### ISSUE TITLE
Emergency Medical Transportation out-of-network value blanking after Save

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#172]
```
What steps will reproduce the problem?
1. Log on to PClient5 as a BCBSMA Administrator
2. Click on Manage Plan
 Enter search criteria:
 Effective Date - 2015
 Market Segment - Connector
 Product Group Type - HMO Blue LOcal
 Plan Type - Standard
 Click - Show Me Plans
3. Hover cursor over desired plan (
600387HR_HMO_Blue_Ded_500_Limited_Cost_Sharing_80-0243HCCSCONLCS1-1-15) to 
select The drop down box with 3 choices will appear
 Select Create a new plan from this plan"
4. Click on Custom Plan Button
5. Click on Common Medical Event tab
6. Go to Emergency Medical Transportation field
7. Change out-of-network value to 20% coinsurance
8. Proceed to save/validate


Actual Result:
Emergency Medical Transportation out-of-network value defaults to blank


Expected Result:
This should capture save (20% coinsurance)


```

Original issue reported on code.google.com by `wcd82...@gmail.com` on 9 Jun 2015 at 10:47

**Comment by willdwyer** [comment]
This defect was discovered to still exist today by one of the BEs.

Please see the following steps to replicate this defect:
1. Log on to PClient5 as a BCBSMA Administrator
2. Click on Manage Plan
   Enter search criteria:
   Effective Date - 2015
   Product Group Type - Blue Care Elect
   Plan Type - Standard
   Click - Show Me Plans
3. Hover cursor over either an HCCS plan or a non-HCCS plan
   select The drop down box with 3 choices will appear
   Select Create a new plan from this plan"
4. Click on Custom Plan Button
5. Click on Common Medical Event tab
6. Go to Emergency Medical Transportation field
7. Change Cascade Options to No Cascade
8. Proceed to save/validate

See screenshots for results of what occurs.  Please fix globally.

<img width="841" alt="screen shot 2015-11-02 at 4 38 20 pm" src="https://cloud.githubusercontent.com/assets/13453008/10895209/f8266c04-8180-11e5-8085-4b894e922c20.png">
<img width="848" alt="screen shot 2015-11-02 at 4 21 10 pm" src="https://cloud.githubusercontent.com/assets/13453008/10895210/f828682e-8180-11e5-8121-0c975902cb9c.png">

**Comment by TimHeasley** [comment]
Will,
The workbook has been updated and tested in PClient5.  Please retest and after you confirm/approve we can move the workbook to Production.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This is still a defect.  I tested generating and editing a custom out of standard plan 800078HR_Blue_Care_Elect_Enhanced_Value_80-0135HCCSMM1-1-16, and encountered the error.  See screenshot.

![screen shot 2015-11-03 at 4 26 30 pm](https://cloud.githubusercontent.com/assets/13453008/10922187/d0e4f6ca-8247-11e5-8361-d1cde3d7d156.png)

**Comment by TimHeasley** [comment]
Will,
Can you provide more information regarding the issue?  The field is no longer blank.  
Selecting No cascade will allow the circled field to remain the same.
Thank you for your help,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Per the above screenshot, the No Cascade option is selected...

I copied and pasted 20% coinsurance in all the fields under Emergency Medical Transportation.  Upon saving, the value in In-Network (Highest Cost Share) was changed to $150/visit.  This was likely cascaded from a previous field.

If you have any other questions, let me know.

**Comment by TimHeasley** [comment]
Will,
Thank you for the details. We updated the workbook and have tested in PClient5.  It is now working correctly. Please retest at your convenience. We will move to Production after you have approved the fix.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This looks fixed.

Please move to production.

**Comment by TimHeasley** [comment]
Will,
Workbooks have been moved to Production and are ready for retest.
Please retest and close issue after confirmation of fix.
Thanks,
Tim

**Comment by willdwyer** [comment]
Retested... this look fixed, and is now being closed.
