### ISSUE TITLE
Header from previous custom plan generated remains on header - AB-146

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#221]
```
What steps will reproduce the problem?
1. Log on to production as a BCBSMA Administrator
2. Click on Manage Plan
3. Search for any custom plan
4. Create a Custom Plan
5. Generate Final PDF with disclosures
6. Go back to manage plan interface
7. Search for a standard plan
8. Hover over plan, click plan document options
9. Generate Final PDF with disclosures

Actual Result:
See screenshot. Notice how header from previous custom plan is still there.

Expected Result:
This should not replicate from previous plan generated.

```

Original issue reported on code.google.com by `wcd82...@gmail.com` on 2 Jul 2015 at 6:41

Attachments:
- [Screen Shot 2015-07-02 at 2.30.14 PM.png](https://storage.googleapis.com/google-code-attachments/bcbsmaissuestracker/issue-221/comment-0/Screen Shot 2015-07-02 at 2.30.14 PM.png)

**Comment by TimHeasley** [comment]
AB-127 and AB-146 are in queue to be picked up following the closure of 2 other issues on the employer enclave. In priority ranking, AB-127 will be picked up first, followed by AB-146. This may stretch into Sprint 6 based on capacity and timing of the 2 other bugs resolution (Sprint 5: 7/29-8/11, Sprint 6: 8/12-8/26).

**Comment by TimHeasley** [comment]
Update for this issue: 

Due to a higher priority issues on the employer enclave, these have not been picked up yet.  They are first in line pending the resolution of the production bugs that are currently in progress with development.

Currently, it is not anticipated that they will begin before the next sprint (Sprint 6), which starts next Wednesday.

**Comment by willdwyer** [comment]
Hi Tim,

Do you have an update on this item?  Sprint 6 is 8/12 - 8/26.

**Comment by TimHeasley** [comment]
Will, 
I have contacted the product team regarding this issue AB-146 (and issue AB-127).  The product team just resolved a blocker bug today that had precedence over these 2 items.  I will continue to work with the product team to try and get a firm timeframe.  As soon as I know the details I will add them here.

**Comment by willdwyer** [comment]
Thanks, Tim.  Please keep me updated.

**Comment by markderg** [comment]
Update from Product Team - Items 221 and 183 are scheduled to be completed as part of this Product Sprint.  The completion for these 2 issues is scheduled for 9/8.  **NOTE:  This is provided that no production issues take priority during this period.  Pending the completion of these 2 issues, we will need to account for internal and external testing requiring these code code changes loaded into our test environment and then PClient 5.  Based on the development and testing timeline we will plan on deployment the end of September (9/29) with a tentative timeline below.  
• 9/8 – Completion of Development
• 9/9 – Deploy code for internal testing
• 9/10, 9/11, 9/14 – Services Testing in CPE2
• 9/15 – Deployment to PClient 5
• 9/16 – Services Testing in PClient 5
• 9/18 – 9/22 -  BCBSMA Testing in PClient 5
• 9/23 – Go/No Go (BCBSMA and HR)
• 9/24 & 9/25 – HR QA Validation of Code as part of Deployment to Production
• 9/28 – Deployment to Production
• 9/29 – Post Production Checkout by BCBSMA

**Comment by TimHeasley** [comment]
Tested in PClient5 and the plan header appears correctly.  The previous plan name does not appear. Ready for retest.

**Comment by willdwyer** [comment]
Hello,

This appears to be fixed.  Please move to production.

**Comment by michparrish** [comment]
great thank you! we are looking to hopefully deploy the code to production by 9/25, but more to come in an official email from Mark.

**Comment by markderg** [comment]
Looking to Deploy Code to Production on 9/25.  See sequence of events below.  

Reason for Deployment:  Fix 2 defects:  1).  Header from previous custom plan generated remains on header -#221/Issue AB 146 in JIRA & 2).  Plan name under the selected plan details tab - #183/Issue AB 127 In JIRA
Deployment Tasks
HR Testing in CPE2:  Tim Heasley
HR Testing Approval Date in CPE2:  9/15
HR Testing in PClient 5:  Tim Heasley
HR Testing Approval Date in PClient 5:  9/16
BCBSMA Testing in PClient 5:  Will Dwyer
BCBSMA Testing Approval Date in PClient and Promotion to PROD:  9/17
HR Approvers of Code Deployment to PROD:  Mark Der Garabedian, Michelle Parrish, Kris Kennedy, and Judy Li
HR Approval Date:  9/17
Timeline for HR QA Testing:  9/23 and 9/24
Timeline for Deployment:  9/25 at 10 pm
Timeline for BCBSMA Post Production Checkout:  9/28

**Comment by markderg** [comment]
[P19 5 11 29 Code Deployment 9.25.15 V2.xlsx](https://github.com/g4gaurang/bcbsmaissuestracker/files/2628/P19.5.11.29.Code.Deployment.9.25.15.V2.xlsx)

Final deployment checklist attached with all required approvals and tasks.

**Comment by willdwyer** [comment]
Hello,

While doing a health check on this item, we encountered an issue.  See the screenshot below, which shows that the standard stock # populated where the HR job # should be.  This came out of creating a custom plan out of standard plan 800280HR_Master_Medical_80-0129LG1-1-16.  We are opening a new defect for this.

![screen shot 2015-09-28 at 2 27 51 pm](https://cloud.githubusercontent.com/assets/13453008/10145177/952121a0-65ef-11e5-8a9a-67a6fb2202b0.png)

**Comment by michparrish** [comment]
Hi Will,

I noted in the new defect that I was not able to recreate this in our Shadow environment or in Prod, using both ways to get into the Configurator (Dashboard > Manage Plan and search and Content Library > Edit > Manage Plan). I found too that prior attempts by you show that the job number shows the right number in the right fields. 

Please test again and let me know if you're able to recreate this or not. I cannot. Thank you.

**Comment by michparrish** [comment]
Hi Will,
Can you please close this item if the testing has proven successful? Barring the other defect that you found through this testing. thank you.

**Comment by willdwyer** [comment]
Hi Michelle,

I will close this specific defect, as the issue noted above does not directly pertain to the header from the previous custom plan remaining on generator.  However, the defect that was open for the stock # populating where the HR job # should be on the plan header will remain open (defect # 258).  I have tested a number of scenarios, and have not encountered an instance with the header from previous custom plan remaining on generator.  As a result, this defect will be closed.
