### ISSUE TITLE
Permissions testing on the Highroads system

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#225]
```
This task is being opened to track the testing effort for the new agreed upon 
user permissions to the Highroads system. HR will deploy the changes to 
Pclient5 for testing on 7/8 and let inform BCBSMA when they are ready to test.

```

Original issue reported on code.google.com by `g4gaur...@gmail.com` on 7 Jul 2015 at 9:59

**Comment by willdwyer** [comment]
Hello,

We encountered a couple permissions errors this morning.  There are 2 discrepancies with the Power User role in using Configurator.

The issues are as follows:
1. Power User should be able to create a custom plan from a standard plan.  I.e. if a user goes to configurator, and in search, specifies to search for standard plans... on search results screen, if a user hovers over it, specifies create a new custom plan... he/she cannot do so (see screenshot)
2. Power User should NOT be able to edit standard plans from the configurator.  He/she should see an error message upon doing so (2nd screenshot) 
   ![screen shot 2015-07-27 at 10 13 42 am](https://cloud.githubusercontent.com/assets/13453008/8910135/18e1d9b8-3453-11e5-885a-9fc9b8baf6d2.png)
   ![screen shot 2015-07-27 at 11 14 06 am](https://cloud.githubusercontent.com/assets/13453008/8910138/1bb4c0e2-3453-11e5-939e-1bd100f0383c.png)

**Comment by michparrish** [comment]
researching issues

**Comment by michparrish** [comment]
Standard plan editing has been fixed - after testing in pclient5 at the end of June, the item was closed without moving the updated Validation Mapping doc to Prod. This has now been moved and tested - errors received when I try to edit a Standard plan and create a Standard from a Standard in the configurator.

Still working on the permissions item - all permissions look correctly set up and it was confirmed last week that the Power User was all set. I have sent this item to our QA Dept to assist me as Steve H is on vacation.

**Comment by michparrish** [comment]
Item #1 above did not have to do with Permissions as they stand for today (after the cleanup) - the issue was that the mapping for the Custom Draft plan designs was still pointing to the Plan > Draft > Custom folder. We had not updated permissions on this specific folder going into Prod b/c as soon as the all permissions were approved, we would flip the switch on the new Custom Draft Plan Designs plan master folder and the mapping would be complete. NOTE: the new mapping was already tested and approved in pclient5, we hadn't moved it b/c we didn't want to interrupt any work being done in Prod.

Note sent to Will for approval to update the mapping in Prod to the new folder, and then this item will be fixed.

Please also note we are still pending overall permissions approval, which was pending Paul G's retest today.

**Comment by willdwyer** [comment]
Hi Michelle,

I tested, and confirmed that the permissions update has been made to standard plan editing, and that part is now fixed.

**Comment by michparrish** [comment]
Hi Will,
thank you - I just want to document and be clear that the standard plan editing issue was not a permissions issue. It was a Validation Mapping document issue. 
thanks!

**Comment by michparrish** [comment]
Per Will's approval, we have updated the app properties mapping in Prod to point all draft custom plan designs to the new Custom Draft Plan Design plan master folder, located under the Marketing and Sales - Custom folder. I tested creating a new custom plan from a standard plan in the configurator, logged in as Jenn D, and am no longer receiving the permission error seen earlier.

**Comment by markderg** [comment]
Will...Looking to close this item out as part of the permissions validation in PROD.  Do we have confirmation that Paul G's retest is completed in PROD.  That was the final task we were waiting on from BCBSMA.  Please advise.  Many thx, Mark

**Comment by willdwyer** [comment]
Hi,

I re-tested permissions with Paul Grizey’s log-in, and I confirm that the fix (access to the standard folder) has been made.

Also, I tested the validation mapping issue, and I was able to create a custom plan from a standard plan in the configurator.  So, that has been fixed as well.

@jddecoste Can you please test with your ID as well?

Once confirmed, this can be closed.

**Comment by jddecoste** [comment]
I have retested both ways; editing the standard plan and creating a custom
they are both working correctly now

**Comment by willdwyer** [comment]
Hello,

This issue is closed.
