### ISSUE TITLE
Adding 2016 dropdown list of values to the configurator

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#230]
Project Member Reported by BCBSMAMarketing4, Yesterday (25 hours ago)
This task is being created to track updates to the 2016 List of values to the eligible options clipboard of the product configurator. An email was sent out with the newer values to Jenn Jackson on Friday, July 10,2015. Mark D. was copied on the email by Jenn Jackson.

Yesterday (23 hours ago) #1 michelle.at.highroads
meeting set up with Will to answer outstanding questions, 7/21.

**Comment by willdwyer** [comment]
Good morning,

I wanted to follow up – Will, Steve and I just met and answered the questions below, as well as put together a timeline for this work.

1)      Changes will be effective as soon as HighRoads can finish the work
2)      After using the tool a bit, there were values that either weren’t needed or were missing – needed to make those changes
3)      Timeline: As soon as HighRoads can complete the changes.

We will start work on this today and are looking to finish development and internal QA by the end of the week. **Note: Steve A is on vacation beginning 7/24, but will loop in Alex A. as needed, if development is not finished (or to handle any QA fallout).
We will aim to hand over the updates to BCBSMA for QA in pclient5 by Monday, 7/27 and hopefully move the workbooks to Prod by 7/28.

We have asked Will to reach out to us by today if there was anything missing from the original request that he would like included.

Please let me know if there are any further questions.

**Comment by g4gaurang** [comment]
Any updates on this one @michparrish ?
Per your notes above "We will aim to hand over the updates to BCBSMA for QA in pclient5 by Monday, 7/27 and hopefully move the workbooks to Prod by 7/28."
CC @willdwyer @jddecoste

**Comment by michparrish** [comment]
We are still in the process of validating our test results per the requirements. We do not yet have an updated ETA on these updates at this time. We will post that as soon as we have a better idea.

**Comment by g4gaurang** [comment]
Any updates  on this @michparrish @markderg ? We would like to get these in the system for training next week.

CC @jddecoste

**Comment by michparrish** [comment]
We are finished with the HMO workbook updates/testing. We will be moving those to pclient5 today after confirmation that the calculator is working as expected. 
PPO workbooks are being updated now and will be tested Monday, hoping to release to pclient5 on Monday or Tuesday. Therefore, all LOV updates will be ready for BCBS testing by Tuesday 8/11.
Once tested and confirmed success, we will move the workbooks into Production.

**Comment by michparrish** [comment]
PPO workbooks have also been tested and are ready for BCBS testing in pclient5, in addition to the HMO workbooks that were posted yesterday along with the calculator. @g4gaurang @willdwyer @jddecoste

**Comment by willdwyer** [comment]
Hi Michelle, I am testing the LOVs across all workbooks, and should be complete with this by tomorrow.

**Comment by willdwyer** [comment]
Michelle,

It appears that the only new 2016 LOVs that were added were for the pharmacy coverage (4 tier options).  Please add the other additional values for the other fields that were on the spreadsheet.  These are all highlighted in green.  If you need me to send the spreadsheet again, let me know.

**Comment by michparrish** [comment]
apologies for the missed items. We will update, test and let you know when they are ready for your review.

**Comment by michparrish** [comment]
@willdwyer Additional values have been updated and tested, along with any cascading rules, etc. Please test and let us know if there are any issues. Thank you!

**Comment by willdwyer** [comment]
Hi Michelle,

I am noticing issues with the cascading with the PPO Blue Options plans.

When I input either of the new eligible options below, and select cascade, the attached screenshot(s) depicts what occurs
$500 per admission/$500 per admission/$1,500 per admission in-network / 20% coinsurance out-of-network
No charge/$500 per admission/$1,500 per admission in-network / 20% coinsurance out-of-network

![screen shot 2015-08-12 at 2 20 40 pm](https://cloud.githubusercontent.com/assets/13453008/9233236/f1de071a-40ff-11e5-8a07-1ba0bb822c9f.png)
![screen shot 2015-08-12 at 2 25 12 pm](https://cloud.githubusercontent.com/assets/13453008/9233239/f342a994-40ff-11e5-851e-c8ca1e6078ed.png)

**Comment by michparrish** [comment]
this has been fixed - please retest. Thank you

**Comment by willdwyer** [comment]
Hi Michelle,

This specific component has been fixed, but we are still encountering other issues with this.  Please see below.

When I input any of the 4 tier pharmacy eligible options for PPO Plans, and select cascade all, the cascading does not work.  See screenshot.

![screen shot 2015-08-14 at 4 06 34 pm](https://cloud.githubusercontent.com/assets/13453008/9283037/88c45f22-429e-11e5-8982-f8058151b559.png)

**Comment by michparrish** [comment]
Will it doesn't look like there is a semicolon after 'retail' - are you copying/pasting from the Eligible Options LOV? I just copy/pasted this value and it cascaded correctly.
![4t rx cascade](https://cloud.githubusercontent.com/assets/13471811/9283748/06fea17c-42a4-11e5-909b-5cbc5ff5e9c0.JPG)

**Comment by willdwyer** [comment]
Hi Michelle,

This was taken from the Eligible Options field (directly copied and pasted).  I don't remember specifically which plan the above screenshot was taken from, but I am going to do more testing on this.  As long as every PPO plan has the semicolon in that spot, then I am fine with it.

**Comment by willdwyer** [comment]
Hi Michelle,

So, I confirmed that the cascading issue above has been resolved.  However, we noticed that certain LOVs are missing.  See the attached screenshot, demonstrating that certain values in ER cost share do not appear in the Eligible Options dropdown list.  $35 per visit and $10 per visit are both missing.

Note that this was replicated by creating a custom plan out of standard plan 800168HR_PPO_Blue_Options_v.4_80-0222M... 
<img width="1200" alt="screen shot 2015-08-17 at 1 10 35 pm" src="https://cloud.githubusercontent.com/assets/13453008/9311094/22f146c4-44e2-11e5-8970-4226b3949ee2.png">

Please fix globally.

**Comment by michparrish** [comment]
Thanks, Will. Our apologies - we're investigating now as we were certain we got all of the updates. Will update the item when ALL LOV options are updated and ready.

**Comment by michparrish** [comment]
Will, after further review - we made the updates for all of the LOV values that were included in the document that we had. The ones you note that are missing above were not included on this document. Were there additions made after the doc was sent to us? please see the attachment
![lov values](https://cloud.githubusercontent.com/assets/13471811/9314550/9a43195e-44f7-11e5-91ba-f7eea2e118ea.JPG)

**Comment by willdwyer** [comment]
Hi Michelle, I will research this, and get back to you.  If I can confirm that these 2 values ($35 per visit, $10 per visit) are no longer required for ER cost share, then we are good with this.  I will leave this assigned to me.

**Comment by willdwyer** [comment]
Hi Michelle,

I was able to confirm that these 2 values were actually taken out as options by the BEs, and removed from a later spreadsheet, so the version you have IS correct.  As mentioned, everything else looks good with the 2016 LOVs, so I will now close this request.
