### ISSUE TITLE
New government mandated requirement  - Provision to Require Online Access to Individual Underlying Policy or Group Certificate

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#231]
**Government Requirement:** The government departments have released a new requirement that affects the content on the SBC and will require us to change a mapping. More specifically, they have instructed plans to change the web address on the disclaimer section up top on the first page of the SBC to provide the consumer with a direct link to their policy or plan document. 

http://www.cms.gov/CCIIO/Resources/Fact-Sheets-and-FAQs/Downloads/Fact-Sheet_SBCFinalRule-6-11-15-MM-508.pdf

**System Impact:** Currently the HR plan design field "Website" is mapped to the disclaimer section web address AND also to the www.bluecrossma.com web address link in the footer on first and last page. 
Due to  change in the government requirement we will need to decouple this mapping and create a new HR plan design field that exclusively maps to the Disclaimer section plan document web address for plans effective 1/1/2016 

**System Requirements:** 
1. Create a new HR plan design field called FirstPageDisclaimerWebsite that exclusively maps to the Disclaimer section plan document web address.
2. The existing website plan design field  should be decoupled to link only to the footer web address (currently www.bluecrossma.com) on both the first and last page.
3. Add FirstPageDisclaimerWebsite on the configurator UI screen in the appropriate location so users can customize.

![image](https://cloud.githubusercontent.com/assets/10272072/8875901/34eca4d2-31ea-11e5-9483-99fee6aa6c68.png)

**Comment by michparrish** [comment]
Briefly discussed this item last week with Gaurang and team and estimated that we could have this work completed and approved by 8/21, with move to Prod by 8/24. 
Steve A will need to complete this work and he is on vacation this week. He is also due to start the FMPro # enhancement work directly upon his return to the office on 8/3. We hope to start on this work around 8/5 or 8/6, after we hand off the FMPro # to BCBSMA for testing.
Once this timing is run by Steve A, I will update the item with any changes in this schedule if he does not agree with the timing.

**Comment by michparrish** [comment]
Questions for requirements (let me know if you'd like to have a quick meeting or if answering in this forum is ok):
1) Where would you like the new field located on the plan design, or does it matter? Please let us know where you'd like it.
2) Validation rules in the Configurator for this field - we can set to mandatory, please confirm this is a requirement. Are there any other rules you'd like assigned to this field? NOTE: there are no other rules assigned to the Website fields in the configurator, but I wanted to ask.
3) Location in Configurator: I'd think the SBC Benefit Data page would make the most sense? Do you want the field next to the other Website field or at the end of the page?
4) Name of field in Configurator: do you want it all one word like above or want it to be separate words? "FirstPageDisclaimerWebsite" vs "First Page Disclaimer Website"? with or without asterisk for mandatory?

**Comment by g4gaurang** [comment]
Questions for requirements (let me know if you'd like to have a quick meeting or if answering in this forum is ok):
1) Where would you like the new field located on the plan design, or does it matter? Please let us know where you'd like it.

**Logically, between the Header Plan Type and Website plan design fields.**

![image](https://cloud.githubusercontent.com/assets/10272072/9064303/e21a9de6-3a99-11e5-990f-0f88d10e40d6.png)

2) Validation rules in the Configurator for this field - we can set to mandatory, please confirm this is a requirement. Are there any other rules you'd like assigned to this field? NOTE: there are no other rules assigned to the Website fields in the configurator, but I wanted to ask.
**Use the same validation rules you have for the Website field.**
3) Location in Configurator: I'd think the SBC Benefit Data page would make the most sense? Do you want the field next to the other Website field or at the end of the page?
**Yes, on the SBC Benefit Data Page  and place it between  Plan Type and Website.**
![image](https://cloud.githubusercontent.com/assets/10272072/9064141/289a7418-3a99-11e5-8059-f326d1a90999.png)

4) Name of field in Configurator: do you want it all one word like above or want it to be separate words? "FirstPageDisclaimerWebsite" vs "First Page Disclaimer Website"? with or without asterisk for mandatory?
**Use "First Page Disclaimer Website". Again, conceptually, validation should be similar to the website configurator field (so with the asterisk).
Question: Is it a lot of work to label the website field as Footer website just so the user is distinctly clear now that we have multiple website fields ?**

**Additional Question: On those website fields, Is it possible to type in an alias text and then hyperlink that text to a website. For example: On Excel or other documents you can type any text you want and hyperlink to any website you want to.**
![image](https://cloud.githubusercontent.com/assets/10272072/9064802/2c8ca9bc-3a9c-11e5-87fc-1ee410d4cdf6.png)

**Comment by michparrish** [comment]
Thank you for your responses. Question: Is it a lot of work to label the website field as Footer website just so the user is distinctly clear now that we have multiple website fields ?
- Minimal work for a Configurator UI renaming, however the original name would show on the Missing Mandatory field error. If this field has a default value and is always filled in on the Standard plans, though, reaching this error should be rare.

Additional Question: On those website fields, Is it possible to type in an alias text and then hyperlink that text to a website. For example: On Excel or other documents you can type any text you want and hyperlink to any website you want to.
- No - we believe this was discussed during requirements and we are only able to keep these fields as text without hyperlink functionality.

**Comment by g4gaurang** [comment]
Minimal work for a Configurator UI renaming, however the original name would show on the Missing Mandatory field error. If this field has a default value and is always filled in on the Standard plans, though, reaching this error should be rare.
- Understood. Please change on Configurator UI to say Footer website instead of website.

**Comment by michparrish** [comment]
@g4gaurang just to be certain - do you also want the name of the field within the plan design to be all one word or same as Configurator (which will be "First Page Disclaimer Website"). Please let me know - thanks!

**Comment by g4gaurang** [comment]
> @g4gaurang just to be certain - do you also want the name of the field within the plan design to be all one word or same as Configurator (which will be "First Page Disclaimer Website"). Please let me know - thanks!

Yes, that will work. Thanks.

**Comment by michparrish** [comment]
@g4gaurang sent note re: the following:

I’m prepping for the plan design field addition tonight and had a couple of questions.

First – attached is a list of the current plan designs that are locked in WIP status. Would you be able to have the current owners check them back in please? There is a test one in the first row – maybe this one could just be deleted?

Also – when I search on HR Plan Design doc type and Plan Year 2016, I receive 380 results. Does this sound correct to you? I believe we had around 386 2015 plan designs when we last did structure updates in May, and I know some of the 2015 plans were discontinued for 2016, so this number sounds ok to me as long as you think few new plans have been created for 2016 thus far (which I guess would only be Customs)? Please let me know.

(attachment in email, I forget how to attach here)

**Comment by michparrish** [comment]
new field has been added to all plan designs in Prod. Pending refresh into pclient5 evening of 8/12 to continue with configuration updates on 8/13.

**Comment by willdwyer** [comment]
Hi Michelle,

I encountered an issue when testing.  Please see attached screenshots.  Website is entering as "Click here to enter text"

<img width="1151" alt="screen shot 2015-08-13 at 11 03 52 am" src="https://cloud.githubusercontent.com/assets/13453008/9253432/c3762f36-41ab-11e5-8d23-c4168240ecfd.png">
<img width="889" alt="screen shot 2015-08-13 at 11 08 18 am" src="https://cloud.githubusercontent.com/assets/13453008/9253433/c51f6406-41ab-11e5-97d5-370fe467fd7c.png">

**Comment by michparrish** [comment]
@willdwyer @g4gaurang this has not been released for testing yet. We are still working on the configuration and mapping.

**Comment by willdwyer** [comment]
Got it, thanks.  Your last comment prior was a bit confusing, hence i thought was ready for retest today.

**Comment by g4gaurang** [comment]
@michparrish, @markderg I understand this work is still "in-process" but we would like you to finish the development and deployment on this task at your earliest and notify us so we can complete the standard SBCs. To be more specific, we have in the process of finalizing our 2016 standard  connector SBCs but we can't because  we need to put different weblinks on the footer website and first page disclaimer website but are unable to do so. See screenshot -

![image](https://cloud.githubusercontent.com/assets/10272072/9341498/55065f5e-45c4-11e5-8f77-4a893c265543.png)

**Comment by michparrish** [comment]
@g4gaurang this is almost ready for testing. We are working through one item that we hope to have resolved tomorrow (we weren't able to give it the attention today, as you know). We will let you know ASAP as soon as it's ready for testing.

**Comment by markderg** [comment]
Gaurang:  As part of testing we discovered an issue where we are not able to display a field on the certain types of BCBSMA plan’s SBC Output.   We are able to get the field to display on for EPO, POS, Indemnity, 2 tier HMO and 2 tier PPO SBCs.   The field does not display on the 3 tier HMO and PPO SBCs as well as the 4 tier HMO and PPO SBCs.   

The field in question is “First Page Disclaimer Website”, which currently exists in the plan designs for both production and pclient5.   

As a next step, we ask BCBSMA to test this change in PClient 5 so this can validated.  Once approved by BCBSMA we can move the configuration to production so the field will populate EPO, POS, Indemnity, 2 tier HMO and 2 tier PPO SBCs.

For 3 tier HMO and PPO SBCs as well as the 4 tier HMO and PPO SBCs, we have escalated this as a showstopper issue internally with the Product team.  We understand BCBSMA is looking to generate SBCs as of this Monday.  As a workaround, our recommendation is to have SBCs generated by BCBSMA with the exception of 3 tier HMO and PPO SBCs as well as the 4 tier HMO and PPO SBCs.  Those SBCs can be escalated to HighRoads for manual generation until this issue is addressed.  

Please advise us on your thoughts re this issue and our proposed next steps.  We'd be happy to set up a call to discuss.  

Thx, Mark

**Comment by markderg** [comment]
Bug Number for this issue is #18719.

**Comment by g4gaurang** [comment]
@markderg  A sampling of Single and Two tier plans have been verified on Pclient5. 
and I notice the plan design field “First Page Disclaimer Website” missing on 

  800054HR_Preferred_Blue_Basic_2000_80-0122SG1-1-16 800350HR_Access_Blue_Saver_II_Limited_Cost_Sharing_80-0248CONLCS1-1-16
800368HR_HMO_Blue_Zero_Cost_Sharing_80-0250CONZCS1-1-16

Michelle has them in a locked state currently.
 Let us know once you fix and redeploy.

> For 3 tier HMO and PPO SBCs as well as the 4 tier HMO and PPO SBCs, we > have escalated this as a showstopper issue internally with the Product team.

 Please resolve the issue with 3 and 4 tiers plans expeditiously and move to Pclient5 for testing. Also provide an ETA on the fix after consulting your product team. We will do a  full regression test once you move all fixes to Pclient5 and then on production.

CC @jddecoste

**Comment by michparrish** [comment]
There was a list of plans in Prod that I had sent that were locked - I asked for these to be unlocked by the users before we made the plan design updates and some were not yet unlocked. 800054HR is currently still locked by Natty in both env and she is still locked in 800368 in pclient5 (not me) - please have her unlock. I have updated the 800368 in Prod and 800350 in both environments.

We are treating the issue with the 3/4 tier plans as a blocker bug and all eyes are on this. Will update as soon as we have this fixed and will update first in pclient5 for your team to test.

**Comment by michparrish** [comment]
@g4gaurang @jddecoste 
The issue with the 3 and 4-tier plans has been resolved. Please continue testing in pclient5. Thank you for your patience as we worked through this.

**Comment by g4gaurang** [comment]
> 800054HR is currently still locked by Natty in both env and she is still locked in 800368 in pclient5 (not me) - please have her unlock. I have updated the 800368 in Prod and 800350 in both environments.

@michparrish Natti has unlocked . Please complete your plan design changes and let us know.

**Comment by michparrish** [comment]
@g4gaurang all set

**Comment by g4gaurang** [comment]
> michparrish commented 21 hours ago
> @g4gaurang @jddecoste 
> The issue with the 3 and 4-tier plans has been resolved. Please continue testing in pclient5. Thank you for your patience as we worked through this.

Verified but Not fixed. See screenshot from Pclient5.

![image](https://cloud.githubusercontent.com/assets/10272072/9413358/69e72704-47ff-11e5-854e-96b7d77aebc1.png)

**Comment by michparrish** [comment]
Hi Gaurang,
as with other testing, we need to know what plan design you used, etc to be able to troubleshoot what you're seeing. Please post details so we can look into this ASAP. thank you!

**Comment by g4gaurang** [comment]
> Hi Gaurang,
> as with other testing, we need to know what plan design you used, etc to be able to troubleshoot what you're seeing. Please post details so we can look into this ASAP. thank you!

Hi Michelle, As the plan name indicates it is HMO Blue New England Options Deductible III v.5 plan. You can try any of the 3 market segments versions of the plan and you will still get the same results indicated in the screenshot above.

800042HR_HMO_Blue_NE_Options_Ded_III_v.5_80-0258SG1-1-16
800105HR_HMO_Blue_NE_Options_Ded_III_v.5_80-0258MM1-1-16
800255HR_HMO_Blue_NE_Options_Ded_III_v.5_80-0258LG1-1-16

**Comment by TimHeasley** [comment]
Guarang,
I tested each of the plans you listed above and did not have any issues. The test website appeared in all possible formats. I have attached a screenshot of one of the plans and also listed each of the plans that were tested.
Thanks,
Tim

![800255_testing](https://cloud.githubusercontent.com/assets/13483804/9417105/ad0fae94-4817-11e5-9a38-d7a01db9674b.JPG)

**Comment by willdwyer** [comment]
Hi Tim,

We tested a few samples on PCLIENT5, and this looks fixed now.  Please move to production, and let us know once this is done.

**Comment by michparrish** [comment]
the current workbooks in pclient5 have the LOV and FMPro # configuration in them as well. Given that the LOVs have been approved but the FMPro# is still in process, we need to work on decoupling that configuration from the workbooks first, test to ensure no issues or impacts are found from that removal, and then upload the workbooks to Prod. We will leave the versions WITH the FMPro# in pclient5 for continued testing. 
The workbooks for this enhancement will be ready for Prod by Monday morning. We will let you know once they are posted.

**Comment by michparrish** [comment]
All configuration has been loaded to Prod - please test and confirm. thank you.

**Comment by willdwyer** [comment]
Hi, this looks fixed, and is now being closed.
