### ISSUE TITLE
Custom plan created in production errors out during document generation

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#235]
**What steps will reproduce the problem?**
1. Log on to Production as ggorad01
2. Click on Manage Plan
Enter search criteria:
Effective Date - 2016
Financial Arrangement - Insured
Market Segment - Large Group 100+
Product Type - POS
Plan Type - Standard
Click - Show Me Plans"
3. Hover cursor over desired plan (800203HR_Blue_Choice_Value_Plus_80-0125LG1-1-16) to select The drop down box with 3 choices will appear
Select Create a new plan from this plan"
4.Click on Custom Plan Button
5. Fill out the mandatory fields on the appropriate tabs and go to plan documents 
6. Select draft, with disclosures, PDF output  and click submit.

**Actual Result:**  See screenshot error below

![image](https://cloud.githubusercontent.com/assets/10272072/9138037/96e564a2-3cef-11e5-9208-d9d509654136.png)

**Expected Result:**  User should be able to generate the PDF. 

FYI... I was able to generate the PDF on this on August 4,2015 for     3425242_TEST_ACCOUNT_&_COMPANY_#VALUE! for which I used the same standard base.

**Comment by michparrish** [comment]
@g4gaurang @TimHeasley I removed all versions since last night that I had worked on to add the new field in and was able to generate files. This item can be retested and closed. We're still working on all other issues related to this plan. Other POS plans work, so it is not a workbook-related item. More to come...

**Comment by michparrish** [comment]
sorry - issue is that since we added the new fields, things shifted down. the calculator needs to be adjusted as well and we hadn't done this (this was on our list to update after the fields were added). Updating now and posting ASAP.

**Comment by michparrish** [comment]
@g4gaurang  calculator has been updated and I just tested on the plan above and was able to generate a document successfully. Please retest and confirm. Thank you!

**Comment by g4gaurang** [comment]
Verified and Fixed.
