### ISSUE TITLE
Searching for User - Dropdown list should populate

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#238]
Hello,

Please see steps below.
1. Click Search on Dashboard
2. Click Advanced Search tab
3. Click + to expand Additional Options
4. Change Status: to Modified By
5. Change User: to User
6. An additional box will populate below.  (See screenshot)  This should be a dropdown list of all eligible users.  Currently, the box asks for the user to type the user name in; however, due to possible nicknames, and correct spelling of user, this could be cumbersome.  Please populate a dropdown list for this field.
   ![screen shot 2015-08-06 at 5 35 35 pm](https://cloud.githubusercontent.com/assets/13453008/9145498/e89b2d9e-3d22-11e5-8443-0acab266fcc9.png)

Thank you,

**Comment by michparrish** [comment]
Hi Will - this is product-wide and does not have the ability to have a dropdown. That said, please fill this field with the way a person's name would show up in the Modified By column of content library or a search result:
![search by user](https://cloud.githubusercontent.com/assets/13471811/9145593/cc8d946a-3d23-11e5-8f1f-a5565363ebf8.JPG)

**Comment by willdwyer** [comment]
Thanks, Michelle.  We will close this request.
