### ISSUE TITLE
Standard Values field should be renamed to Eligible Options 

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#239]
See screenshot:
![screen shot 2015-08-11 at 5 17 33 pm](https://cloud.githubusercontent.com/assets/13453008/9225009/aabee10e-40d4-11e5-9a19-5fcf7337d79d.png)

Please follow steps below to reproduce issue.

What steps will reproduce the problem?
1. Log on to PClient5 as a BCBSMA Administrator
2. Click on Manage Plan
 Enter search criteria:
 Effective Date - 2015
 Product Type - PPO
 Plan Type - Standard
 Click - Show Me Plans"
3. Hover cursor over desired plan (ç) 
to select The drop down box with 3 choices will appear
 Select Create a new plan from this plan"
4. Click on Custom Plan Button
5. Click on Common Medical Event

Actual Result:
Multiple fields are named Standard Values

Expected Result:
These should all be named Eligible Options

Please correct logic globally.

This issue is similar to a prior defect (#168)

**Comment by michparrish** [comment]
@willdwyer They've all been updated in pclient5 and Prod. Please retest.

**Comment by willdwyer** [comment]
Hi Michelle,

I looked in PCLIENT5 and Production, and this appears to be fixed, and is now being closed.
