### ISSUE TITLE
Enhancement request: increase timeout period to 300 mins from 40 mins - BPMS-I-13

### ISSUE THREAD

**Issue by michparrish** [willdwyer/bcbsmaissuestracker#243]
BCBSMA would like to request to increase the timeout period when using the HR system from the current 40 mins to 300 mins (5 hrs). HR standard is 110 mins but this was changed in the past by a request from BCBSMA IT. The timeframe of 40 mins no longer meets BCBS's needs and they would like to increase to 300.

**Comment by markderg** [comment]
We need final approval from Jenn DeCoste/BCBSMA before moving forward with this enhancement.  Thx, Mark

**Comment by markderg** [comment]
Waiting on final approval from BCBSMA IT.  Jennifer Jackson is seeking approval from BCBSMA IT.  E-mail below.
![e-mail re final approval pending from bcbsma it](https://cloud.githubusercontent.com/assets/13459490/9331337/ddd01286-458c-11e5-94f3-ff4ada47b7a4.JPG)

**Comment by markderg** [comment]
Assigned back to BCBSMA to secure approval from BCBSMA IT.  Thx, Mark

**Comment by jddecoste** [comment]
Check on status w/ IT today. Person we need info from will return from vacation on 8/24.
Jen Jackson continues to remain on point.

**Comment by markderg** [comment]
NOTE: Once this enhancement is approved it will be 1 hour of development time and will be part of a maintenance release (overnight).

**Comment by markderg** [comment]
Approved by BCBSMA per e-mail below from Jen Jackson.

Next Steps:  1).  Update Ops Manual with new time out period (300 minutes), 2).  Confirm HR IT deployment date of this change.  Mark D. will follow up on both items 1 and 2.  

From: <Jackson>, Jennifer Jennifer.Jackson@bcbsma.com
Date: Monday, August 31, 2015 at 12:12 PM
To: bcbsma Jennifer.DeCoste@BCBSMA.com, Mark Der Garabedian mdergarabedian@highroads.com
Cc: "Soleyn, Matthew" Matthew.Soleyn@bcbsma.com, "Grundza, Jeremy" Jeremy.Grundza@bcbsma.com
Subject: FW: SSO timeout policy?

HI Jenn and Mark,
Per the below email exchange, I approve extending the HR SSO timeout window as long as we document within the operations guide, what that timeout should be.

Please make sure that me and Matt Soleyn continue to remain the contacts for SSO in the operations guide until further notice.

Jen

**Comment by markderg** [comment]
Update re previous comment:  1)  Ops Manual will be updated by close of business on 9/2 and 2).  Change from 40 minutes to 300 minutes will go into PROD tomorrow night pending BCBSMA final approval.

Change will take place during maintenance window between 10 am - 11 pm.  System will be down at this time.  This change will be only be made in production.  PClient will not be changed.  Its timeout will remain at 30 minutes.  

Please acknowledge receipt of this message and "approved" in the body of your comment so we can proceed forward with this change scheduled for tomorrow night - 9/2.  Thanks, Mark

**Comment by g4gaurang** [comment]
> Change will take place during maintenance window between 10 am - 11 pm. System will be down at this time

@markderg Did you mean 10 **pm** to 11 pm - A one hour window ?
We cannot afford production going down between 10 am - 11 pm especially during open enrollment.

**Comment by markderg** [comment]
My apologies. The time should be 10 pm to 11 pm-During 1 hour maintenance window. Thanks. Mark.

**Comment by jddecoste** [comment]
BCBSMA approval to move forward with change in Production to extend timeout period from 40-300min within the window of 10:00pm-11:00pm on 9/2/15

**Comment by markderg** [comment]
Successful Deployment of configuration change in production.  

Background of deployment and post deployment action items below.

![issue 243](https://cloud.githubusercontent.com/assets/13459490/9650488/982b1e00-51d1-11e5-82e3-c6df413a0cf8.JPG)

**Comment by markderg** [comment]
Hi...

I am looking for an update regarding the status of the production checkout by BCBSMA.  Thx, Mark

**Comment by g4gaurang** [comment]
This Enhancement/task is completed and the time out increase has been verified and fixed in production. In addition, I checked with HR if there is a link between #254 and this change and they had this to say. 

> michparrish commented 37 minutes ago
> I don't logically see a correlation between a simple change to a timeout period and the ability to upload documents, but I have noted this change to our QA Dept as well so they have all of the necessary information. They will work with IT to determine if this had any impact.

This is being closed.

**Comment by markderg** [comment]
Thanks Guarang for your update.  We will update the Ops Manual and post to CL.
