### ISSUE TITLE
BLOCKER issue - Word SBC Templates generated through the system show  junk data in the Excluded services section.

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#248]
Over the weekend we discovered a blocker bug we wanted to inform you of:

Word SBC documents, both final and draft versions, generated from Prod or Pclient5 are showing incorrect bullets in the Services NOT Covered/Other Covered Services boxes. They are repeating ‘Acupuncture’ and ‘Bariatric Surgery’ in them rather than showing the proper values.

I have opened a blocker bug for this issue this morning, #18720. I will keep you notified of the status. I will also open a new item in GitHub.

![image](https://cloud.githubusercontent.com/assets/10272072/9442201/91a23a22-4a48-11e5-9762-d6cb0898f7f2.png)

![image](https://cloud.githubusercontent.com/assets/10272072/9442207/9acb7ad2-4a48-11e5-8ce3-98efcd21d38f.png)

NOTE: PDFs, both Draft and Final, are not impacted by this. Users can still generate and download the PDF versions either from Content Library or from the SBC Preview page in the Configurator. This ONLY impacts Word versions.

**Comment by michparrish** [comment]
All templates have been updated and tested in Prod and pclient5. This item can be closed.
That section of the template became corrupt during one of our last updates - we cannot tell how or why. We have fixed this section and all is working as expected now. For future - we will do a distinct set of regression tests whenever there are template updates completed.
screen shot of updated word doc in pclient5:
![3t in pclient5](https://cloud.githubusercontent.com/assets/13471811/9445090/47e5aefe-4a58-11e5-9356-e18310c4c265.JPG)

**Comment by g4gaurang** [comment]
Validated on both Pclient5 and Production across a sample set of  2016 plans. Issue looks fixed. This issue has been in production alteast since the second week of June 2015. Any word documents created since June 6th 2015 that were corrupt were also deleted as part of cleanup. 2015 word docs have not been validated since they cannot be generated.
