### ISSUE TITLE
Remove QR codes and accompanying wording from the footer off all SBC templates

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#250]
BCBSMA would like to remove QR codes and accompanying wording from the footer off all SBC templates.

![image](https://cloud.githubusercontent.com/assets/10272072/9496533/b71bc236-4bde-11e5-85d9-c2e86c9b9f0b.png)

**Acceptance Criteria** : All SBC generations done through the HR system going forward will not have QR codes and accompanying wording in the footer.

The footer content alignment will mirror 2014 SBC footer placement.

![image](https://cloud.githubusercontent.com/assets/10272072/9496565/ecd677c2-4bde-11e5-9c42-0bd1db567eae.png)

**Comment by michparrish** [comment]
in process

**Comment by michparrish** [comment]
All templates have been updated and tested in pclient5. One plan per tier but all 6 versions of the documents.
If you wish to run plans yourself, please feel free to.
If you wish to just review the ones that I generated, they are in Custom > michelle test > all docs generated at 2:33 and after. I already sent the 1-tier samples to Gaurang for review and he approved. These are the 2, 3 and 4-tier sets. (the 1-tier is from around 10:58am this morning if you want to review again).
Thank you!

**Comment by g4gaurang** [comment]
A few samples across market segments, tiers , document types, plan and product types were tested and changes look good to be moved to production.

**Comment by michparrish** [comment]
Templates are uploaded in Prod and ready for review. Once confirmed, please feel free to close out item. Thanks!

**Comment by willdwyer** [comment]
Hello,

I tested in production, and this looks to be fixed.  I will close now.
