### ISSUE TITLE
Ability to manually override dynamically generated calculator amounts 

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#257]
We would like the ability to override the final  calculator numbers manually through  the Plan Design/ Configurator User Interface for both Maternity and Type II Diabetes.  This will help us create more plans within the system thereby increasing the value we get out of the system and it's utility.

Some examples include plans with dual cost share (25% coinsurance + $250 copayment) etc. which have to be done outside of the system.

**Current State**
The current plan designs have data fields to store calculator output data for both Maternity and Type II Diabetes ( although  these fields are not updated with newer amounts when calculator is rerun). In addition, the configurator also has tabs to capture both Maternity and Type II Diabetes output values through the UI.

Per our understanding, the calculators are dynamically triggered every time during document self-generation. We do not have the ability to manually override any dynamically generated calculations.

**System Requirement**
For any plan design, when a user indicates No Calculator Run in the configurator and then goes to the Having a Baby and/or Type II diabetes tabs and manually updated/overrides the output amounts, saves and re-generates the SBCs, the system should  capture the amounts the user entered manually on the SBC  output document overriding any system generated calculations.

In addition, we would also like to know if it is possible to override directly through the edit plan design interface.

**Comment by michparrish** [comment]
We set up the configurator to have the ability to override the calculator already. 
If you go to the Misc tab in the configurator, you have the field that is called 'Run Calculator'. When this is changed to No, you would then navigate to the Having a Baby and Managing Diabetes tabs and manually enter the final numbers you'd like to see on the SBC. By changing Run Calculator to No, this bypasses the auto-run of the calculator when generating the SBC and you will see the numbers you entered into the Having a Baby/Managing Diabetes tabs instead.

I just tested this in pshadow to ensure it was working and it worked fine. I changed Run Calculator to No, and then updated every field in Having a Baby/Managing Diabetes to '80' and all values were 80 on the SBC. Are you seeing differently? If so, then this is most likely a defect and not an enhancement.

Re: your last question - no, there is no way to manually edit these values through the Edit Plan offline tool, as there are no fields in the plan design currently to capture this information and the values come from the calculator directly. There is currently no way to not call the calculator using the offline tool.

**Comment by g4gaurang** [comment]
If you have set it up to actually work we were never made aware of this feature.  We were in fact told  at one point it will not be possible to override the calculator manually. This is a requirement we have requested and discussed last year as well as early this year and that is why you may have built this function. I know you changed it from a radio button to a drop-down during implementation around June,2015. It did not work when we initially tested it as a radio-button. If you say it works we will test On Pclient5 and let you know accordingly.

**Comment by michparrish** [comment]
Just a reminder that we are performing the code deployment and refresh right now in pclient5. That has been concluded but we need to now reset IDs and passwords. Please hold off on any testing in pclient5.

**Comment by g4gaurang** [comment]
Yes, we are aware of it but thanks for the reminder. We will start once you send us the new IDs and passwords.

**Comment by g4gaurang** [comment]
This feature is working both on pclient5 and in production. A couple of findings
1. The plan design updates with the override amounts but if calculator is dynamically run it will not update. This is a known behavoir and HR cannot fix it.
2. There is no field level validation if user enters unrealistic amounts as overrides. so onus is on the user to enter correct amounts.

@jddecoste  we will need to include this as part of refresher training to educate the BEs of the availability and use of this feature.

**Comment by michparrish** [comment]
@g4gaurang please let me know why this was reopened. Is it not working properly?

**Comment by g4gaurang** [comment]
**Training Guide:** 
When user creates a complex SBC with dual cost share ( for e.g. $250 copayment or 30% coinsurance) within the HR product configurator and are unable to get the correct cost calculations through the system generated calculators, they will need to perform the following steps to manually override the calculator-
1. Manually calculate the coverage examples outside the system using the Maternity and Type II Diabetes excel apps using the two-step process.
2. Go to the configurator and on the Misc. fields tab, indicate "No" against the run calculator field. 
3. Go to the Having a Baby tab and plug in the Maternity calculator  output amounts for  Deductible, Copayment, Coinsurance and Limits or Exclusions output from Step 1. (no need to plug in plan and patient pays numbers - they will be automatically calculated)
4. Go to the Type II Diabetes tab and plug in the Type II Diabetes calculator output amounts for  Deductible, Copayment, Coinsurance and Limits or Exclusions output from Step 1 (no need to plug in plan and patient pays numbers - they will be automatically calculated)
5. Click Save and/or Click Plan Documents in the top pane and generate the appropriate SBC document.
6. Confirm that the numbers you manually plugged in will show up on both the coverage examples sections of the SBC.

**Note** 
1. This override activity will be needed ONLY when the dual cost share is for a service that impacts either of the calculators
2. Even if such a dual cost share impacts only one of the calculators, BOTH calculators will have to be manually overridden. This means both the calculators for that SBC will have to be done manually using the excel apps and the outputs transferred back to the plan configurator because the system does not currently have the ability to selectively override only one calculator.

@jddecoste  @kselvo01
