### ISSUE TITLE
Stock number populating where HighRoads job # should be

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#258]
Hello,

On the Manage Plan interface, when creating a custom plan out of standard plan 800280HR_Master_Medical_80-0129LG1-1-16, the stock number populated where HighRoads job # should be.  

This was found when performing a health check on defect #221.

**Comment by michparrish** [comment]
Hi Will,

Please note what steps were taken when you saw this error. I searched for that specific plan design, clicked Edit > Manage Plan > Create new plan from this plan > Custom and did not encounter the same issue in both Prod and our Shadow environment:

![stock number in header](https://cloud.githubusercontent.com/assets/13471811/10145399/e39e2854-65f0-11e5-9e69-d4ccb8eb9b32.JPG)

I performed this rather quickly, so I know it wasn't a system 'glitch' of sorts (clicking too quickly). I also tested searching on 2016/Indemnity/Standard plans, chose 800280 and followed the same Create New Plan > Custom and received the same result.

Please have user try again and recreate as I am not able to on my end.

**Comment by willdwyer** [comment]
Hi Michelle,

I'm not sure if my screenshot was attached before, but here it is.
![screen shot 2015-09-28 at 2 27 51 pm](https://cloud.githubusercontent.com/assets/13453008/10145740/f20ec48c-65f2-11e5-85df-dc5fbfb9c49c.png)

**Comment by willdwyer** [comment]
Note that I tested other indemnity plans and did not see this error, so I could not isolate one specific cause.

**Comment by michparrish** [comment]
it looks like you're using Firefox - please try with IE8/10 and let me know if you see the same issue.

You are going to see repeated issues if you continue to use a browser other than IE8/10 to use your Highroads tool.

**Comment by willdwyer** [comment]
Hi Michelle,

This was a random occurrence, and we have not seen it since.  This will be left open for now to see if it comes up again.

However, I doubt that this was caused by using Firefox instead of IE 8/10, as it seemed like a HighRoads system error instead of a browser error.

**Comment by michparrish** [comment]
Hi Will, That's fine to keep it open for now but it should not stay open indefinitely. 

Please close the defect #221 if the testing is complete. Thank you.

**Comment by TimHeasley** [comment]
Hi Will,
Just checking to see if this issue should remain open?
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I am following up with the BEs to see if they have encountered this at all.  If they haven't, then it can be closed.

**Comment by willdwyer** [comment]
Hi Tim,

I have followed up with the BEs, and no one has encountered this error since, so this defect will be closed.
