### ISSUE TITLE
Cost Calculator issues with % coinsurances values

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#259]
Hello,

We are encountering the screenshot calculator issue when attempting to generate an SBC with both copayment $ values and coinsurance $ values.  See screenshots below.

This was done by generating a custom plan from standard plan 800047HR_HMO_Blue_NE_Value_Plus_80-0108SG1-1-16.

Please research and fix globally.

<img width="1326" alt="screen shot 2015-09-28 at 4 46 04 pm" src="https://cloud.githubusercontent.com/assets/13453008/10148692/ec6db852-6602-11e5-9c0b-e80a3f7e6855.png">
<img width="549" alt="screen shot 2015-09-28 at 4 56 56 pm" src="https://cloud.githubusercontent.com/assets/13453008/10148708/078d3a04-6603-11e5-95d0-86becb07be69.png">
![screen shot 2015-09-28 at 4 46 17 pm](https://cloud.githubusercontent.com/assets/13453008/10148709/07900b1c-6603-11e5-8458-e7ac66d48caf.png)

**Comment by michparrish** [comment]
@willdwyer can you please let me know which of the Eligible Options in the dropdown were used for this? I don't see one that matches, so it looks like a manual entry that we did not account for in the calculator. The only one that comes close is "$15/50% coinsurance/50% coinsurance retail; $30/50% coinsurance /50% coinsurance mail" and that would show as only '50% coinsurance' in the preferred drugs, not what you see above in either the configurator or the SBC.

**Comment by TimHeasley** [comment]
Will, 
I uploaded the new calculator to PClient5 and created a custom plan from standard plan 800047. I did not have any issues, see screenshot.  Please retest in PClient5 and after your approval we can move the calculator to Production.  Thank you

https://drive.google.com/file/d/0B346D2AloIVGTjVKRFNFcVVERG8/view?usp=sharing

**Comment by willdwyer** [comment]
Hi Michelle,

The prescription drug cost information is customized in this, so this is not one of the eligible options.  The user would select the no cascade option for this.

Also Tim, per your message, I will retest in PCLIENT5

**Comment by willdwyer** [comment]
Hi Tim,

This looks fixed in PCLIENT5.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Moved to Production and ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This looks good.  This request is being closed now.
