### ISSUE TITLE
Enhancement request: Need ability to upload and assign attributes to multiple doc types at same time - BPMS-I-18

### ISSUE THREAD

**Issue by michparrish** [willdwyer/bcbsmaissuestracker#260]
Hello,

It was noticed earlier that if a user tries to assign attributes with documents of 2 different types, they are unable to. We will need a user to be able to assign attributes for 2 document types at once, as with plans there will be both a word document and PDF associated with them. Without this override, it will take double the time to upload and assign attributes.

screen shot 2015-09-28 at 1 50 50 pm

Please provide an LOE and timing for this as well as the enhancement request referenced above.

**Comment by michparrish** [comment]
@willdwyer  after review and some testing, I can assign attributes to a Word doc and a PDF together at the same time successfully, using both the Edit Attributes and Output Attributes functions. Please let me know how you were trying to perform this as well as what types of documents you were trying to update.

**Comment by michparrish** [comment]
@willdwyer 
after more review, I see you are trying to assign attributes at the time of manual upload, to 2 different doc types. The system is not allowing you to upload 2 different doc types, therefore the process is stunted right away and you're receiving the system errors. 
I believe this request needs to be changed to requesting the ability to upload and assign attributes to documents with different doc types at the same time. 
Please confirm.

**Comment by willdwyer** [comment]
Hi Michelle,

That is correct.  We are requesting to have the ability to upload 2 different doc types manually and assign attributes to them at the same time.  Note that in instances like these, they would have the exact same attributes.

**Comment by michparrish** [comment]
Changed the name of the request and created a new enhancement request (thus, new number) internally that better articulates the request.
This item will be picked up in the next sprint, which starts on 10/7. We should receive LOE after the sprint closes, on 10/21. So would expect info around 10/22.
Thank you.

**Comment by willdwyer** [comment]
Thanks, Michelle.

The sooner the better on this, as without this enhancement, it is taking users twice as long to upload and assign attributes to documents.

**Comment by michparrish** [comment]
Understood - unfortunately, I have no way to pick up time on this. I'll only hear when the sprint is finished. I'll report back as soon as I hear so you all can give the OK to move forward after hearing the LOE, if it's considered.

**Comment by willdwyer** [comment]
Hi Michelle,

Just to add some more information to this enhancement request, users have the ability to edit different document types if they are already in Content Library, so to assign attributes to different document types when they are in the process of being uploaded should be an easy fix.

This is demonstrated in the screenshot below.

![screen shot 2015-10-06 at 11 50 19 am](https://cloud.githubusercontent.com/assets/13453008/10314100/051e3a42-6c21-11e5-97bd-2120eb8c7dbf.png)

**Comment by michparrish** [comment]
Hi Will,
I understand what you're saying but I'm not to say if this fix is 'easy' or not and don't want to assume. Bulk assigning attributes to documents already housed in the system is clearly different code than uploading and assigning attributes for the first time and I don't know how difficult decoupling the doc type from this process will be for Dev.

**Comment by willdwyer** [comment]
Hi Michelle,

Do you have an update on the LOE and timing for this enhancement?  As indicated above, we would receive info by around 10/22.

**Comment by michparrish** [comment]
All:
Dev was able to update this item as part of the Recommended Attributes item, rather than a separate enhancement request. Therefore we did not have to return back to your team for LOE approval and this will not count towards your overall Enhancement hours allotment.
This item is with our QA team now and when they have tested successfully, we will schedule a deployment to pclient5 for our teams' testing. 

For this item - users will be able to upload multiple documents with varying doc types at once, and be able to assign 'like' attributes to all documents being uploaded. The attributes section of the popup will also include the 'Recommended Attributes' separation found when uploading single documents today.

HighRoads will report back when QA has finished with their testing and we are ready to deploy to our test environment.

**Comment by TimHeasley** [comment]
Working with QA to complete testing to secure a Production date by end of January.

**Comment by TimHeasley** [comment]
Enhancements being built to QA environment with completion of testing scheduled for the end of this week.

**Comment by markderg** [comment]
Our internal testing has found a defect preventing us from moving forward with BCBMA testing/validation.  We are currently investigating the issue with our QA and Development Teams.  Our expected production date is now TBD based on this defect.  Once we understand the root cause we will follow up with a definitive plan of action including a new testing and production date schedule.

**Comment by willdwyer** [comment]
Hi Marc,

Can you please provide more specific details on this defect?

**Comment by willdwyer** [comment]
Hi Mark,

Just following up - please provide more information on this defect noted above.

Also note: we are mapping out the new process to train onboarding employees on uploading documents and assigning attributes on March 11, so this enhancement, as well as #293 must be implemented by then.

**Comment by TimHeasley** [comment]
Issues #260 & #293 are critical needs for the BCBSMA team for their March 11 training.

**Comment by willdwyer** [comment]
Hello,

Just a reminder that this deadline is approaching.

**Comment by TimHeasley** [comment]
Hi Will,
We are finalizing our testing and are ready to move the enhancements to PClient5 for your testing.  

We wanted to let you know that this enhancement is mostly working.  You are able to upload documents although you need to push through an error message.  When you click submit a "please contact system administrator" error message appears. After clicking OK you can Click Submit again and no error message received, documents appear in correct folders. We are working with our development team to fix this so the message does not appear.

We want to move this item to PClient5 to test along with the other items that are working - #293 #335 #336 

Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
The code has been moved to PClient5, although when I did internal testing I am now not able to push through the error message.  I am working with QA support to push through and remove the error message.  As soon as I hear something I will update this issue.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I tested this in PCLIENT5 for 10+ different scenarios, and only encountered it once.  It occurred when I selected doc types (2) SBCS - (Word - Carve Out) - Final and (2) SBCS - (PDF and Word) - Draft, and only partially assigned some of the recommended attributes.

Other than that, it functioned as expected.  I still have more testing to do, but will let you know when it appears safe to move to production.

**Comment by willdwyer** [comment]
Hi Tim,

Please move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for testing.  
The code is tied in with the following issues and be moved to Production once we have approval. 

#256 - code is working, need to fix on configuration side, able to move to Prod
#260 - approval to move to Production, even though there is an issue when loading pdf & word documents together
#293 - approval to move to Production
#335 - fixed ready for retest
#336 - fixed ready for retest
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I am confused with the above to reference #256 ... I thought this wasn't tied in with the next production code update?

We are scheduled to train new hires on the new upload/attribute process tomorrow at 2PM, so we definitely need this moved to production before then (ideally before noon, so we can confirm there are no further issues).  This is why there was a deadline associated to it.

If it is indeed tied to #256 , then please work and fixing the remaining requirement on this ASAP, so we can move to production.

Please know that this is a hot issue.

**Comment by TimHeasley** [comment]
Go-NoGo to production meeting scheduled for 3/29.

**Comment by TimHeasley** [comment]
We are a Go for moving the code to Production this evening.  We will notify you tomorrow when you can test in Production.

**Comment by willdwyer** [comment]
OK thank you.  Will the production environment be down for a certain period of time?  If so, when?

**Comment by TimHeasley** [comment]
Code has been moved to Production and is ready for retest.

**Comment by willdwyer** [comment]
Looks good.  Closed
