### ISSUE TITLE
Cascading error with 4 tier pharmacy plans

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#261]
What steps will reproduce the problem?
1. Log on to Production as a BCBSMA Administrator
2. Click on Manage Plan
 Enter search criteria:
 Effective Date - 2016
 Product Group Type - Access Blue NE
 Plan Type - Standard
 Click - Show Me Plans"
3. Hover cursor over desired plan (800286HR_Access_Blue_NE_Enhanced_Value_80-0149HCCSLGASC1-1-16 ) 
to select The drop down box with 3 choices will appear
 Select Create a new plan from this plan"
4. Click on Custom Plan Button
5. Click on Common Medical Events tab
6. Go to Generic Drugs field
7. Expand Eligible Options, highlight and copy value "$25/$50/$75/$150 retail; $50/$100/$150/$450 mail
8. Paste into in-network field
9. On Cascade Options field, make sure Cascade All is selected
10. Proceed to save/validate
11. Click Plan Documents, generate Final PDF with disclosures
12. On PDF, go to page 3 of 8

See screenshot.  Note that the cascading is 'skipping over' the Preferred brand drugs field.

![screen shot 2015-09-30 at 5 27 26 pm](https://cloud.githubusercontent.com/assets/13453008/10207256/3400a4e4-6799-11e5-9fab-d7dfff77604c.png)

**Comment by TimHeasley** [comment]
Will,
We are looking into the issue.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
We have updated the workbook for this item.  The cell reference in Preferred Brand Drugs was pointing to a wrong cell for when the Rx values were parsed. Tested and confirmed working in PClient5.  Ready for retest in PClient5. 
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

So I just went to retest this defect... I entered the same value from eligible options as mentioned before ($25/$50/$75/$150 retail; $50/$100/$150/$450 mail), and noticed that, when cascading, the same value generates in Preferred brand drugs as Non-preferred (left of screenshot).  However, when I went back to Edit the plan, I entered the same value from Eligible options ($25/$50/$75/$150 retail; $50/$100/$150/$450 mail), saved/validated/generated, and it appears to be fine (right of screenshot)

![screen shot 2015-10-02 at 11 09 22 am](https://cloud.githubusercontent.com/assets/13453008/10249946/1e102a84-68f6-11e5-8a25-40e8e2dfa20c.png)
.  I showed this to Michelle as well.  Please research.

**Comment by michparrish** [comment]
Hi Will, Alex reloaded the workbooks and retested and things look fine. Mind retesting and let me know if you see it again? If not, let me know if we can move to Prod. Thanks!

**Comment by willdwyer** [comment]
Hi Michelle,

I retested in PCLIENT5, and it looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Workbook has been moved to Production and is ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I retested, and it looks good.  This defect is now being closed.
