### ISSUE TITLE
Values not cascading in prescription drug fields for Blue Choice plans

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#262]
Hello,

When entering particular values from eligible options in Blue Choice Local plans, and selecting 'Cascade All', the cascading will not occur.

See screenshot below, as the value from eligible options did not cascade after saving with Cascade All selected

![screen shot 2015-10-01 at 12 07 45 pm](https://cloud.githubusercontent.com/assets/13453008/10226729/38b5e33e-6837-11e5-852e-4b3464017d62.png)

**Comment by TimHeasley** [comment]
Will,
Cascading values have been fixed for all POS plans. The issue was "and" in the value.  It has been updated, tested and confirmed working in PClient5 for different cascading values.  Ready for retest.  After you have the chance to test and approve we can move to Production.
Thanks,
Tim

**Comment by willdwyer** [comment]
Good catch, Tim.  Thanks.  And, it looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Workbook has been moved to Production and is ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I retested, and this looks good.  This defect is now being closed.
