### ISSUE TITLE
Other Practitioner Office Visit cost share  per occurence verbiage cascading incorrectly

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#265]
A Benefit Expert has reported the following issue - 
When attempt to generating a SBC for a Master Medical Indemity plan, the Other Practitioner Office Visit field should read:  20% coinsurance / chiropractor visit.    This is the standard so initially I didn’t make any changes to the field before generating the plan.   See below screenshot of what was in the configurator.

![image](https://cloud.githubusercontent.com/assets/10272072/10349308/dbeb2284-6d0b-11e5-86c2-1dc1e7cd1567.png)

Once I generated the plan, that field (along with the other cascade fields) only said 20% coinsurance.   See below: 
![image](https://cloud.githubusercontent.com/assets/10272072/10349316/e83ea146-6d0b-11e5-8a19-a49787fed166.png)

I think part of the issue is that in the Primary Care Visit field (the one that we use to cascade, it appears that what is coded is “20% coinsurance” instead of “20% coinsurance per visit.”   Thus when we generate the plan we only get "20% coinsurance” instead of “20% coinsurance / visit.”   

![image](https://cloud.githubusercontent.com/assets/10272072/10349329/f863fcc4-6d0b-11e5-8703-c5dde2957967.png)

This is an issue with all indemnity plans..

In addition, when I tested a PPO plan to check the casacading for the 20% coinsurance this is what I notice - the per occurence verbiage is missing on in-network but present on the out-of-network.
3453473_Lisa Test 18_Preferred_Blue_80_Copay_444TESTS
![image](https://cloud.githubusercontent.com/assets/10272072/10349267/9a68a638-6d0b-11e5-9767-a4a94b645056.png)

Please fix globally and test all plan types for this issue.

**Comment by michparrish** [comment]
HR is reviewing the item.

**Comment by michparrish** [comment]
Hi all,

HR has determined that the request is not a defect, but is an enhancement request.
Please see the attached LOV value requirement document below. We did not receive instruction to add 'per visit' to the end of coinsurance LOV values, only the copay values. To update all workbooks and test in both CPE2 and then pclient5 will be an LOE of 5 hrs.
Just a note that if this change is made, the new value will cascade to all of the following fields:
Specialist Visit
chiropractor (other practitioner office visit)
Mental/Behavioral Outpatient
Substance Use Disorder Outpatient
Rehabilitation Services
Habilitation Services
Urgent Care

Additionally, we also do not have the requirement to change any cascaded values from Primary Care to Other Practitioner's Office Visit from '/ visit' to '/ chiropractor visit'. This is not expected behavior in the OON field right now, and therefore is technically a defect. However, since is functioning as we would want it to work, it would be an enhancement request to make this update to all workbooks for all INN and OON fields and test to ensure it's working properly. To make this update to the workbooks and test in both environments will be an additional LOE of 5 hrs. 

Please let us know if you would like us to make these changes.

[Final Sprint 2 CascadingRules_Plan Management _3 18 15 with 4 28 demo 1 1 items  5 11 QA.xlsx](https://github.com/g4gaurang/bcbsmaissuestracker/files/14191/Final.Sprint.2.CascadingRules_Plan.Management._3.18.15.with.4.28.demo.1.1.items.5.11.QA.xlsx)

**Comment by g4gaurang** [comment]
## See #162 

In addition, this was part of the original mapping document which formed the basis of a BCBSMA SBC sent to HR back in December 2013. Check with Steve. K

![image](https://cloud.githubusercontent.com/assets/10272072/10523488/a80ad098-7348-11e5-8431-187ef1e8f3ee.png)

---

In addition, this currently works perfectly fine on a PPO plan in production. Try changing from the default  $20 per visit in-network / 20% coinsurance out-of-network  to  $15 per visit in-network / 20% coinsurance out-of-network and you will notice that the /chiropractor for other practitioner office visit on the out-of-network column will be applied correctly.

![image](https://cloud.githubusercontent.com/assets/10272072/10523927/f38c7448-734a-11e5-9624-e1d09e57890a.png)

**Comment by michparrish** [comment]
thank you - the enhancement would then only be for adding the 'per visit' verbiage to the coinsurance LOV values. We'll ensure that when the copay AND/OR coinsurance values are cascaded to OPOV, the 'per visit' is changed to '/ chiropractor visit'. 
LOE 5 hrs for updates to all workbooks and testing.

**Comment by g4gaurang** [comment]
> thank you - the enhancement would then only be for adding the 'per visit' verbiage to the coinsurance LOV values. We'll ensure that when the copay AND/OR coinsurance values are cascaded to OPOV, the 'per visit' is changed to '/ chiropractor visit'. 
> LOE 5 hrs for updates to all workbooks and testing.

Sorry, you are not making any sense. You should have already accounted for this as part of release. I have pointed out at least 3 factors it should already be working.  This is technically a defect. Fix it.

**Comment by michparrish** [comment]
This is what was meant by 'we'll ensure that when the copay AND/OR coinsurance values are cascaded to OPOV, the 'per visit' is changed to '/chiropractor visit'.

**Comment by g4gaurang** [comment]
> This is what was meant by 'we'll ensure that when the copay AND/OR coinsurance values are cascaded to OPOV, the 'per visit' is changed to '/chiropractor visit'.

Per occurrence logic and verbiage for copay AND/OR coinsurance values for OPOV is already working fine on many to most of the plans. For example : a Preferred_Blue_Ded_2000_80-0119LG1-1-16 or a HMO_Blue_Basic_Copay_ etc etc. There are a few plans for example indemnity plans like Master Medical where it does not work as expected. In that context this is a defect. This is what we want you to fix . Why would you want to charge us 5 hours as enhancement for fixing a defect ?

**Comment by michparrish** [comment]
There are 2 different items in your request - 
1) the defect where the '/ chiropractor visit' is not working in all cases. We will fix this defect.
2) the need for when a coinsurance is selected in Primary Care Office Visit, for it to cascade to OPOV and state '/ chiropractor visit' after it. Is this correct? In order for this to happen, we need to first add 'per visit' to the coinsurance LOV value in Primary Care Visit, as it is currently not there and is only there for the copay values, as received in the requirements documents we've received for the LOV values.
Do you want this updated? If yes, it will take 5 hours of LOE to make the adjustment to all workbooks that have a coinsurance value in Primary Care, and then testing to ensure it works properly and without issue when cascaded.

**Comment by g4gaurang** [comment]
> There are 2 different items in your request -

There is only ONE issue. That issue is every time their is either a No charge or a copay or a coinsurance cost share in ANY of the tiers in the other practitioner office visit service on the SBC, it should always be qualified with "/ chiropractor visit" when you cascade the value - This behavior already exists in the system and WORKS WELL on MANY OF THE PLANS. we tested including HMOs, PPO, POS, Access Blues etc. but it does not work fine with Indemnity plans as indicated on the first comment on this defect. We would like you to fix this.

**Comment by TimHeasley** [comment]
Guarang,
I have tested all of the workbooks in PClient5 and "chiropractor visit" appears correctly.
Please retest at your convenience.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Looks good on Pclient5. Please move to production.

**Comment by TimHeasley** [comment]
Guarang,
Fix has been moved to Production and is ready for retest.
Once confirmed that it is working, please close issue.
Thanks,
Tim

**Comment by g4gaurang** [comment]
I tested a limited set of plans in production and issue looks fixed.
