### ISSUE TITLE
Incorrect Maternity Calculation 

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#267]
Job number: 3455207.
FMPRO#: 154631BS

See screenshot. Deductible and Copayment outputs should be $20 and $750 respectively. Please fix globally

![maternitycalcerror](https://cloud.githubusercontent.com/assets/10272072/10456672/9672c106-7190-11e5-8958-4e19d1148ad8.PNG)

**Comment by michparrish** [comment]
![3455207](https://cloud.githubusercontent.com/assets/13471811/10456907/a6fdf9c2-7191-11e5-8ae7-f58de013bf81.JPG)
It looks like the deductible in this plan is $0 - please confirm this should be $20, make the change and retest.

**Comment by g4gaurang** [comment]
> It looks like the deductible in this plan is $0 - please confirm this should be $20, make the change and retest.

Good Morning! The OVERALL deductible is $0. BUT the PHARMACY deductible is $100.

**Comment by TimHeasley** [comment]
Gaurang,
The calculator has been fixed and moved to Production. 

It appears that the Rx deductible syntax was different, so it wasn’t recognizing that there was a deductible value.  Another condition was added to look for in the string to fix this issue.

Ready for retest.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Looks fixed. If user replaces retail with mail, system will still factor the deductible in the maternity calculator even though the maternity only uses retail cost share. This is not a problem right now but we will cross that bridge when we get there.
