### ISSUE TITLE
No Charge LOV should be No charge

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#268]
Hello,

This was reported by BE Denise DeSylvia.  When selecting the "No charge" eligible option and selecting cascading, "Charge" was capitalized in certain fields.  It should read "No charge" and not "No Charge".  See screenshots.

![screen shot 2015-10-13 at 2 53 58 pm](https://cloud.githubusercontent.com/assets/13453008/10465864/28969570-71bf-11e5-8492-886d2f71388f.png)
![screen shot 2015-10-13 at 2 53 45 pm](https://cloud.githubusercontent.com/assets/13453008/10465865/2897553c-71bf-11e5-832d-e2d09976d723.png)
![screen shot 2015-10-13 at 2 54 52 pm](https://cloud.githubusercontent.com/assets/13453008/10465866/289b6fd2-71bf-11e5-8c87-4b320ea7325d.png)

**Comment by TimHeasley** [comment]
Will,
I have looked into this item and it looks like we received “No Charge” for the DropdownListofValues file. I also reviewed the rest of the tabs and this is the only case (HMO – Primary care visit to treat…) where it happens.

We will update and let you know when it is ready for retest.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
This item has been updated an ready for retest in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This is still a defect (see screenshots).

![screen shot 2015-10-14 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/13453008/10494173/d034e3c2-7282-11e5-9af0-fd99f3126838.png)
![screen shot 2015-10-14 at 2 47 19 pm](https://cloud.githubusercontent.com/assets/13453008/10494171/d033bcb8-7282-11e5-85a1-1b0287ec6009.png)
![screen shot 2015-10-14 at 2 47 12 pm](https://cloud.githubusercontent.com/assets/13453008/10494172/d033e0a8-7282-11e5-851e-439eb9b3cfcf.png)

I noticed that the LOV for Primary Care visit is "No Charge".  It should be "No charge" across the board and globally.  Please make the adjustment(s) and let me know once complete.

**Comment by willdwyer** [comment]
Hi Tim,

This is still a defect.  See screenshots.

![screen shot 2015-10-14 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/13453008/10495075/ead72b2c-7287-11e5-9f62-45f42416245b.png)
![screen shot 2015-10-14 at 2 47 19 pm](https://cloud.githubusercontent.com/assets/13453008/10495076/ead7b0a6-7287-11e5-9c99-7fd960019745.png)
![screen shot 2015-10-14 at 2 47 12 pm](https://cloud.githubusercontent.com/assets/13453008/10495074/ead69e50-7287-11e5-98b9-3ed8087b959a.png)

As mentioned, the LOV across the board should be "No charge" (c should not be capitalized).  Please fix globally.

**Comment by TimHeasley** [comment]
Hi Will, 
The cascading field has been updated to "No charge" and it cascades correctly.  
Ready for retest in PClient5.
Thank you,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This looks fixed.  Please move to production.

**Comment by michparrish** [comment]
pending successful testing of #265, then we can move the workbooks to Prod for both items.

**Comment by TimHeasley** [comment]
Fix has been moved to Production and is ready for retest.  
Once confirmed that it is working, please close issue.

Thanks

**Comment by willdwyer** [comment]
Hi Tim,

This looks fixed.  Defect is now being closed.
