### ISSUE TITLE
Cascade Options not displaying in Primary Care visit and Imaging

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#269]
Hello,

hat steps will reproduce the problem?
1. Log on to PCLIENT5 as a BCBSMA Administrator
2. Click on Manage Plan
Enter search criteria:
Effective Date - 2016
Product Group Type - HMO Blue NE
Plan Type - Standard
Click - Show Me Plans"
3. Hover cursor over desired plan (800089HR_HMO_Blue_NE_Ded_1000_Copay_80-0272HCCSMM1-1-16 )
to select The drop down box with 3 choices will appear
Select Create a new plan from this plan"
4. Click on Custom Plan Button
5. Click on Common Medical Events tab
6. Go to Primary Care visit and Imaging fields
7. Expand Cascade Options
8. Paste into in-network field
9. Note that all options except "Cascade All" are missing

See screenshots below, and fix globally

![screen shot 2015-10-14 at 3 32 34 pm](https://cloud.githubusercontent.com/assets/13453008/10496308/1b7afdb6-728e-11e5-890e-91f3ff890176.png)
![screen shot 2015-10-14 at 3 59 14 pm](https://cloud.githubusercontent.com/assets/13453008/10496309/1b7ce54a-728e-11e5-846d-6b4c6227ad26.png)

**Comment by TimHeasley** [comment]
Will,
Testing has been completed in PClient5 and the Cascade Options appear correctly.
Ready for retest. Let me know if you have any questions.
Thank you,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This is still a defect.  The cascade options have disappeared in the Imaging field (see screenshot).

![screen shot 2015-10-15 at 6 09 35 pm](https://cloud.githubusercontent.com/assets/13453008/10528982/05bc0210-7368-11e5-81a6-67b1d410d4a0.png)

**Comment by willdwyer** [comment]
Note the plan that was used in the above screenshot: 800250HR_HMO_Blue_NE_Enhanced_Value_80-0110LG1-1-16

**Comment by TimHeasley** [comment]
Will,
Thank you for testing.  We will make the updates and let you know when you can test.
Tim

**Comment by TimHeasley** [comment]
Will,
We have researched the issue and we have notes from our 5/11/15 call that state there is not a need for an option to selectively cascade for Imaging.
Would you like us to add it back in?
Thanks,
Tim

**Comment by willdwyer** [comment]
Tim,

We need to make to sure this is consistent across every single plan.  We will see plans that have the cascade option, as well as other plans as well.  

See below examples... one currently has cascading on imaging while other does not.  The plans are: 800089HR_HMO_Blue_NE_Ded_1000_Copay_80-0272HCCSMM1-1-16 
800250HR_HMO_Blue_NE_Enhanced_Value_80-0110LG1-1-16 

![screen shot 2015-10-20 at 2 38 57 pm](https://cloud.githubusercontent.com/assets/13453008/10617828/7f33d188-773a-11e5-8f27-45db14dba8e2.png)
![screen shot 2015-10-20 at 2 54 16 pm](https://cloud.githubusercontent.com/assets/13453008/10617831/813be056-773a-11e5-8d96-ff190878cde3.png)

**Comment by TimHeasley** [comment]
Will
We will update all workbooks so that the Imaging Cascade Options appear.
I will let you know when it is ready for retest in PCient5.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
Cascade option appears for Imaging, ready for retest.
After you confirm & approve we can move to Production.
Thank you,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Still a defect (per screenshot).  Please make sure the cascade option appears for Imaging for all plans.

This was found from generating a custom out of standard plan 800164HR_Network_Blue_NE_Premier_Value_80-0111MMASCBF1-1-16 

![screen shot 2015-10-22 at 5 18 32 pm](https://cloud.githubusercontent.com/assets/13453008/10678531/0b56837a-78e1-11e5-8e5d-fbbb24928ab8.png)

**Comment by TimHeasley** [comment]
Will,
We have not moved the workbooks to Production.  If you could test in PCient5 and confirm the fix, we can then move them to Production.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I reviewed this plan, as well as several others in PCLIENT5, and the cascading option does, in fact, appear in Imaging.  I confirm the fix.  Please move to Production.

**Comment by TimHeasley** [comment]
Will,
The workbook has been moved to Production.  After you confirm the fix, please close the issue.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This looks fixed.  I will now close this defect.
