### ISSUE TITLE
Enhancement request - Attribute list should match from SBCs to summaries

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#270]
Hello all,

We are requesting the attribute list to be updated in HighRoads so that the attributes list to choose from matches for both SBCs and Summaries.  The following attributes are the ones that are required:
Plan Year
Product Group Type
Market Segment
Financial Arrangement
Product Type
Effective Date (MM_DD)
Effective Date (YYYY)
Language
Preferred Account Name

Please provide LOE and timing for this.

**Comment by michparrish** [comment]
Hi Will,
I'm not sure I understand the request. The attributes are the same throughout the system. They do not change options by doc type.

**Comment by michparrish** [comment]
Hi Will,
I'm not sure I understand the request. The attributes are the same throughout the system. They do not change options by doc type.

**Comment by michparrish** [comment]
as discussed in Monday's meeting, 10/19, I will take this back and research why we are seeing different attributes for different doc types and standardize them for SBCs and Summaries.

**Comment by michparrish** [comment]
Will, I'm seeing the same attribute values for Summaries as we do for SBCs. In fact, I checked with folks here to confirm that we cannot set up separate sets of attributes per doc type and this was confirmed. 
Please see the attached doc - here are examples of me checking a Summary of Benefits, clicking the Tools > Edit Attributes function and the options available for Plan Year and Product Group Type. Please send screen shots of what you're seeing if you're seeing different options, along with where you are going to see these options.
[attributes.docx](https://github.com/g4gaurang/bcbsmaissuestracker/files/17767/attributes.docx)

**Comment by willdwyer** [comment]
Hi Michelle,

I actually verified that all attribute values are the same for Summaries and SBCs, so this open item will be closed.
