### ISSUE TITLE
Larger than usual DRAFT stamp on SBC

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#272]
Benefits Experts have reported an issue with DRAFT  stamps on documents generated through the system. The draft stamp sizes are not consistent and when a document had a large draft stamp, it prevents the user from marking up and reading edits. See example below - 
FMPRO number 154841BS

![image](https://cloud.githubusercontent.com/assets/10272072/10612696/eb8b9c0a-771f-11e5-847d-e0e153d80665.png)

**Comment by TimHeasley** [comment]
Hi Guarang,
I did some testing in PClient5 and the size of the draft stamp is consistent, nothing has been updated in the templates.  Word documents have the same size stamp throughout all plans using the same template.  PDF plans are also the same throughout.  

Can you verify that the BE was using IE8 or IE10?  

UPDATE:
We can work on changing the size of the stamp on the templates although this could have some downstream impacts, like duplicating across pages.

Supported browser downstream impacts - errors in views of pages/dropdowns, page errors, potentially changes in the results of the documents created.

Thanks,
Tim

**Comment by g4gaurang** [comment]
Here is the attached example from production. Browsers should not matter. BE used IE10. This seems to be document level issue.

[154841BS_qc-JB_10-20-15.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/17046/154841BS_qc-JB_10-20-15.pdf)

**Comment by TimHeasley** [comment]
Guarang,
Was this a Word document then saved as a pdf?
Thanks,
Tim

**Comment by g4gaurang** [comment]
It seems to be the case. I confirmed with the BEs and they mentioned they did so because they were having problems generating the the calculators on them.

**Comment by TimHeasley** [comment]
Guarang, 
Thank you for confirming with the BE's.  
If you test multiple word documents you'll notice that "DRAFT" is the same size on all word documents.  For all pdf documents "DRAFT" is smaller, but consistent.

Let me know if you have any questions.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Draft stamps on Word documents are of different size than those on PDF documents. Based on Tim's comment above, given the risk it may not be worth the effort to make the size on both word and PDF documents consistent. We will train the BEs to be mindful of this if they convert from word to PDF.
