### ISSUE TITLE
Diabetes calculator not working properly

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#273]
Hello,

This was reported by BE Julie Beers.  See attached PDF, and screenshot of diabetes calculator of what the numbers should be.  The specific cause has not been found, but the numbers are not matching correctly.

Please advise.

[3456190_Bake n' Joy Foods, Inc._HMO_Blue_NE_Options_Ded_II_v.5_154841BS.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/16955/3456190_Bake.n.Joy.Foods.Inc._HMO_Blue_NE_Options_Ded_II_v.5_154841BS.pdf)

![screen shot 2015-10-20 at 12 14 02 pm](https://cloud.githubusercontent.com/assets/13453008/10613703/474dd0a4-7724-11e5-8ff4-c3827aba3805.png)

**Comment by TimHeasley** [comment]
The calculator issue is being reviewed.

**Comment by TimHeasley** [comment]
Will,
There is no pharmacy deductible being pulled in in their calculator. According to the Other Deductibles, it should be $100. Another thing is that the Lab tests are getting pulled in at $40, but from what I’m seeing in the PDF, those are “No charge”. Can you retest?
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

We are still seeing this as a defect.  See attached PDF, as well as screenshot for what deductible should be.  This is a customized plan that was edited and generated out of standard plan 800011HR_Blue_Care_Elect_Ded_3000_80-0132SG1-1-16 

![screen shot 2015-10-22 at 2 09 37 pm](https://cloud.githubusercontent.com/assets/13453008/10674052/ef4762e0-78c6-11e5-8c9f-e7c9e18c0330.png)

[sbc_preview(480).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/18771/sbc_preview.480.pdf)

**Comment by TimHeasley** [comment]
Will,
The calculator has been updated.
It is ready for retest in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This is still a defect.  See attached PDF, as well as screenshot below with correct calculations.  In this example, it appears that the diabetes calculator is inputting the deductible amount of $500, which pertains to services at a general hospital, as opposed to the [correct] deductible amount of $300, which pertains to prescription drugs.  Please research and advise.

![screen shot 2015-10-27 at 5 53 46 pm](https://cloud.githubusercontent.com/assets/13453008/10773870/5471c14a-7cd4-11e5-9424-b95e31eac611.png)

[sbc_preview(501).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/22037/sbc_preview.501.pdf)

**Comment by TimHeasley** [comment]
Will,
The diabetes calculator has been updated and tested in PClient5.  
Please retest at your convenience and after you confirm we can move to Production.
Thanks,
Tim

**Comment by willdwyer** [comment]
Not fixed.

![screen shot 2015-11-04 at 4 31 53 pm](https://cloud.githubusercontent.com/assets/13453008/10952600/9885de3c-8311-11e5-8886-c58238b15a0d.png)

[sbc_preview(528).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/27521/sbc_preview.528.pdf)

**Comment by TimHeasley** [comment]
Will,
We updated the calculator and the fix applied. The formula we used to validate the parsed “other deductible” cells wasn’t working.
Ready for retest in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Still not matching.  The deductible is now inputting $300 as opposed to $500, yes, but the copayment(s) amount are off.  See attached PDF and screenshot of what calculator should be.

![screen shot 2015-11-04 at 6 47 13 pm](https://cloud.githubusercontent.com/assets/13453008/10955954/733b9de2-8325-11e5-8465-bbcb4c4c6035.png)
[sbc_preview(530).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/27620/sbc_preview.530.pdf)

**Comment by TimHeasley** [comment]
Hi Will,
Thank you for testing. We updated the calculator file.  It seems it wasn’t reading the Lab test value as an integer even though it was one and it was completely ignoring it.

Ready for retest in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Thanks, Tim.

Unfortunately, we are still seeing issues upon further testing.  We tested a Preferred Blue PPO Saver plan in PCLIENT5, and the numbers in both the Diabetes calculator and Maternity calculator are pulling the member values in the Other Deductibles field, and not the family values in the Other Deductibles field.

Please see below.

![screen shot 2015-11-05 at 11 27 20 am](https://cloud.githubusercontent.com/assets/13453008/10974506/7cc85568-83b0-11e5-8815-36676ee80e5f.png)
![screen shot 2015-11-05 at 11 27 07 am](https://cloud.githubusercontent.com/assets/13453008/10974507/7cccf33e-83b0-11e5-8783-d5a0b5acd169.png)
[sbc_preview(530).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/28206/sbc_preview.530.pdf)

**Comment by TimHeasley** [comment]
Hi Will,
We have had a number of people working on this issue and we do have a question:

Why is this plan required to use the family value over the member value and can you point it out on the requirements if we should actually use family?  There are requirements to pull the Family values for a ‘Saver’ plan, but this plan is not.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I apologize, as I attached the wrong PDF in the last comment.  Please see attached, and compare calculator numbers to what was provided in the screenshots below

![screen shot 2015-11-06 at 4 42 09 pm](https://cloud.githubusercontent.com/assets/13453008/11009502/67f0d840-84a5-11e5-929e-6d7c0a4a1a57.png)
![screen shot 2015-11-06 at 4 41 04 pm](https://cloud.githubusercontent.com/assets/13453008/11009501/67ef11c2-84a5-11e5-951b-e8fa2d724d80.png)

[sbc_preview(533).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/29241/sbc_preview.533.pdf)
.

**Comment by TimHeasley** [comment]
Will, 
We have reviewed the items you added in your recent comment and have some observations.

Below are the differences that are getting pulled into the existing calculator that are different from what you entered:
•The calculator is pulling in the “member” value for the Pharmacy deductible, but you entered the “family” value (Diabetes and Maternity)
•The calculator is pulling in the “member” value for the Inpatient deductible,  but you entered the “family” value (Maternity)
•The calculator is pulling in the “non-low cost generic drug value” for Generic – Retail in maternity, but it looks like the entered the “low-cost generic drug value drug” value (Maternity)

Please advise.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This is a Saver plan, so the family amounts should be pulled for the deductibles (overall, other).  For the out-of-pocket limit, Saver plans pull the member amount, not the family amount.

For diabetes and maternity, in 4 tier pharmacy plans (where there are 2 sets of values in the Generic drugs section), the calculator should input the 2nd tier ("for other generic drugs"), not "low-cost generic drugs.

You are correct, in that for the maternity, the input amount should be $40, and not $20.  However, see below as this does not make a difference in the outputs.

![screen shot 2015-11-09 at 5 38 03 pm](https://cloud.githubusercontent.com/assets/13453008/11048965/e5e679d4-8708-11e5-8cdb-739ce3370258.png)

**Comment by TimHeasley** [comment]
Hi Will,
The updated calculator file has been posted to PClient5.  With this update, the Saver plans now correctly pull the family values for both Pharmacy and Inpatient deductibles in both Diabetes and Maternity calculators.

Please retest at your convenience.
Thanks,
Tim

**Comment by willdwyer** [comment]
Looks good, Tim.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for testing. We are finishing updating Issue #277 and will have it ready for you test in PClient5. After you confirm it is working we will move the calculator to Production for both items.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will, 
The updated calculator has been moved to Production.  It is ready for retest.  After you confirm/approve it is working correctly please close the issue.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

We are still seeing issues.  See attached PDF, as well as screenshot of correct diabetes calculations.  Note that this was in production.

![screen shot 2015-11-17 at 10 45 13 am](https://cloud.githubusercontent.com/assets/13453008/11216358/c1699436-8d18-11e5-852e-4be20b1dd7d5.png)

[sbc_preview(550).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/36859/sbc_preview.550.pdf)

**Comment by TimHeasley** [comment]
Will,
The updated calculator has been loaded to PClient5 and is ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
Tim,

Just to confirm, the fix was made in PCLIENT5, not production, right?  The error was discovered in Production.

**Comment by TimHeasley** [comment]
Will,
Correct, the fix to the calculator was uploaded to PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
The updated calculator has been moved to Production.  It is ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
Looks good, Tim.  This defect is now being closed.
