### ISSUE TITLE
Tiers names for Home Health Care inverted on the User Interface for Option plans

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#274]
We've noticed  that the  Basic Benefits Tier and Out-of-Network tiers/column names for Home Health Care inverted on the User Interface for Option plans.
This impacts ALL options plans. Please fix this as soon as possible. We are receiving complaints from our sales teams about incorrect benefits as a result of this defect.  In some cases the values also end up being inverted.

How Home Health Care looks -
800024_HMO_Blue_NE_Options_Ded_II_v.5_80-0221LG1-1-16

![image](https://cloud.githubusercontent.com/assets/10272072/10666292/a91ab97a-789e-11e5-9e96-d9cd106e435a.png)

![image](https://cloud.githubusercontent.com/assets/10272072/10665743/5aef0a1a-789b-11e5-98a8-4e585d2dc810.png)

**Comment by TimHeasley** [comment]
Guarang,
We have fixed the issue and Home Health Care rows appear correctly.  Ready for retest in PClient5.
After you confirm the fix we can move to Production.
Thanks,
Tim

**Comment by g4gaurang** [comment]
I tried testing an options plan on Pclient5 to validate the fix and while the labels appeared in order for Home Health Care services, when I tried a simple cascading scenario by copy/pasting the first value from the dropdown and clicking save,  the system seems to produce junk values for out-of-network column across many cascaded to services 

3463157__Preferred_Blue_Options_Deductible II_v.5_444333BS

![image](https://cloud.githubusercontent.com/assets/10272072/10670720/d9071f0a-78b4-11e5-80c6-ea9da6d89202.png)

**Comment by TimHeasley** [comment]
Guarang,
When you copied and pasted to you have the entire value - "$ 15/25/45 PCP-Level Copayment / $45 Specialist-Level Copayment in-network / 20% coinsurance out-of-network"

When I copied the entire value it appeared correctly.
Can you retest and let us know if it is still an issue?
Thank you,
Tim

**Comment by g4gaurang** [comment]
This looks good now. Please move changes to Prod.

**Comment by sayotte7701** [comment]
The fix has been loaded to production.   Please feel free to close this item at your convenience.

**Comment by g4gaurang** [comment]
No issues have been reported in production. This is being closed
