### ISSUE TITLE
Unable to edit out-of-network column for Generic drugs

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#275]
**Steps to Reproduce**
1. Login to Pclient5 as an admin
2. search and select 3464152__Preferred_Blue_Options_Deductible II_v.5_777555BS
3. Edit this plan through the manage plan interface
4. Go to the common medical event tab and try changing the values for out-of-network column for Generic drugs.

**Actual Result:**
You will notice your cursor icon change to a non-edit icon. See screenshot.This does not happen with the other tier or columns.

**Expected Result:**
System should allow you to edit this value like it does allow you to edit other value

![image](https://cloud.githubusercontent.com/assets/10272072/10693699/c97ebcba-7967-11e5-8b10-fbf928d4eb40.png)

**Comment by TimHeasley** [comment]
Guarang,
We have tested in PClient5 and were not able to replicate the issue.  I also created a custom plan (3464154) using the same standard base plan (800373) and was able to edit the Generic OON field.  Can you retest and see if you are still seeing an issue?  

https://drive.google.com/file/d/0B346D2AloIVGcFRpWlltRm0xR2M/view?usp=sharing

Thanks,
Tim

**Comment by g4gaurang** [comment]
I ran into the above issue while trying to replicate an issue a user reported. While I no longer encounter the non-editable field issue, I still encounter the issue the user reported - 

**Steps to Reproduce**
1. Login to Pclient5 as an admin
2. search and select 3464152__Preferred_Blue_Options_Deductible II_v.5_777555BS
3. Edit this plan through the manage plan interface
4. Go to the common medical event tab and try changing the values for out-of-network column for Generic drugs to  "$40 / retail supply for low cost generic drugs; $80 other generic drugs" 
5. turn the cascading to No Cascade" and click save.

**Actual Result:**
When screen refreshes, the newer value you put in the field is no longer saved and is instead defaulted to another value.

**Expected Result:**
System should allow use to save any value they input when they turn cascading off.

**Comment by TimHeasley** [comment]
Guarang,
This has been updated and tested in PClient5.  The value saves correctly.
Please retest in PClient5.
Thank you,
Tim

**Comment by g4gaurang** [comment]
This looks good. Please move to prod.

**Comment by TimHeasley** [comment]
Guarang,
The changes have been moved to Production and are ready for retest.
After approval/confirmation please close the issue.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Looks good in production.
