### ISSUE TITLE
Capture File Fill Diabetes and Maternity Values error - % retail and mail service supply

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#277]
Hello,
One of our BEs attempted to generate an SBC, but received the Capture File Fill Diabetes and Maternity Values error.  It was determined that the calculator is unable to generate due to the % retail and mail service supply values demonstrated.  Note that these values are correct, and the calculator should account for them.

The custom plan generated was 3456851_Entegris, Inc_Blue_Care_Elect_Saver_90_1500_154854BS

Please fix globally ASAP

![screen shot 2015-10-29 at 10 24 56 am](https://cloud.githubusercontent.com/assets/13453008/10822530/096e212e-7e2e-11e5-82e5-0403edf5c66c.png)

![screen shot 2015-10-29 at 10 24 41 am](https://cloud.githubusercontent.com/assets/13453008/10822485/dc186036-7e2d-11e5-8f79-2a7fdcf8c4c8.png)

**Comment by michparrish** [comment]
HR is reviewing the item

**Comment by TimHeasley** [comment]
Will,
The calculator has been updated.  The “ / retail and mail service” part was throwing off in the Preferred Brand Drugs Mail Order cell and the combined “retail and mail order override” was not overriding it for that cell.

The fix has been tested and confirmed in PClient5.  Please retest at your convenience. After confirmation/approval we will move fix to Production.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

The calculator is generating, however I came across a couple incorrect maternity calculations.  Please see attached PDFs and screenshots.  The deductible amount(s) are off by $20.

Please advise.

![screen shot 2015-10-29 at 5 50 07 pm](https://cloud.githubusercontent.com/assets/13453008/10833122/1e6eb88a-7e66-11e5-995c-2141c72a186e.png)
[sbc_preview(513).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/23809/sbc_preview.513.pdf)
![screen shot 2015-10-29 at 6 02 41 pm](https://cloud.githubusercontent.com/assets/13453008/10833304/46f57a04-7e67-11e5-935c-7e0b030a91da.png)

[sbc_preview(514).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/23795/sbc_preview.514.pdf)

**Comment by g4gaurang** [comment]
Tim, we need this fix ASAP. What is the status on this ?

**Comment by michparrish** [comment]
this is in process - we'll let you know as soon as it's complete and ready for retest

**Comment by michparrish** [comment]
This has been fixed and retested to success. Please retest and let us know if you're ready to move to Prod.
Thanks!

**Comment by willdwyer** [comment]
Hi, this defect looks good.  Please move to production.

However, note that we discovered 2 separate defects in the midst of re-testing (being reported now).

**Comment by michparrish** [comment]
calculator has been loaded to Prod. Please test and close item as you see fit.

**Comment by willdwyer** [comment]
Hi, we tested in production, and noticed a discrepancy in the cost calculator.  We tested the original plan the defect was discovered on (3456851_Entegris, Inc_Blue_Care_Elect_Saver_90_1500_154854BS), and the diabetes calculations were off.  See screenshot below and attached PDF.

[sbc_preview(534).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/29248/sbc_preview.534.pdf)

![screen shot 2015-11-06 at 4 58 01 pm](https://cloud.githubusercontent.com/assets/13453008/11009782/bb2cd124-84a7-11e5-800f-5682f299d4be.png)

**Comment by TimHeasley** [comment]
Will,
The calculator has been updated in PClient5 and is ready for retest.  
After you confirm/approve we will move the calculator to Production that will correct this issue and #273.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

During re-testing, we encountered this error again (Capture File Fill Diabetes and Maternity Values)

Please see custom plan 
3475157_Lisa Test 5_Network_Blue_Options_Ded_v.4_1234TEST
 in PCLIENT5.

![screen shot 2015-11-13 at 2 33 31 pm](https://cloud.githubusercontent.com/assets/13453008/11155449/87bd42d0-8a13-11e5-8a87-a23b86f72e6d.png)

**Comment by TimHeasley** [comment]
Hi Will,
This is ready for retest in PClient5.  
Thank you for testing.
Tim

**Comment by willdwyer** [comment]
Looks good, Tim.  Please move to production.

**Comment by TimHeasley** [comment]
Will, 
Thank you for testing.  The updated calculator has been moved to Production.  It is ready for retest.  After you confirm/approve it is working correctly please close the issue.
Thanks,
Tim

**Comment by willdwyer** [comment]
I completed testing, and this looks good.  Defect is now being closed.

**Comment by willdwyer** [comment]
Hello,

This is an old issue that is reopening, as it was discovered by a BE today.  Please see screenshots.

This is for plan 3559474_Bristol Plymouth Regional School District_Master_Medical_160786BS

![screen shot 2016-04-07 at 10 56 52 am](https://cloud.githubusercontent.com/assets/13453008/14356238/04155622-fcb2-11e5-860d-e84ee68b2af4.png)
![screen shot 2016-04-07 at 10 27 36 am](https://cloud.githubusercontent.com/assets/13453008/14356239/041ec31a-fcb2-11e5-9f8a-bcc7fcc3ab4e.png)
![screen shot 2016-04-07 at 10 27 32 am](https://cloud.githubusercontent.com/assets/13453008/14356237/04134922-fcb2-11e5-8bd3-528c93cadba6.png)

Note this is showstopper priority, and must be fixed ASAP.  Please make sure this is fixed globally, as we don't want to reopen this again.

**Comment by TimHeasley** [comment]
We are looking at the calculator. As soon as we have a fix we will let you know when you can retest.
Thanks

**Comment by TimHeasley** [comment]
Will, we have fixed the calculator and it is now ready for retest in PClient5.

**Comment by willdwyer** [comment]
HI Tim,

There is an issue with the Cascade All function for this Eligible Option in PCLIENT5 now ( 20% coinsurance/20% coinsurance/20% coinsurance retail; $5/$10/$10 mail )

See screenshot.  When inserting this option, and selecting Cascade All, it does not cascade properly.  The mail service supply information is missing from Preferred Brand Drugs and Non-preferred brand drugs.

![screen shot 2016-04-08 at 10 16 46 am](https://cloud.githubusercontent.com/assets/13453008/14386836/81e42732-fd74-11e5-9428-7f9f4b0b9a67.png)

**Comment by TimHeasley** [comment]
We will research the cascade issue in PClient5 and let you know when it is ready for retest.

**Comment by TimHeasley** [comment]
We have updated the workbook and tested in PClient5.  Ready for retest.

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Workbook has been moved to Production. Thanks

**Comment by willdwyer** [comment]
Not fixed.  As I said, be sure this is fixed globally across ALL plans.  In the midst of testing in production, the defect was discovered to still exist from generating a custom out of standard plan 800207HR_Comprehensive_Major_Medical_80-0128LG1-1-16

**Comment by TimHeasley** [comment]
Will, I just tested in PClient5 creating a custom plan using 800207 and the fields cascade correctly.
See screenshot.

![277](https://cloud.githubusercontent.com/assets/13483804/14394919/ad9ff5a4-fd9c-11e5-90cd-7ceed5867531.JPG)

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Thank you for testing.  The updated workbooks have been moved to Production.

**Comment by willdwyer** [comment]
Looks good.  Closed.

**Comment by willdwyer** [comment]
Hello, this issue is being re-opened as it was discovered by 1 of our BEs.

When trying to input value drugs into Rx cost share information when both coinsurance and copayment are accounted for, the defect is encountered.  I confirmed this by removing value drug information, and was able to generate.  Please see attached screenshots and resolve.

![unknown-6](https://cloud.githubusercontent.com/assets/13453008/18959076/df1d0ca6-8632-11e6-99e7-93c0104a38c5.png)
![unknown-5](https://cloud.githubusercontent.com/assets/13453008/18959077/df28ffc0-8632-11e6-8df5-9db2b3561af3.png)

**Comment by michparrish** [comment]
We are working on this issue - was able to recreate in pclient5 with plan created from 900192HR_Blue_Care_Elect_Pref_80_Copay_80-0138LG1-1-17, the source plan used in this one.

**Comment by michparrish** [comment]
HIGRDS-749 bug has been created for this item

**Comment by michparrish** [comment]
Tested this out a bit more today and the issue seems to be pointed to the type of plan, potentially. As the update works fine with an Access Blue NE plan (900178). Was there anything different done to the Blue Care Elect plans this year?

**Comment by michparrish** [comment]
never mind my question - all works correctly without that additional 'no cost for value drugs' text in the Blue Care Elect plans. Still researching...

**Comment by michparrish** [comment]
ok - so we figured it out and I'm going to close the bug.
If you want to check it out in pclient5 on the original plan (900192HR_Blue_Care_Elect_Pref_80_Copay_80-0138LG1-1-17), make a copy of it and update the Preferred Drug text to what your BE updated, you can now generate a document.
Please let me know how it goes and we can move the new calculator into Prod ASAP.

The issue:
For some reason, the calculator was pulling back Coinsurance = 0.05 when it should return Copayment = 0 when it’s no charge. Change has been made and a new calculator uploaded into pclient5 for your testing.

**Comment by willdwyer** [comment]
Looks good, please move to production

**Comment by cfieldsHR** [comment]
This has been updated in production.

**Comment by willdwyer** [comment]
All set.  Closed
