### ISSUE TITLE
Capture File Fill Diabetes and Maternity Values error - $ 5/ retail supply or No charge / mail service  supply

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#278]
User receives the Capture File Fill Diabetes and Maternity Values error when trying to generate an SBC document. On further analysis of the generic drugs cost share it seems the culprit is the No charge part of the string-

$ 5/ retail supply or **No charge** / mail service  supply

Please fix so that the calculators work when the cost share is No charge.

L. Knife and Son, Inc. BCEP100/80 [155485BS]

![image](https://cloud.githubusercontent.com/assets/10272072/10942683/1e2370aa-82df-11e5-976a-26fbc339b071.png)

**Comment by michparrish** [comment]
this is in process, we'll let you know when it's ready for retest - thanks!

**Comment by michparrish** [comment]
Calculator has been updated and tested in pclient5 to success, using '...no charge / mail service supply' and '...No charge / mail service supply' (changing capitalization).
Please retest at your earliest convenience.

**Comment by g4gaurang** [comment]
Changes look good on Pclient5. Please move to prod.

**Comment by michparrish** [comment]
thanks - please test the other calculator item and we can move the full calculator into prod to fix all open items.

**Comment by michparrish** [comment]
item 277

**Comment by michparrish** [comment]
calculator has been loaded to Prod. Please test and close item as you see fit.

**Comment by g4gaurang** [comment]
Changes look good in production.
