### ISSUE TITLE
Cascade override issue - Blue Choice plan, Generic drugs field

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#279]
Hello,

When creating a custom plan out of Blue Choice $5 standard plan, the following defect was discovered:

By changing the cascade option to No Cascade under Generic Drugs, inputting same value for all fields, and then save/validating... see screenshot, as value in Self-Referred defaults to Not Covered.

Please fix globally.

![screen shot 2015-11-04 at 2 25 26 pm](https://cloud.githubusercontent.com/assets/13453008/10949899/49001d90-8303-11e5-82a4-d031e0069a98.png)

**Comment by TimHeasley** [comment]
We are researching the issue.

**Comment by TimHeasley** [comment]
Will,
Workbook has been updated and tested in PClient5.  Cascade option is working correctly.
Ready for retest, after you confirm/approve, we can move to Production.
Thanks
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This looks good.  You can move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for testing.  The workbooks have been moved to Production.
Please test in Prod and after confirmation of fix, please close issue.
Thanks,
Tim

**Comment by willdwyer** [comment]
Looks good.  Closed.
