### ISSUE TITLE
Cascade override issue - HMO Blue NE HCCS plan, Rx drugs fields

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#280]
Hello,

When creating a custom plan out of HMO Blue New England Premier Value with HCCS standard plan, the following defect was discovered:

By changing the cascade option to No Cascade under Generic Drugs, and then inputting SEPARATE values in In-Network Lowest Cost Share, In-Network Highest Cost Share, and then save/validating... see screenshot, as value in In-Network Highest Cost Share defaults to what is in In-Network Lowest Cost Share.
![screen shot 2015-11-04 at 2 47 25 pm](https://cloud.githubusercontent.com/assets/13453008/10949981/9a61e8d0-8303-11e5-8d18-25f667a83098.png)
Please fix globally.

**Comment by TimHeasley** [comment]
We are researching the issue.

**Comment by TimHeasley** [comment]
Will,
 Workbook has been updated and tested in PClient5. Cascade option is working correctly.
 Ready for retest, after you confirm/approve, we can move to Production.
 Thanks
 Tim

**Comment by willdwyer** [comment]
Looks good, Tim.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for testing.  The workbooks have been moved to Production.
Please test in Prod and after confirmation of fix, please close issue.
Thanks,
Tim

**Comment by willdwyer** [comment]
Looks good.  Closed.
