### ISSUE TITLE
Time-out issue in IE8

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#281]
Hello,

This was reported by Kevin Selvo.  

This was encountered by: going to Manage Plan configurator in IE8, creating a custom out of standard plan HMO Blue NE $5_LG, clicking Plan Details tab...

The below script error was encountered.
@kselvo01 
![untitled132](https://cloud.githubusercontent.com/assets/13453008/10950025/cd2ee3f8-8303-11e5-9126-310116e8457f.png)

**Comment by michparrish** [comment]
Hi Will,
I can't see that error message clearly, even when I zoom in on it. Do you have a cleaner copy you can send to me or post? Thanks.

**Comment by g4gaurang** [comment]
See attached. 

[Document3.docx](https://github.com/g4gaurang/bcbsmaissuestracker/files/27452/Document3.docx)

**Comment by g4gaurang** [comment]
Occurred again at 9:08 on the create custom plan from search results.

![image](https://cloud.githubusercontent.com/assets/10272072/10971206/1ab91baa-83a1-11e5-8a79-83bef11bab68.png)

**Comment by g4gaurang** [comment]
When clicking create new plan button at 9:19

![image](https://cloud.githubusercontent.com/assets/10272072/10971232/483144cc-83a1-11e5-8c24-36af8d79b65a.png)

**Comment by g4gaurang** [comment]
Click on plan details tab at 9:30

![image](https://cloud.githubusercontent.com/assets/10272072/10971262/6c1c6a42-83a1-11e5-90b2-43fc35f87aef.png)

**Comment by michparrish** [comment]
Thank you for the additional detail. I've reached out to our QA team to start the investigation into why this would be occurring.

**Comment by michparrish** [comment]
@willdwyer @kselvo01 
All: wanted to check in to see if this has been experienced lately? We have the item with QA who is working with IT to investigate but as time passes, I wanted to see if there was a more recent instant of this.
Thanks!

**Comment by willdwyer** [comment]
This defect has not been encountered in monitoring status, and since we have migrated from IE8 to IE11, this appears to be resolved.  This item will now be closed.
