### ISSUE TITLE
Clicking logout, then clicking back button... still logged in

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#282]
Hello,

If a user clicks Quick Links, then logs out of HighRoads...
then the user then clicks the back button on the browser, the user still has access to all functionalities as if he/she was still logged in to the system.

This is a security issue, so please fix.

**Comment by TimHeasley** [comment]
Will,
We will research the issue and look for a solution.
Thank you,
Tim

**Comment by TimHeasley** [comment]
Hi Will,
We had multiple people test both from the Dashboard and from inside the Configurator. When clicking the Back button we did see the login screen again. 

Can you retest to see if it is still occurring?  You may have to clear your cache.
Thanks,
Tim

**Comment by willdwyer** [comment]
BCBS had an internal meeting on this yesterday with our IT department.  More information will be provided soon

**Comment by willdwyer** [comment]
Hello, this has been fixed internally by our IT team.  This defect is now being closed.
