### ISSUE TITLE
Update the footer font from size 10 to size 12.

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#283]
We realized the footer font size on all SBCs generated through the HR system is 10 points. It should always be 12 points per government mandate.
(Unless otherwise instructed, the plan or issuer must use 12-point (as required by Federal law) font, and replicate all symbols, formatting, bolding, and shading. )

Please make this template level change so that all SBC documents word or PDF will henceforth generate  footer text with 12 point size. 

This footer text is both on the first and last page of the SBC template.
The font type is Arial Narrow and that does not change.

![image](https://cloud.githubusercontent.com/assets/10272072/11129816/8aa0921e-894f-11e5-81d7-c3c50948a2c5.png)

**Comment by TimHeasley** [comment]
Guarang,
We have tested an assortment of plans: HMO, PPO, POS, and EPO on all available tiers in PClient5. Everything looks good with no spacing issues. Please retest in PClient5.
Thanks,
Tim

**Comment by g4gaurang** [comment]
This runs it too close. Can you do something about it ?

![image](https://cloud.githubusercontent.com/assets/10272072/11304493/41c4d6f4-8f76-11e5-8a64-5dc636677f65.png)

**Comment by sayotte7701** [comment]
We've made an update to this in pclient5.  Let us know if this works.   Thank you.

**Comment by g4gaurang** [comment]
The footer alignment on the last page looks good. Can you do something about the footer alignment of the licensee statement on the first page ? Move it more rightwards towards the page numbering ?

![image](https://cloud.githubusercontent.com/assets/10272072/11591954/a2d3c2ea-9a69-11e5-9860-2132a66acc7c.png)

**Comment by sayotte7701** [comment]
The templates have been updated to move the licensee information further towards the right and closer to the page numbering in pclient5.   Please validate at your convenience.   Thank you.

**Comment by g4gaurang** [comment]
Looks good on Pclient5. Please move to production.

**Comment by TimHeasley** [comment]
Guarang,
The templates have been moved to Production.  Please confirm the updates and close after you complete your testing.
Thank you,
Tim

**Comment by g4gaurang** [comment]
The footnote on the back has “You can View the Glossary at www….. or call 1-800-262-BLUE To request a copy”. The V in view and T in to should not be uppercase.  Please fix ASAP on production across all templates and redeploy. This has been deemed a showstopper by the team and they are unable to finalize any final SBC output documents until then.

![image](https://cloud.githubusercontent.com/assets/10272072/11813815/4a9412b4-a311-11e5-8701-573d9eb9b3f6.png)

**Comment by sayotte7701** [comment]
The templates have been updated and loaded to pclient5.  If you don't need to validate in pclient5, let me know and I can load these to production.

thank you

**Comment by g4gaurang** [comment]
> The templates have been updated and loaded to pclient5. If you don't need to validate in pclient5, let me know and I can load these to production.
> 
> thank you

If you just changed the caps on the letters, then you can move to production.

**Comment by sayotte7701** [comment]
Thank you Guarang.  The updated templates have been loaded to production.

**Comment by TimHeasley** [comment]
Keeping open for a week until confirmation of no issues.  Issue will be closed after this timeframe.

**Comment by willdwyer** [comment]
Hi Tim,

We have discovered an error with the footer on indemnity plans.  The wording is cut off (see below), as the sentence ends in "request a"... the word copy is missing.  Please re-generate test and fix all standard indemnity plans.

Thanks,

<img width="924" alt="screen shot 2015-12-22 at 3 02 45 pm" src="https://cloud.githubusercontent.com/assets/13453008/11964676/4c2e2716-a8bd-11e5-8995-ceecb54bda17.png">

[sbc_preview(646).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/70134/sbc_preview.646.pdf)
[sbc_preview(644).pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/70133/sbc_preview.644.pdf)

**Comment by sayotte7701** [comment]
Hi Will,

The indemnity template has been corrected and loaded to pclient5.  Please let me know when I can move it into production.   thank you

**Comment by g4gaurang** [comment]
See attached PDF. The disclaimer language is getting cut off and dropping the word “Association.

[157376BS_MMWEC_BCEP100_80_CAD_12-29-15.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/74942/157376BS_MMWEC_BCEP100_80_CAD_12-29-15.pdf)

PLEASE fix globally and retest all templates. BCBSMA cannot send out such SBC templates to the market.

**Comment by michparrish** [comment]
Gaurang - do you mean this sentence? This is the same statement on all docs and looks like a completed sentence. I can't find where you're talking about.
Disclaimer:
This document contains only a partial description of the benefits, limitations, exclusions and other provisions of this health care plan. It is not a policy. It is a general overview only. It does not provide all the details of this coverage, including benefits, exclusions and policy limitations. In the event there are discrepancies between this document and the policy, the terms and conditions of the policy will govern.

**Comment by michparrish** [comment]
Disregard my  note - I found the location.

**Comment by g4gaurang** [comment]
The highlighted sentence is missing the word "Association"  at the end

![image](https://cloud.githubusercontent.com/assets/10272072/12053097/ad944dc4-aee3-11e5-97fd-bd07b34486dd.png)

**Comment by michparrish** [comment]
Thanks
This only impacted the 2-tier template. The template has been fixed and uploaded to pclient5. Please retest and I can move this to production ASAP.

**Comment by g4gaurang** [comment]
Please move to production as long as any changes you made are limited to this fix.

**Comment by michparrish** [comment]
2T template has been moved to Prod.

**Comment by willdwyer** [comment]
Hi Michelle,

Per comment that was to addressed to Tim on this thread 14 days ago" The wording is cut off (see below), as the sentence ends in "request a"... the word copy is missing."

That error was encountered again after generating custom plan 3504401.  See attached PDF.  Please fix globally.
[sbc_preview(647).pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/78633/sbc_preview.647.pdf)

**Comment by michparrish** [comment]
the 2 tier template has been fixed in pclient5 - I had to move the word 'the' up to the 2nd line in the Glossary footnote. Please retest in pclient5 with a 2t plan and I can move this template into Prod ASAP. Thank you.

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by michparrish** [comment]
all set! thank you!

**Comment by willdwyer** [comment]
Michelle, while testing in production, I came across an instance where I generated a custom out of a standard, and the footer was not correct (same issue).  The standard was 800341HR_Master_Medical_80-0129LGASC1-1-16 

Please make sure this fix is made globally across all standard plans.

**Comment by willdwyer** [comment]
Just attaching PDF showing instance.

[sbc_preview(656).pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/80033/sbc_preview.656.pdf)

**Comment by michparrish** [comment]
Apologies, Will. I've updated the 1, 3, and 4T templates to move up the word 'the' to the 2nd row and pulled in the rest of the 3rd row of the footer statement. All templates are updated in pclient5 and tested. please retest and let me know when you want them moved to Prod. Thank you.

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by michparrish** [comment]
templates moved - please retest and close item. Thanks!

**Comment by willdwyer** [comment]
Looks good, Michelle.  This defect is being closed.
