### ISSUE TITLE
Enhancement Request: 'Recommended Attributes' denotation to be available during Bulk Editing of attributes - BPMS-I-20

### ISSUE THREAD

**Issue by michparrish** [willdwyer/bcbsmaissuestracker#293]
BCBS would like to request that the 'Recommended Attributes' be applied to bulk editing of attributes as well, as their 'Recommended Attributes' are applied to all doc types. This would be in the Tools > Edit Attributes function.

Also related to another request, BPMS-I-18, the ability to apply attributes to multiple docs at once (the same attributes) when uploading new docs. We'd want the Recommended Attributes functionality on this popup as well for bulk loading.

Opened request today 11/17. Will update item when this has been included in new sprint for consideration and LOE estimate.

**Comment by michparrish** [comment]
All:
Dev was able to update this item as part of the Recommended Attributes item, rather than a separate enhancement request. Therefore we did not have to return back to your team for LOE approval. Also, the hours for this item will not count toward your enhancement request allotment.
This item is with our QA team now and when they have tested successfully, we will schedule a deployment to pclient5 for our teams' testing. 

For this item - users will be able to see a denotation of Recommended Attributes when using the bulk attribute editing tool at Tools > Edit Attributes.

HighRoads will report back when QA has finished with their testing and we are ready to deploy to our test environment.

**Comment by TimHeasley** [comment]
Working with QA to complete testing to secure a Production date by end of January.

**Comment by TimHeasley** [comment]
This enhancement is also being built to QA environment with completion of testing scheduled for the end of this week.

**Comment by markderg** [comment]
Our internal testing found a defect preventing us from moving forward with BCBMA testing/validation.  We are currently investigating the issue with our QA and Development Teams.  Our expected production date is now TBD based on this defect.  Once we understand the root cause we will follow up with a definitive plan of action including a new testing and production date schedule.

**Comment by willdwyer** [comment]
Hi Marc, per comment in #260 , please provide more specific details on this defect.

**Comment by willdwyer** [comment]
Hi Mark, per comment in #260, please provide an update.

**Comment by TimHeasley** [comment]
Issues #260 & #293 are critical needs for the BCBSMA team for their March 11 training.

**Comment by willdwyer** [comment]
Hello,

Just a reminder that this deadline is approaching.

**Comment by TimHeasley** [comment]
Preparing to move to PClient5 along with #260 #335 #336

**Comment by TimHeasley** [comment]
Will,
I have tested and confirmed the updated code has been moved to PClient5.
It is ready for testing in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Please move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for testing.  
The code is tied in with the following issues and be moved to Production once we have approval. 

#256 - code is working, need to fix on configuration side, able to move to Prod
#260 - approval to move to Production, even though there is an issue when loading pdf & word documents together
#293 - approval to move to Production
#335 - fixed ready for retest
#336 - fixed ready for retest
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I am confused with the above to reference #256 ... I thought this wasn't tied in with the next production code update?

We are scheduled to train new hires on the new upload/attribute process tomorrow at 2PM, so we definitely need this moved to production before then (ideally before noon, so we can confirm there are no further issues).  This is why there was a deadline associated to it.

If it is indeed tied to #256 , then please work and fixing the remaining requirement on this ASAP, so we can move to production.

Please know that this is a hot issue.

**Comment by TimHeasley** [comment]
Go-NoGo to production meeting scheduled for 3/29.

**Comment by TimHeasley** [comment]
We are a Go for moving the code to Production this evening.  We will notify you tomorrow when you can test in Production.

**Comment by willdwyer** [comment]
OK thank you.  Will the production environment be down for a certain period of time?  If so, when?

**Comment by TimHeasley** [comment]
The IT Team will be deploying the build tonight between 22:00 and 23:00 to the Payer Production environment.  For the duration of this work the Payer Production environment will not be available.

**Comment by TimHeasley** [comment]
Code has been moved to Production and is ready for retest.

**Comment by willdwyer** [comment]
Looks good.  This is now closed.
