### ISSUE TITLE
Unable to remove Hearing Aids Limitations text

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#296]
When BE attempts to remove the “$2,000 per ear every 36 months for members age 21 or younger” from the Hearing Aids limitations field on the Excluded services Tab, it won’t save. In other words, system will not take it off even if user deletes the texts and clicks save. This issue was noticed in production and replicated in Pclient5 on 3478158__Advantage_Blue_555333BS  
Please see below for the screen shots from production and fix.

![image](https://cloud.githubusercontent.com/assets/10272072/11276373/e259491e-8eaf-11e5-9db6-8cc50496ee2f.png)

![image](https://cloud.githubusercontent.com/assets/10272072/11276400/f73dd764-8eaf-11e5-875f-3d88d131d2d4.png)

![image](https://cloud.githubusercontent.com/assets/10272072/11276409/038cef46-8eb0-11e5-8d79-e634359100ad.png)

**Comment by michparrish** [comment]
I was able to recreate in pclient5 as well. We're reviewing/investigating.

**Comment by TimHeasley** [comment]
Guarang,
We have corrected the workbook.  It has been tested in PClient5 and confirmed working correctly. 
Please retest at your convenience.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Guarang,
This is ready for retest in PClient5.  
After you confirm we will be able to move this issue, along with #297 & #298 to Production.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Fix looks good on Pclient5. Please move to production.

**Comment by sayotte7701** [comment]
This configuration has been loaded to production.  Please validate and close at your convenience.  Thank you.

**Comment by g4gaurang** [comment]
Looks good in production.
