### ISSUE TITLE
Cascade override issue - HCCS plan, inpatient fields

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#297]
Hello,

It was reported by one of our BEs that certain fields in HCCS plans are cascading improperly.

Maternity Inpatient (highest cost share) usually reads as “$XXXX admission for general hospitals and no charge for delivery,” but is being replaced with standard language from MH Inpatient (highest cost share) “No charge or $XXXX admission for general hospitals.

Please fix globally.  I have attached a sample PDF showing the improper cascading.

[sbc_preview-4.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/39218/sbc_preview-4.pdf)

**Comment by TimHeasley** [comment]
Will,
The workbook has been updated and tested in PClient5.  It is working correctly.
Ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
This looks fixed.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for retesting. Since issues #296 (#298 has been approved) also involves workbook updates, once it is confirmed as fixed we'll move them all to Production.
Thanks,
Tim

**Comment by sayotte7701** [comment]
The configuration has been loaded to production. Please validate and close at your convenience. Thank you.

**Comment by willdwyer** [comment]
Looks good, Steve.  This is being closed.
