### ISSUE TITLE
Missing space on cascaded value in Emergency room services field

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#298]
This defect was encountered when editing custom plan 3478151_Lisa Test 15_HMO_Blue_NE_Options_Ded_II_v.5_1234TEST...

On the Emergency room services field, when selecting Cascade All and then one of the LOVs from Eligible Options... after cascading and saving/validating, there is a missing space in all of these values.  Please see screenshots.  Note the defect was encountered in PCLIENT5.

![screen shot 2015-11-19 at 10 46 41 am](https://cloud.githubusercontent.com/assets/13453008/11279109/a262b7fc-8ebc-11e5-8b39-facf76be2c10.png)
![screen shot 2015-11-19 at 10 44 35 am](https://cloud.githubusercontent.com/assets/13453008/11279110/a264a2ba-8ebc-11e5-891e-9bac279690af.png)

**Comment by TimHeasley** [comment]
Will,
We have corrected the workbook. It has been tested in PClient5 and confirmed the values appear correctly. Please retest at your convenience.
Thanks, Tim

**Comment by willdwyer** [comment]
Hi Tim, this looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Will,
Thank you for retesting.  Since issues #296 & #297 also involve workbook updates, once they are confirmed as fixed we'll move them all to Production.
Thanks,
Tim

**Comment by sayotte7701** [comment]
This configuration has been loaded to production. Please validate and close at your convenience. Thank you.

**Comment by willdwyer** [comment]
Looks good, Steve.  This is now being closed.
