### ISSUE TITLE
Comments on grandfathered disclosure

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#299]
See attached. The Grandfathered disclosure that attaches from the HR system comes in with comments from Steve Kelsey. While these boxes are not visible on the grandfathered disclosure,when user selects the comments feature in adobe, these invisible comments show up. Please clean up these comments from the grandfathered disclosure and deploy back both on Pclient5 and production.

[156265BS_LC_11_20_15_QC.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/43940/156265BS_LC_11_20_15_QC.pdf)
[156265BS_L. Knife and Son Inc._BCEP_CAD_11-18-15.pdf](https://github.com/g4gaurang/bcbsmaissuestracker/files/43941/156265BS_L.Knife.and.Son.Inc._BCEP_CAD_11-18-15.pdf)

**Comment by TimHeasley** [comment]
Guarang,
I updated the grandfathered disclosure and review the comments that appeared.  Please retest in PClient5.  After confirmation/approval I will move the disclosure to Production.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Looks good. Please move to prod.

**Comment by TimHeasley** [comment]
Guarang,
Thank you for testing.  The updated disclosure has been moved to Production.
After you retest & confirm please close issue.
Thanks,
Tim

**Comment by g4gaurang** [comment]
Looks good in production.
