### ISSUE TITLE
Custom plan design with multiple issues

### ISSUE THREAD

**Issue by g4gaurang** [willdwyer/bcbsmaissuestracker#301]
BE is getting some strange errors when just starting her job. 
1.  #N/A in the website even though its Insured.
2.  Diabetes and Maternity errors and I haven’t even adjusted the benefits. She filled out the required fields to start and save job. (screen shot)
3.  Tried to preview and got another error. (screen shot)
4.  She searched for the job and its pulling the template number rather than the high roads job number (3477154_National Lumber Company_Preferred_Blue_Ded_2000_156526BS)

![image](https://cloud.githubusercontent.com/assets/10272072/11483219/4b61e560-9775-11e5-83a7-f632a0685cb9.png)

![image](https://cloud.githubusercontent.com/assets/10272072/11483240/628c13dc-9775-11e5-922d-71d4a55410b2.png)

![image](https://cloud.githubusercontent.com/assets/10272072/11483256/70ad4e4a-9775-11e5-9384-92473e30c9ab.png)

**Comment by sayotte7701** [comment]
Thank you for reporting this.   I went in an checked and it looks like this plan was generated from a 2015 standard plan, and not a 2016.   I would expect to see some of the errors reported if a 2015 plan was used.   Could you confirm this is the case.   Thank you.

**Comment by g4gaurang** [comment]
HR does not support 2015 plan design SBC generation through their system. HR, please ensure you are able to support multi year SBCs for next year. (2016 and 2017 ) -  This will not be a choice going forward.
