### ISSUE TITLE
Inpatient fields cascading issue

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#324]
Hello, this was reported by one of our BEs.

3487203_DeniseTest_Preferred_Blue_Ded_500_789456BS 

The inpatient Facility Fee (e.g. hospital room) is cascading incorrectly.  When Cascade All is selected, the user input a value of $1,000 / admission in Facility Fee (e.g. hospital room) - Inpatient Highest Cost Share, which isn't among the list of values (per screenshots).  Upon saving/validating, the value is cascading to the Highest Cost Share Fields in Mental Health Inpatient Services and Substance Abuse Inpatient Services.

See screenshots below.  Please fix globally.

![screen shot 2015-12-11 at 11 51 41 am](https://cloud.githubusercontent.com/assets/13453008/11756390/8c8c4462-a027-11e5-9bf4-63aa83aed52b.png)
![screen shot 2015-12-11 at 11 54 48 am](https://cloud.githubusercontent.com/assets/13453008/11756392/8c8ea658-a027-11e5-964b-d711d77dc6a1.png)
![screen shot 2015-12-11 at 11 54 19 am](https://cloud.githubusercontent.com/assets/13453008/11756391/8c8de434-a027-11e5-9c41-9fd3151a67f6.png)

**Comment by TimHeasley** [comment]
Hi Will,
I just tested creating a custom plan - 3484151__Preferred_Blue_Ded_500_800115HR using 800115 as the base standard plan.  I tested the cascading rules for Facility fee (e.g., hospital room) and it appears to be cascading correctly. 
Can you retest and let us know if the issue still appears?
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I just retested the original plan this was reported from, and it seems to cascade correctly.  This is being closed.
