### ISSUE TITLE
Unable to generate standard advantage blue plan

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#326]
Hello,

When attempting to generate the 800288HR_Advantage_Blue_80-0204LGASC1-1-16 plan, it does not complete generation, and just stay in screenshotted state.  Please advise.

<img width="889" alt="screen shot 2015-12-17 at 4 52 57 pm" src="https://cloud.githubusercontent.com/assets/13453008/11883137/c9410cc4-a4de-11e5-99a4-fddde97807f5.png">

**Comment by TimHeasley** [comment]
Will,
I just tested creating a new plan from standard plan 800288 and was able to generate both draft & final documents.  Can you retest to see if the issue is still appearing?
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim, I tried it again, and got this error (screenshot)
![screen shot 2015-12-18 at 11 00 25 am](https://cloud.githubusercontent.com/assets/13453008/11900913/9179cec8-a576-11e5-851d-da364e67f326.png)

**Comment by TimHeasley** [comment]
Hi Will,
It appears that the user is using Firefox which is not supported. 
Can you please retest using internet explorer and let us know the outcome?
Thanks,
Tim

**Comment by willdwyer** [comment]
Tim,

I retested in IE, and was able to successfully generate SBC(s).  This defect is now being closed.
