### ISSUE TITLE
Unable to edit Blue Care Elect custom plan

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#327]
Hello,

This was reported by one of our BEs.

User is unable to edit 3481414_Woods Hole Oceanographic Institute_Blue_Care_Elect_Saver_90_1500_157015BS

Please see the screenshot that user encounters when attempting to edit from the configurator interface.

![screen shot 2015-12-21 at 2 50 33 pm](https://cloud.githubusercontent.com/assets/13453008/11941278/583409de-a7fc-11e5-8289-81bc49b8c1df.png)

**Comment by TimHeasley** [comment]
Hi Will,
I will look into this issue and search for the cause.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Hi Will,
This plan used standard plan 800195 and it was determined by the HighRoads QA support team that this plan has a corrupt system ID.  See Issue #325.  The workaround is to recreate a custom plan from original standard plan or from this plan create another custom plan then edit it in Plan Configurator.
Thank you,
Tim

**Comment by willdwyer** [comment]
See issue #325

**Comment by TimHeasley** [comment]
Ties in with Issue #325 - 
"If you're no longer experiencing issues with this plan, we can close it. To be safe, we were going to generate a new copy of that Standard plan but it looks like things are working fine so we don't need to go to that extent. We ran the same tests as you and received the same results.
 please feel free to close this item if you see fit. Thanks!"

**Comment by willdwyer** [comment]
This issue, as well as #325 are being closed.
