### ISSUE TITLE
Custom accounts constantly creating new folders and re-adding name at end upon generation - AB-183

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#335]
See attached screenshot.  Everytime a new plan is generated for this account, it creates a new folder and adds 'Northeast Security, Inc.' to its folder name again.

![screen shot 2016-01-11 at 4 28 30 pm](https://cloud.githubusercontent.com/assets/13453008/12247789/94a10c0e-b883-11e5-97cd-6b1d897771e9.png)

**Comment by TimHeasley** [comment]
Will,
I tested in the Production Shadow environment a few times and the pdf's and word documents are going to the correct folder (Northeast Security, Inc.).  Can you let me know the steps the BE's are following, are they using the Preferred Account Name on the Plan Details tab?
Thank you for your help,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I just replicated the same steps as the BE, and confirmed this is a valid defect.

The steps were as follows:
1. Go to Search
2. Search for _157778_, plan design
3. Generate Draft PDF out of plan design
4. Go to Content Library
5. Note how another folder has been created with another replication of this account name (see screenshot)

![screen shot 2016-01-13 at 5 12 23 pm](https://cloud.githubusercontent.com/assets/13453008/12309463/da904aae-ba18-11e5-88f9-081330ca5091.png)

**Comment by TimHeasley** [comment]
Will,
Just wanted to give an update. We have cleaned up and consolidated the folders/files in Production. Tomorrow I will test in the production shadow environment the custom plan above and standard plan to research if the issue continues and possible causes.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
Tested this morning and new folders were still being created.  I will reach out to QA support to research.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

This particular item was regarding the issue with folders for account Northeast Security, Inc., and how this specific account seems to be duplicating its file name over and over when a new plan is generated.

Is this OK to retest?

**Comment by TimHeasley** [comment]
Not at this time, the QA team is still working on the issue with this particular folder.

**Comment by willdwyer** [comment]
Hi Tim,

Just adding to this - I went to generate another draft document under plan 157778, and this is what happened (see screenshot). 

<img width="950" alt="screen shot 2016-01-26 at 2 30 33 pm" src="https://cloud.githubusercontent.com/assets/13453008/12592216/7ebdbd80-c439-11e5-9bf8-ff5e61da3678.png">

**Comment by TimHeasley** [comment]
Will,
I would expect that to happen since we have not heard back from QA regarding a root cause.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Any update with this?

**Comment by TimHeasley** [comment]
Hi Will,
I am working with the QA team to see where this issue stands.  As soon as I have an update I'll let you know.  I'll see what I can do to help move this along.
Thanks,
Tim

**Comment by TimHeasley** [comment]
The QA team is still working on the issue with this particular folder and researching a fix. We will update as we learn new details on the root cause and timing.

**Comment by willdwyer** [comment]
Hello,

I have discovered another account (MSPCA) that is having this same issue.  Everytime a new plan is generated for this account, it creates a new folder and adds 'MSPCA' to its folder name again.  See screenshot.  I have also renamed this GitHub to a more general term.

<img width="1059" alt="screen shot 2016-02-25 at 11 52 07 am" src="https://cloud.githubusercontent.com/assets/13453008/13327543/4e5ead2a-dbb8-11e5-859d-15e143b58767.png">

**Comment by TimHeasley** [comment]
Preparing to move to PClient5 along with #260 #293 #336

**Comment by TimHeasley** [comment]
Will,
I have tested and confirmed the updated code has been moved to PClient5.
It is ready for testing in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Not fixed.

See screenshots, as recently generated PDF went to this folder with the account name MSPCA repeated.

<img width="1239" alt="screen shot 2016-03-14 at 3 23 14 pm" src="https://cloud.githubusercontent.com/assets/13453008/13757226/d56bdf3c-e9f9-11e5-95d8-5eeeda29a8bb.png">

<img width="1279" alt="screen shot 2016-03-14 at 3 24 27 pm" src="https://cloud.githubusercontent.com/assets/13453008/13757217/cd34cc20-e9f9-11e5-8c55-209719cbd276.png">

**Comment by TimHeasley** [comment]
Hi Will,
I cleaned up the folders (consolidated/removed) and tested both MSPCA & Northeast Security and they are going to the correct folders. 
Please retest in PClient5 at your convenience.
Thanks,
Tim

**Comment by willdwyer** [comment]
Looks good, please move to production.

Note: also with the move to production, please consolidate all folders into the correct one(s).

**Comment by TimHeasley** [comment]
Thank you for testing.  
The folders in Production have already been consolidated as a part of the folder updates tied in with issue #336.

**Comment by willdwyer** [comment]
Let me know when it has been moved to production, and we will test in that environment.

**Comment by TimHeasley** [comment]
Go-NoGo meeting to production scheduled for 3/29

**Comment by TimHeasley** [comment]
We are a Go for moving the code to Production this evening.  We will notify you tomorrow when you can test in Production.

**Comment by TimHeasley** [comment]
Code has been moved to Production and is ready for retest.

**Comment by willdwyer** [comment]
Looks good, Tim.  This is now being closed.
