### ISSUE TITLE
Ability to create subfolders for system generated folders in Content Library - AB-179

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#336]
Hello,

I believe we have discussed this before, but users in HighRoads are able to create subfolders for HighRoads/user created folders in Content Library, but NOT for system/configurator generated folders.  This is having a negatively time consuming effect on uploading documents to HighRoads.  See screenshots.
![screen shot 2016-01-19 at 1 54 31 pm](https://cloud.githubusercontent.com/assets/13453008/12429013/fbeff298-beb5-11e5-811c-c83adee45610.png)
![screen shot 2016-01-19 at 1 54 18 pm](https://cloud.githubusercontent.com/assets/13453008/12429014/fbf9960e-beb5-11e5-9fda-e338f2ce65ca.png)

Please fix this.

**Comment by michparrish** [comment]
Hi Will,
It's not that the system-generated folders won't allow a user to create new folders below them, but the system will not allow users to create new folders in Plan Masters at all, functioning as designed to provide a level of security to the area of CL that is considered 'final'. This is updated in the Ongoing Support Manual - when new folders need to be manually added to the Plan Master section of Content Library, this needs to be a request into HR and we can add it on the backend. 
If you need new folders added to this section, please submit a request to Support.
Thanks!
Michelle

**Comment by willdwyer** [comment]
Michelle,

In the manual, it notes that the process of sending requests to HR for folder set up should only be in place if the folder does not already exist.  

The issue that ties in with this is that there is no apparent difference between system generated folders and user-created folders in content library.  Therefore, if a user needs to create a subfolder, they won't know the correct process to follow, unless they click on each individual folder (which, needless to say, would be illogical).

My suggestion for a solution to this defect is 1 of 2 things:
1. allow BCBS users to create subfolders for both system generated and user-created folders (per your response, this would be done by overriding existing security measures)
2. make some sort of variance between system generated and user-created folders that would allow BCBS users to be able to easily distinguish between the 2 (perhaps a different color, icon, etc.)

Let me know which of the 2 options is feasible.

**Comment by michparrish** [comment]
Will,
Let's discuss in our meeting on Monday. There is not a permissions/editable restriction, this is a system restriction.
For your item #2 - the CMS folders are already yellow and the PM folders are blue:
![cms vs pm folders](https://cloud.githubusercontent.com/assets/13471811/12483630/1bd7904c-c024-11e5-90db-8fcbd69e2ea7.JPG)

**Comment by willdwyer** [comment]
Michelle,

I am referring to custom account folders.  If you notice on the 2 screenshots I attached to the first comment in this item, 1 folder lets the user create a subfolder, while the other 1 doesn't.  Also note how they were both 'blue' folders.  Also, see screenshot below, as all custom account folders are blue.

![screen shot 2016-01-21 at 10 27 25 am](https://cloud.githubusercontent.com/assets/13453008/12484732/a413078e-c029-11e5-8177-be6d0b588b9b.png)

**Comment by michparrish** [comment]
sorry - I thought we were talking about the differences between CMS and Plan Masters, not all within Plan Masters.
I will ask QA why a user is not allowed to create a Plan Master (year) folder under the configurator-generated folder vs the user-created Custom folder. I have a feeling it's b/c of the connection of the Configurator to these folders, as user entry may break that connection. I'll confirm. 
Thank you.

**Comment by willdwyer** [comment]
Hi Michelle,

Did you speak with QA about this?

**Comment by TimHeasley** [comment]
Will,
I sent an email this morning to see about an update for this item.  
As soon as I hear from them I will update GitHub.
Thanks,
Tim

**Comment by michparrish** [comment]
Will - we have a bug opened for this item. I'll note bug name in the name of this item and we'll have it on watch.
thanks for your patience.
michelle

**Comment by TimHeasley** [comment]
The QA team is still working on the issue with this particular folder and researching a fix. We will update as we learn new details on the root cause and timing.

**Comment by TimHeasley** [comment]
Preparing to move to PClient5 along with #260 #293 #335

**Comment by TimHeasley** [comment]
Will,
I have tested and confirmed the updated code has been moved to PClient5.
It is ready for testing in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Not fixed.  See screenshot.

![screen shot 2016-03-14 at 3 55 39 pm](https://cloud.githubusercontent.com/assets/13453008/13758000/76ab4560-e9fd-11e5-8062-b0def485747b.png)

**Comment by TimHeasley** [comment]
Hi Will,
The code update for this item is when a user is in Plan Configurator and they add a new Preferred Account Name the folder now has the correct structure to insert plan masters. If you try this process in PClient5 you will see you are able to insert a plan master to a newly created Preferred Account Name folder.

I am currently in the process of updating all of the folders that were created previously that do not have the structure to allow inserting plan masters.
I will let you know when this is complete.
Thanks,
Tim

**Comment by willdwyer** [comment]
Thanks, Tim.  Do you have an ETA as to when it will be done?  This will be included in our training to new users for uploading and assigning attributes, so we need this complete ASAP

**Comment by TimHeasley** [comment]
Will,
All of the folders **A through K** have been updated in Production. I will continue working on the updates tomorrow and will have an end of day update (unless completed earlier).
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
All of the folders have been updated in Production. 
I will continue to track new folders that are created until we are able to move the code fix for this issue from PClient5 to Production.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
This is ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Looks good.  This has my approval to move to production.

**Comment by TimHeasley** [comment]
Go-NoGo meeting to production scheduled for 3/29

**Comment by TimHeasley** [comment]
We are a Go for moving the code to Production this evening.  We will notify you tomorrow when you can test in Production.

**Comment by TimHeasley** [comment]
Code has been moved to Production and is ready for retest.

**Comment by willdwyer** [comment]
This looks good.  This item is now being closed.
