### ISSUE TITLE
Grandfather custom plans do not generate with Grandfather Custom Plan Design Type attribute

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#338]
Hello,

Per screenshot below as an example, grandfather custom plans do not generate with Grandfather Custom Plan Design Type attribute.  In below screenshot, this is a grandfathered SBC that was generated out of HighRoads, as it has the grandfather disclosure attached to it.

![screen shot 2016-02-09 at 4 56 59 pm](https://cloud.githubusercontent.com/assets/13453008/12931998/8391c0c0-cf4e-11e5-8785-3145223b6d66.png)

This defect is preventing us from testing measures for workaround for enhancement 300 (ASC Grandfather Phone # issue)

Please research and fix globally.

**Comment by michparrish** [comment]
Hi Will,
The Grandfather disclosure documents are not based off of that attribute field. They are based off of a combination of Financial Arrangement attribute and the Grandfather plan design field within the plan design.
This is not a defect, this is how it's been set up since the mapping for Grandfathered Disclosure documents has been in place. Attached is the mapping document for all Disclosure docs. The Grandfathered docs are the 3 at the end of the list.

Thank you,
Michelle

**Comment by michparrish** [comment]
[DisclosureSectionRules.xlsx](https://github.com/willdwyer/bcbsmaissuestracker/files/124914/DisclosureSectionRules.xlsx)

**Comment by willdwyer** [comment]
Hi Michelle,

So, in order to add the rule of changing Plan Design Type attribute from Custom to Grandfather Custom when the grandfather disclosure is included, this would be classified as an enhancement, and not a defect, correct?

**Comment by michparrish** [comment]
Correct - we will have to talk through requirements if you decide to submit this as an enhancement, then submit for LOE review/assessment if this requires development.

**Comment by michparrish** [comment]
There seems to be an issue with my access to add notes into GH after I post one? And it doesn't seem like I have the ability to update labels anymore? I wanted to remove 'new' since we have been talking about this.

**Comment by willdwyer** [comment]
Hi Michelle,

I am not sure why, but I can look into it.  I checked, and the settings are prompted for no restrictions to collaborators.

Let me know if you see this same issue on other items as well.  I have removed the Status - New label.

**Comment by willdwyer** [comment]
Submitting this as an enhancement.  Please provide LOE and timing estimate for implementing this.

**Comment by michparrish** [comment]
Thanks
Let's discuss requirements on Friday's weekly meeting.

**Comment by willdwyer** [comment]
To be discussed on 2/15 meeting

**Comment by willdwyer** [comment]
HighRoads is working on developing a list for all grandfathered plans in the system.  BCBSMA will then bulk update all of these to include Plan Design Type attribute - Grandfathered Custom

**Comment by TimHeasley** [comment]
Emailed IT team 3/31 for an update.

**Comment by TimHeasley** [comment]
Emailed development team 4/14.

**Comment by TimHeasley** [comment]
We have completed running the reports on standard plans.  We are working with IT to see about a report for custom plans.

**Comment by willdwyer** [comment]
Tim,

Why would you need to run a report for standards on grandfathered plans?  There are no grandfathered standard plans.  

The headline to this issue even states grandfather custom plans.

**Comment by TimHeasley** [comment]
Will,
Attached is of all of the custom grandfathered plans in Content Library.  
On the first tab you'll see all of the granfatherd plans, with the appropriate tab location next to the plan name.

Please review the plans and let us know if you have any questions.
Thanks, Tim

[2016 Grandfather Custom Plans.xlsx](https://github.com/willdwyer/bcbsmaissuestracker/files/249352/2016.Grandfather.Custom.Plans.xlsx)

**Comment by willdwyer** [comment]
BCBSMA has finished bulk editing all the custom grandfathered plans in Content Library to have the Plan Design Type attribute - Grandfather Custom.  This request will be closed.
