### ISSUE TITLE
Quick View button on Configurator - BPMS-I-25

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#340]
Hello,

This was brought to our attention by a couple of the BEs on our team.

We are requesting an enhancement for the Quick View button in configurator to operate properly.  The Quick View button shoud allow the user to preview a plan before developing.

Upon clicking the Quick View button, the user should see either:
1. a preview of the plan design details
2. a preview of the screens in the configurator

This would be highly beneficial and would save the BEs a great deal of time.

Please provide an LOE and timing estimate for implementing this.

![screen shot 2016-02-24 at 3 59 05 pm](https://cloud.githubusercontent.com/assets/13453008/13332173/c8177d70-dbce-11e5-86bb-7314d8306278.png)
9

**Comment by michparrish** [comment]
This item has been submitted as an enhancement to the Dev team. Pending assessment.

**Comment by michparrish** [comment]
I still can't update labels, so please place this in Pending status.

**Comment by TimHeasley** [comment]
This item has been submitted as an enhancement to the Dev team. Pending assessment.

**Comment by TimHeasley** [comment]
Emailed development team 3/31 for an update.

**Comment by TimHeasley** [comment]
Emailed development team 4/14.

**Comment by TimHeasley** [comment]
Emailed development team 4/27

**Comment by willdwyer** [comment]
Still no update from them?

**Comment by TimHeasley** [comment]
We received an update late yesterday - 
"I will need to dig a little bit around the parameter setting etc. But I will get back to you guys as soon as I can."
So we have a some movement on this item, as we learn more we will share with the team.
Thanks

**Comment by TimHeasley** [comment]
6/1 - Development team is researching LOE & timing for moving forward with this enhancement. Dev team is meeting 6/3 to discuss LOE & timing. As soon as we have an update we will notify the BCBSMA team.

**Comment by TimHeasley** [comment]
The development team met and discussed this enhancement  After reviewing the high level feature functions noted, they determined this is beyond an minor enhancement. The request is for a new feature which would not only include development of code but new UI.  In order for them to proceed with an LOE they need clear definition of feature sets, corresponding requirements and UI design for the new page. We can discuss on our call tomorrow.

**Comment by TimHeasley** [comment]
Will,
Is the attached plan design view an acceptable format for this enhancement?
Thanks,
Tim

![enhancement-340](https://cloud.githubusercontent.com/assets/13483804/16117030/ffe67536-339d-11e6-9914-06eabb81b378.JPG)

**Comment by willdwyer** [comment]
I will consult internally on this, and get back to you.

**Comment by TimHeasley** [comment]
We have approval from the BCBSMA team and will take the above format to our development team. As soon as we have an LOE & timing we will update here in GitHub.

**Comment by michparrish** [comment]
Enhancement was submitted to Development and LOE is as follows:
2 days
Based on requirements/business process attached:
[Quick View Requirements Document V1 20160718.docx](https://github.com/willdwyer/bcbsmaissuestracker/files/371612/Quick.View.Requirements.Document.V1.20160718.docx)
If you decide to move forward with this enhancement (please provide approval), development can be completed by the end of next week, with hopeful deployment to test environments and Prod by the following week.
Please let us know which direction you choose.
Thanks!

**Comment by willdwyer** [comment]
Hi Michelle,

You have our approval.  Please deploy this to PCLIENT5 so we can test.

**Comment by michparrish** [comment]
We'll be deploying the code tomorrow morning to pclient5. I tested in our QA env and it looks good!
please confirm this is ok - thanks!

**Comment by michparrish** [comment]
Deployment was successful into pclient5. This is ready for your review. Please let us know how it goes!

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by michparrish** [comment]
Thanks, Will - we will schedule some time to move this next week. Wednesday at earliest. I will let you know for sure when we have this scheduled to go. this will be in the evening 10-11pm timeframe. Thanks!

**Comment by willdwyer** [comment]
Just to confirm - is this still being deployed to production tonight?

**Comment by willdwyer** [comment]
Hello,

We just checked, and this wasn't moved to production last night?  Please provide a status update ASAP

**Comment by michparrish** [comment]
Sorry Will - I sent an email out to check the status yesterday with no reply. I'll see if we can get this scheduled for tonight.

**Comment by willdwyer** [comment]
OK thank you

**Comment by michparrish** [comment]
Will, this will not be making it into production tonight but I'm still pushing to have this code moved ASAP. I'll keep you posted.
Thank you for your patience.

**Comment by mattrimer** [comment]
Hi Michelle-- any update on this item?

Thanks!

**Comment by michparrish** [comment]
Hi Matt,

I'm working to hopefully get this pushed to Prod tonight. I'll keep you posted.

Thanks!

**Comment by michparrish** [comment]
Update from our IT/Dev dept - looking to post to our staging environment tomorrow and then schedule push to Prod. I'll keep you updated.

**Comment by michparrish** [comment]
Confirmed we are set to push this to Prod this coming Sunday morning, 8/14.

**Comment by willdwyer** [comment]
Looks good.  This request is now closed.
