### ISSUE TITLE
Diabetes calculator not capturing office visit deductible correctly

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#343]
Hello,

It appears HighRoads is not capturing the office visit deductible unless a frequency is specified (per calendar quarter, for instance).  It has not been discovered until now, as usually when there is an office visit deductible, it is specified as per calendar quarter.  I confirmed this after looking at the calculator requirements (per screenshot), which specifies that the calculator should pull the first $ amount if office visits is specified.

![screen shot 2016-03-10 at 11 45 03 am](https://cloud.githubusercontent.com/assets/13453008/13677490/2bdc275e-e6b8-11e5-986c-a753650c39b1.png)

I have also attached a sample PDF.
[sbc_preview-27.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/167624/sbc_preview-27.pdf)

Please fix globally

**Comment by TimHeasley** [comment]
Will,
We are researching this item and are working on a fix.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
The office visit deductible has been updated in the calculator and tested.
It is ready for retest in PClient5.  After your aproval we can move to Production.
Thanks,
Tim

**Comment by willdwyer** [comment]
Not fixed.  Now, if the calculator has a frequency specific (for instance, per calendar quarter), the calculator does not pick it up.  See screenshot below and attached PDF as an example.

![screen shot 2016-03-11 at 10 47 06 am](https://cloud.githubusercontent.com/assets/13453008/13707227/a780e94e-e776-11e5-85b7-d5b8043be622.png)
[sbc_preview-30.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/169480/sbc_preview-30.pdf)

**Comment by TimHeasley** [comment]
Will,
The calculator has been updated and is now working with the correct frequency.
Ready for retest in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Just a reminder - please send information regarding change of coding for this.

**Comment by TimHeasley** [comment]
Hi Will,
Here is the information I received regarding the calculator update -

We added an additional search on “per calendar year for medical office visits” and returned the value after the “$” if found.

**Comment by willdwyer** [comment]
OK that works.  We will proceed with testing on this.

**Comment by willdwyer** [comment]
Hi Tim,

So, in the midst of retesting, I realized there is another requirement that is missing on this.  Saver plans are not capturing the family amount here in office deductible field (capturing member amount instead).  For instance, see attached PDF.  This is a saver plan, and it specifies both a member and family amount in office deductible, but the calculator is capturing the member amount.

As I had indicated before, testing will be extensive with this item.
[sbc_preview-2.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/182599/sbc_preview-2.pdf)

Please fix globally.

**Comment by TimHeasley** [comment]
Will,
We had never programmed the ‘other deductible’ to check for saver plans for Prescription or Office visits. The calculator has been updated and ready for retest in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Thank you for testing.  The updated calculator has been moved to Production and ready to test.

**Comment by willdwyer** [comment]
Found an error in production in the diabetes calculator.

Calculations are wrong for an Advantage Blue plan.  A frequency is specified (per calendar quarter), and the diabetes calculator is pulling an amount of $100 when it should be pulling $400 ($100 x 4).

As mentioned, when changes are made, please fix globally, unless otherwise told only to fix for a specific plan/group type.

See attached PDF, and correct diabetes calculator.
![screen shot 2016-03-24 at 2 59 02 pm](https://cloud.githubusercontent.com/assets/13453008/14028049/0318d262-f1d1-11e5-8ff8-a547792059b5.png)

[sbc_preview(31).pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/188474/sbc_preview.31.pdf)
[sbc_preview(32).pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/188475/sbc_preview.32.pdf)

**Comment by TimHeasley** [comment]
Will, we will research the issue and let you know when you can retest in PClient5. Thanks.

**Comment by TimHeasley** [comment]
Will, the calculator has been updated and is ready for retest in PClient5.  Thanks

**Comment by willdwyer** [comment]
Not fixed.  See attached PDF and screenshot of what calculator should be.  Similar instance as last message.... a frequency is specified (per calendar quarter), and the diabetes calculator is pulling an amount of $75/ when it should be pulling $350 ($75 x 4).

[3557171_Lisa Test 1_Advantage_Blue_1234TEST.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/198499/3557171_Lisa.Test.1_Advantage_Blue_1234TEST.pdf)
![screen shot 2016-03-31 at 4 02 07 pm](https://cloud.githubusercontent.com/assets/13453008/14189161/f08c6698-f759-11e5-9e82-a93805db6fb0.png)

**Comment by TimHeasley** [comment]
We will update the calculator and let you know when you can retest in PClient5. Thanks.

**Comment by TimHeasley** [comment]
Will,
The updated calculator is in PClient5 and ready for retest. The issue here was that new string language was being introduced while testing and the calculator is programmed to a specific set of language. 
Thanks, Tim

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Thank you for testing.  The updated calculator has been loaded to Production.

**Comment by willdwyer** [comment]
Looks good, Tim.  This defect is now being closed.
