### ISSUE TITLE
PPO Blue Options, Specialist Drug Common Medical Event - L&E defaults to Not Covered

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#344]
Hello,

This defect was discovered by the following steps:
1. Go To Manage Plan
2. Search for:
   Effective Date - 2016
   Product Group Type - PPO Blue Options
   Plan Type - Standard
3. Click Show Me Plans
4. Hover over standard plan, click Create New Plan
5. Click Common Medical Event section
6. Go to Generic Drugs area
7. Change Cascade Options to No Cascade
8. Click Save/Validate

The Specialist Drug, Limitations & Exceptions field will default to Not Covered.  Instead, it should capture the information that was entered previously.  Please see screenshot.
<img width="794" alt="screen shot 2016-03-16 at 11 11 16 am" src="https://cloud.githubusercontent.com/assets/13453008/13817985/9de88a3e-eb6a-11e5-8488-ea8478e823b8.png">

Please fix globally.

**Comment by TimHeasley** [comment]
The services team will research and fix the issue.
As soon as complete we will let you know when you can retest.
Thanks,
Tim

**Comment by TimHeasley** [comment]
Will,
We have implemented the fix, tested in PClient5 and confirmed it is working.
Retest at your convenience.
Thanks, Tim

**Comment by willdwyer** [comment]
Looks good, please move to production.

**Comment by TimHeasley** [comment]
Updated workbook has been moved to Production.
Thanks

**Comment by willdwyer** [comment]
Looks good.  Closed
