### ISSUE TITLE
Change disclosure for PPO Blue Options template

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#345]
Hello,

Please replace the disclosure at the end of both of the templates for the following plan designs with the attached file.  Note that it is just for these 2 plan designs.

800168HR_PPO_Blue_Options_v.5_80-0222MMASCBF1-1-16
800342HR_PPO_Blue_Options_v.5_80-0222LGASC1-1-16

Let me know if you have any questions.

[55-1339_288_PPO_Blue Options v.5_159981MB_2016.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/176328/55-1339_288_PPO_Blue.Options.v.5_159981MB_2016.pdf)

**Comment by sayotte7701** [comment]
Hi Will,
I've made the updates in pclient5.  Please take a look at your convenience.

thank you

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Items have been moved to Production.
Thanks, Tim

**Comment by willdwyer** [comment]
Not fixed.  See error message we are receiving in production.

It affects ALL PPO Blue Options with disclosure(s), so this is elevated to Showstopper priority.
![screen shot 2016-03-23 at 12 00 18 pm](https://cloud.githubusercontent.com/assets/13453008/13994696/5f190e18-f0fc-11e5-947b-e18680a67456.png)

**Comment by TimHeasley** [comment]
Will, we are researching the issue and will let you know when you can retest.

**Comment by TimHeasley** [comment]
The issue has been fixed and ready for retest in Production. Thanks

**Comment by willdwyer** [comment]
Looks good.  Closed.
