### ISSUE TITLE
Produce report for monitoring changes to standard plan designs

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#348]
Hello,

We recently encountered an issue with a change to one of the standard plan designs which resulted in a non-compliant PDF produced.  We did research, and discovered the change was made by Michelle Parrish (see screenshots).  To prevent further issues from occurring, we are requesting a report to be produced that will depict any changes that are made to standard plan designs.

![screen shot 2016-03-30 at 4 29 11 pm](https://cloud.githubusercontent.com/assets/13453008/14156607/4b4125a8-f695-11e5-9501-ca14900a9b0d.png)
![screen shot 2016-03-30 at 4 30 01 pm](https://cloud.githubusercontent.com/assets/13453008/14156609/4dc90368-f695-11e5-955b-a964fd7c4e9e.png)

This is an ongoing task that will require a lot of research, and a discussion as well.

**Comment by TimHeasley** [comment]
Team meeting scheduled for Monday April 4th.

**Comment by TimHeasley** [comment]
Closing this issue, rolling into #351.
