### ISSUE TITLE
Limitations field on Routine eye care - Adult not capturing save

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#349]
Hello,

The following defect was reported by one of our BEs for generating a Blue Care Elect custom plan.

When entering a value of 'one exam every 24 months' in Limitations field in Excluded Services tab under Routine eye care - Adult, the value is not capturing when saving, and defaulting back to blank.  Please see screenshots demonstrating this.

Please fix globally ASAP.

![screen shot 2016-04-01 at 11 02 47 am](https://cloud.githubusercontent.com/assets/13453008/14216246/ccb1a06e-f815-11e5-8f78-22a1e192dfd1.png)
![unknown-6](https://cloud.githubusercontent.com/assets/13453008/14216251/d360bab2-f815-11e5-9fe6-9e773e54e105.png)

**Comment by TimHeasley** [comment]
We are researching the issue.

**Comment by TimHeasley** [comment]
Will, this is a cascading rule from the Eye Exam limitations in the Common Medical Event. Can you verify what the BE entered for Eye Exam on the Common Medical Event tab (Cascade Options and L&E)?

**Comment by willdwyer** [comment]
Thanks, Tim.  I realized the BE had selected Cascading instead of No Cascading, hence the reported defect.  We are good on this.

**Comment by willdwyer** [comment]
Hi Tim,

This is being re-opened as this was discovered to still exist by one of our BEs.  Please see plan 3578222_Tannin Corporation_HMO_Blue_NE_Ded_2000_161425BS.

When entering a value of 'one exam every 24 months' in Routine eye care - adult, and No Cascade in Eye Exam on Common Medical Event tab, it defaults to blank for the Routine eye care - adult field.  Please fix globally.

**Comment by TimHeasley** [comment]
We will research the issue and let you know when it is ready for retest in PClient5. Thanks

**Comment by willdwyer** [comment]
Hi Tim,

Any update?  (This is showstopper priority, so it needs to be fixed ASAP)

**Comment by TimHeasley** [comment]
We are working on a fix and will have it completed this afternoon.

**Comment by TimHeasley** [comment]
Will,
The issue has been fixed in PClient5 and confirmed working.  Also tested 2 tier & 4 tier plans and confirmed they are working correctly too.  Ready for retest in PClient5.
Thanks, Tim

**Comment by willdwyer** [comment]
Hi Tim,

This looks good in PCLIENT5.  Please move to production.

**Comment by TimHeasley** [comment]
Thank you for testing, the updated workbook has been moved to Production and is ready for retest.

**Comment by willdwyer** [comment]
Looks good.  This defect is now being closed.
