### ISSUE TITLE
2017 Standard Plan Copy

### ISSUE THREAD

**Issue by TimHeasley** [willdwyer/bcbsmaissuestracker#351]
This task will be kept as a reference for the process for the 2017 Standard Plan copy.
Notes:
- standard plans will be copied, no changes to data
- only changes will be updating **Job *_and *_Stock Number**

To do's:
-BCBSMA team to begin QA process of documents
-Michelle to research audit type report for standard plans

**Comment by michparrish** [comment]
Hi Will,

I researched internally and unfortunately, there is no templated or stock report that we can set up for your team to perform the 2016 plan design QA between most recent version and the version before that. 
Firstly - you have almost 400 Standard plan designs so running one report is not possible. These will have to be broken down and typically we break them down by Market Segment and, if needed, Product Family or the 'HMO Blue NE', etc. Smaller chunks.
Secondly, there is no way to set up the parameter 'choose most recent version, than the one immediately prior to that' in any of the Search or reporting criteria. So here are 2 options on how to handle that.
Option #1: 
1) Run Searches based on Plan Year = 2016, Plan Design Type = Standard, and then break down by Market Segment, etc. 
2) Select all plans in the search and click on View > Versions
go through the list and select the Most Recent and 2nd Most Recent versions of each plan design and continue to run the reports.
3) When setting up the pivot table of the report, you'd pull the Benefit Items to the rows box and Plan/Version/Benefit Set to the column box
4) You will then be able to see the comparison between the 2 versions of each plan.
PROS: you get the 'comparison' functionality of v1
CONS: You have to manually select each version of the plan design you want to run the report on

Option #2:
1) We can refresh pclient5 with most recent data
2) Run reports on all current versions of each Standard plan design (using the breakdown criteria above b/c of the limitations of search and reporting)
3) Once report is set up per the instructions in #1, bulk Delete all of the most recent versions of the standard plan designs.
4) rerun step #2, as the latest version will be the 2nd most recent version
5) once new set of reports are saved, you can do a vlookup to pull the first and 2nd versions together and conduct your compare via formulas
PROS: you don't have to manually select the versions of the plan designs you need - it's always the top one
CONS: have to wait for a pclient5 refresh, and there is formula work needed after the fact to get to the point of comparison

So either way you save time on the other, just depends if it's on the front end or back end of the process.

I hope this helps a little. I realize it's still not easy either way but at least there are options.

**Comment by willdwyer** [comment]
Michelle,

Both these options involve a lot of manual work done on our end.  The purpose of this (well, particularly item #348 is to make this process more efficient, less time consuming and streamlined.

**Comment by michparrish** [comment]
Understood, Will. Unfortunately, we cannot automate the process any further.

**Comment by willdwyer** [comment]
Hello,

So, after consulting, we have come up with a couple possible solutions...
1. Since this is a limitation of V1 in HighRoads, can HighRoads provide us with the reports based on the above? (either of the 2 options)
2. We may employ use of the Tools > Notifications function for all standard plan designs to have BEs notified if plan design data is changed.  This may have to be opened up as a separate enhancement, but is it possible to include an option in Notifications if: (1) a user selects the Edit Option (instead of Check Out/Check In), and (more ideally), (2) have a user be notified if any data in the plan design window is changed (via Edit, and then Save).

Please let us know.

**Comment by willdwyer** [comment]
Hello,

Please copy all standard plan designs for 2016 into 2017.

Also, please make 2 specific changes to all new 2017 plan designs.

For all plan designs, please 1. remove the HR Job number at the beginning of the plan name and 2. change last digit on stock number from 6 to 7.

For example, 800010HR_Access_Blue_NE_Saver_80-0116SG1-1-16 would become Access_Blue_NE_Saver_80-0116SG1-1-17

Let me know once complete.

Thank you,

**Comment by michparrish** [comment]
Thanks, Will, for the detailed instructions.

Do you have a timeframe as to when you require this work to be completed by? Tim is out on vacation this week, just an FYI. I'd like to plan alternate resources if need be.
Thanks!
Michelle

**Comment by willdwyer** [comment]
End of this week (Friday, May 27th) would be great.

**Comment by michparrish** [comment]
Ok - we can try. I'll provide you with an update on Friday as to how far we get. Hopefully we'll be able to complete it by then.
Thanks!

**Comment by michparrish** [comment]
Hi Will,

I just want to confirm what HighRoads is doing vs what your team would maybe want to do.

HighRoads:
- Set up new plan masters under the 2017_1-1 folders
- Copy all 2016 Standard plans into the new/mirrored plan masters - Small Group-Access Blue Local 2016 plans go into the Small Group-Access Blue Local 2017, for instance
- Rename all 2017 plan designs per the instructions you stated above
- Ensure all Revision tags for new 2017 plans states '1-2017'

BCBSMA:
- Conduct a compare of folders to ensure that all plans have been copied

Outstanding:
- The Plan Year attribute will need to be changed from 2016 to 2017. Does your team want to conduct the bulk attribute update or do you want HighRoads to make this update?
- Effective Date (YYYY) attribute also needs to be updated to 2017. Same question applies (these can both be done at the same time via bulk attribute editing).

Please let me know - thank you!

**Comment by willdwyer** [comment]
Hi Michelle,

This all looks correct.  And yes, we can handle the bulk attribute editing.

**Comment by michparrish** [comment]
Hi Will,

I just want to confirm - looks like you've already done the copy for the Connector plans, is that correct? I believe I recall Tim having copied these over or been involved somehow. Just want to be sure I can delete out the ones I copied in today. Thanks!

**Comment by willdwyer** [comment]
Michelle,

That is correct.  The copy is complete for the connector plans.  HR just needs to complete the copy for Small Group 1-50, Large Group 51-99 and Large Group 100+

**Comment by michparrish** [comment]
perfect, thank you!

**Comment by michparrish** [comment]
Hi Will,
One more question re: the Connector plans/overall count. Are you expecting there to be less 2017 plans b/c of the Connector plans already being copied? for 2016 there are 13 Connector plans but there only look to be 7 Connector plans in the 2017 folders.
Please confirm - I am running reports to make sure the #s are right. As it stands now, I have 366 2017 plans but 372 2016 plans. The differences of the 6 Connector plans is what is in question. Thanks!

**Comment by willdwyer** [comment]
Correct.  Some of the connector plans have been cancelled for 2017.  I have already deleted those from content library.

**Comment by michparrish** [comment]
Hi Will,

The Standard Plan Copy for 2017 is complete. 
Attached is a report for the compare of the plans and the naming conventions. I've kept the original 2016 names in one column, carried over to the next with the Job Number trimmed off and the year of the date trimmed off so I could compare 1:1. There was only one plan that I took the liberty of updating b/c it had a period in the date part ("1-.1-16"). I didn't update the 2016 version, only the 2017 version.
Please let me know if you see any issues. 
Also, these are ready for the bulk editing of the attributes. To remind, the following will need to be updated:
Revision number from 1-2016 to 1-2017
Plan Year from 2016 to 2017
Effective Date (YYYY) from 2016 to 2017

Thanks!
[bcbs 2017 copy compare.xlsx](https://github.com/willdwyer/bcbsmaissuestracker/files/287017/bcbs.2017.copy.compare.xlsx)

**Comment by TimHeasley** [comment]
We talked to legal and audit about our current SBC page counts and they would like us to reduce the current compliance risk by incorporating the 2017 template rule that allows the SBC to be a rolling document with no page breaks after sections.

Task    Resources:
Build a mock of the current template removing the table headers and page breaks - Lisa & Sean
Highroads requirements for the change - Matt & Will
Enhancement estimate - Mark

We have one question regarding this request that we need validated as we determine the LOE. 
Is this to support the new 2017 template only OR for all 2017 plans beginning in January?
-It is potential changes to the current template

**Comment by willdwyer** [comment]
All set.
