### ISSUE TITLE
Primary Care Visit - No Cascade selected, overriding value on HMO Blue Essential plan

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#353]
Hello,

See screenshots.  This was discovered on standard plan 800023HR_HMO_Blue_Essential_80-0249SG1-1-16

When selecting No Cascade and saving, the defaulted value on the standard plan changes to a different value.  Note that this on the standard plan, so any customs generated out of it may be affected.

Please fix across all market segments ASAP

![screen shot 2016-04-08 at 11 12 02 am](https://cloud.githubusercontent.com/assets/13453008/14393255/eb44624a-fd93-11e5-928c-9837b9111aba.png)
![screen shot 2016-04-08 at 11 12 22 am](https://cloud.githubusercontent.com/assets/13453008/14393595/c96a3da0-fd95-11e5-83c0-d0416568ba26.png)

**Comment by TimHeasley** [comment]
We are working on a fix for this item. We will let you know when you can retest. Thanks

**Comment by TimHeasley** [comment]
Will,
Can you let us know the full string you were trying to type into the PCP field? 
This will help us fix the logic that is implemented for the eligible options.
Thanks, Tim

**Comment by willdwyer** [comment]
**$35 / visit (or 50% coinsurance, whichever is less) for first 3 visits per calendar year; no charge for additional visits**

Note that this value is default on the standard plan 800023.

**Comment by TimHeasley** [comment]
Thank you for sending the details.  
The workbooks have been updated and are ready for retest in PClient5.

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by TimHeasley** [comment]
Thank you for testing. The updated workbooks have been loaded to Production.

**Comment by willdwyer** [comment]
Fixed.  Closed
