### ISSUE TITLE
Imaging - No Cascade selected, overriding value on Blue Care Elect plan

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#354]
Hello,

See screenshots. This was discovered on standard plan 
800294HR_Blue_Care_Elect_Pref_80-0177LGASC1-1-16

When selecting No Cascade and saving, the defaulted value on the standard plan changes to a different value. Note that this is on the standard plan, so any customs generated out of it may be affected.

Please fix across all market segments ASAP

![screen shot 2016-04-20 at 10 24 03 am](https://cloud.githubusercontent.com/assets/13453008/14679288/2a402464-06e7-11e6-8c52-1bca1debf328.png)
![screen shot 2016-04-20 at 10 24 21 am](https://cloud.githubusercontent.com/assets/13453008/14679291/2d7ecbd0-06e7-11e6-944f-ca4650d4882e.png)

**Comment by TimHeasley** [comment]
We are researching the issue and will let you know the outcome once completed.

**Comment by TimHeasley** [comment]
Will, the workbooks have been updated and are ready for retest in PClient5. Thanks

**Comment by willdwyer** [comment]
Tim, before I proceed with re-testing, can you please explain why we continue to have defects with the cascading portion of the generator?

**Comment by TimHeasley** [comment]
It was (& has been) a parsing issue, the formulas were interpreting as an unparsed eligible option.

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by michparrish** [comment]
Moved to Prod - thanks!

**Comment by willdwyer** [comment]
Looks good.  Closed.
