### ISSUE TITLE
Default ALL Cascade Options fields to No Cascade across ALL standard and custom plans in configurator

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#355]
Hello,

We are requesting to default the Cascade Options field to No Cascade instead of Cascade All for all plans in configurator.

Please complete globally.

**Comment by michparrish** [comment]
Hi Will,

Since these are values within each plan design, that would be a manual bulk upload update to your Prod data. This is not a change to the workbooks, as you may think. The values were updated into each plan design when we added the fields last year and when they render on the Configurator, the user can change them and the formulas within the workbook function off of the values chosen.

I don't believe we should be making updates to your Prod data but this is something your team could certainly update.

**Comment by willdwyer** [comment]
Hi Michelle,

I suppose we could do this manually.

However, can you confirm that the values are the same for ALL types of plans?

![screen shot 2016-04-22 at 11 58 01 am](https://cloud.githubusercontent.com/assets/13453008/14747627/48495258-0883-11e6-86ab-774b60f995b9.png)

**Comment by michparrish** [comment]
Hi Will,

The values you note above are the defaults that we populated into each plan last year when we created the 2016 plans with these new fields. If your users have ever changed those values to the others in the dropdowns in specific plans that didn't require cascading or required specific cascading, then no, all plans would not currently have those values in them.

If you want to use the 2015 to 2016 compare report that we just posted for you - you can see all of the 2016 plans as they are now ("Updated" tab, as of the date we ran those reports, late last week) and see which plans have which values. Note, those are only the Standard plans, though.

When making the updates, remember that there is a workbook behind the scenes so the formatting needs to be exactly right. So all changes to no cascading should be 'No Cascade' (without apostrophes) - no additional leading or ending spaces. 

Just for your reference, attached is a copy of all of the possible cascading options that each field has.
[Cascade values by field.xlsx](https://github.com/willdwyer/bcbsmaissuestracker/files/232513/Cascade.values.by.field.xlsx)

**Comment by willdwyer** [comment]
Thanks.

We will use this report as a prerequisite for changing all the default values from Cascade to No Cascade

**Comment by michparrish** [comment]
excellent - yes, use that report for whatever you want. QA, this exercise, etc. It's yours!

**Comment by willdwyer** [comment]
This was completed internally by BCBSMA, with assistance from HR.  This is now being closed.
