### ISSUE TITLE
Please set up PCLIENT5 permissions for Kaitlin Pisano (KPISAN01)

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#358]
Hello,

Please set up PCLIENT5 access for KPISAN01.

When complete, please send me her log-in and pw.

Thanks,

**Comment by TimHeasley** [comment]
Hi Will,
Setting up of new users usually goes customer support team.  I sent them the information from this GitHub item and they have set up access for Kaitlin.

-As requested I have set up Kaitlin's account (KPISAN01) in Pclient5. 
I have used the password BCBSM@4uat1!

Thanks, Tim

**Comment by willdwyer** [comment]
All set, thanks.

And, I will refrain from sending these in GitHub in future.

**Comment by TimHeasley** [comment]
Thanks Will,
No worries, just want to make sure new users are setup as quick as possible for you & your team.
