### ISSUE TITLE
Incorrect wording on 2016 SG 1-50 Pediatric Dental Disclosures

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#361]
Hello,

It was recently discovered that there is incorrect wording on all the 2016 standard small group 1-50 disclosures.  When generating any of these plans, the pediatric dental disclosures _currently_ read as follows:

"This policy includes coverage of pediatric dental services as required under the federal Patient Protection and Affordable Care Act."

This disclosure _should_ read as follows:

"Your health plan coverage includes a dental policy that covers pediatric dental services as required under the federal Patient Protection and Affordable Care Act."

Also note: all 2015 standard small group 1-50 plans have the correct disclosure wording, and per disclosure requirement submitted to HighRoads in June, 2015 (attached), there were to be no changes made in disclosure wording from 2015 to 2016.

Please make the adjustment(s) to all 2016 standard small group 1-50 plans, and let us know once complete.

[2016 Disclosure Requirement 6.17.15.docx](https://github.com/willdwyer/bcbsmaissuestracker/files/266677/2016.Disclosure.Requirement.6.17.15.docx)

**Comment by TimHeasley** [comment]
Hi Will,
If you could send us an updated 55-0613 Pediatric Dental disclosure document we can make the change.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

Please see attached.

[55-0613_Pediatric Dental (BCBSMA plans).pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/268983/55-0613_Pediatric.Dental.BCBSMA.plans.pdf)

**Comment by TimHeasley** [comment]
Will,
The updated disclosure has been uploaded into Production and is ready for retest.
Thanks,
Tim

**Comment by willdwyer** [comment]
All set.  Closed.
