### ISSUE TITLE
Template change - MCC Does Meet Compliance for Attached Plans

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#362]
Hello,

Please change the MCC Disclosure on the following plans from the Does Not Meet disclosure to the Does Meet disclosure in PCLIENT5 environment.  I have attached a copy of this disclosure, as well.
[55-0647_MCC_Meets_152993MB_2016.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/277884/55-0647_MCC_Meets_152993MB_2016.pdf)

800032HR_HMO_Blue_NE_Ded_3000_80-0240HCCSSG1-1-16
800031HR_HMO_Blue_NE_Ded_3000_80-0240SG1-1-16
800011HR_Blue_Care_Elect_Ded_3000_80-0132SG1-1-16
800075HR_Blue_Care_Elect_Ded_3000_80-0132MM1-1-16
800138HR_Blue_Care_Elect_Ded_3000_80-0132MMASCBF1-1-16
800096HR_HMO_Blue_NE_Ded_3000_80-0240MM1-1-16
800097HR_HMO_Blue_NE_Ded_3000_80-0240HCCSMM1-1-16
800155HR_Network_Blue_NE_Ded_3000_80-0240MMASCBF1-1-16
800184HR_Blue_Care_Elect_Ded_3000_80-0132LG1-1-16
800289HR_Blue_Care_Elect_Ded_3000_80-0132LGASC1-1-16
800246HR_HMO_Blue_NE_Ded_3000_80-0240LG1-1-16
800247HR_HMO_Blue_NE_Ded_3000_80-0240HCCSLG1-1-16

**Comment by michparrish** [comment]
Hi Will,
I can certainly upload the new pdf for you. That's all set!
Is your team able to regenerate those documents by bulk editing the MCC value from 'Does not meet' to 'Meets' and generate a new doc with disclosures?

**Comment by willdwyer** [comment]
Yes, we can do the bulk editing.

Just to confirm - this was done in PCLIENT5, and not production, right?

**Comment by michparrish** [comment]
Great!
No, the new document was uploaded into Prod so you could regenerate compliant docs in Prod.
Sorry, I missed the pclient5 detail - do you need compliant docs in the test env?

**Comment by willdwyer** [comment]
Michelle,

Is it possible to reverse this change in production, and solely make the change in PCLIENT5?

**Comment by michparrish** [comment]
Yes - all set. I've removed the latest version of the MCC - Meets document in prod so it's back to the last one.
I've uploaded the newest one attached to this item into pclient5.

**Comment by willdwyer** [comment]
Perfect.  Thanks, Michelle.

**Comment by TimHeasley** [comment]
Currently waiting for BCBSMA sales team confirmation on changes.

**Comment by willdwyer** [comment]
Hello,

We have received confirmation from our sales team on this.  Please make the switch in PCLIENT5, so we can retest.  Just as reminder on what must be done...

Please change the MCC Disclosure on the following plans from the Does Not Meet disclosure to the Does Meet disclosure in PCLIENT5 environment. I have attached a copy of this disclosure, as well.

800032HR_HMO_Blue_NE_Ded_3000_80-0240HCCSSG1-1-16
800031HR_HMO_Blue_NE_Ded_3000_80-0240SG1-1-16
800011HR_Blue_Care_Elect_Ded_3000_80-0132SG1-1-16
800075HR_Blue_Care_Elect_Ded_3000_80-0132MM1-1-16
800138HR_Blue_Care_Elect_Ded_3000_80-0132MMASCBF1-1-16
800096HR_HMO_Blue_NE_Ded_3000_80-0240MM1-1-16
800097HR_HMO_Blue_NE_Ded_3000_80-0240HCCSMM1-1-16
800155HR_Network_Blue_NE_Ded_3000_80-0240MMASCBF1-1-16
800184HR_Blue_Care_Elect_Ded_3000_80-0132LG1-1-16
800289HR_Blue_Care_Elect_Ded_3000_80-0132LGASC1-1-16
800246HR_HMO_Blue_NE_Ded_3000_80-0240LG1-1-16
800247HR_HMO_Blue_NE_Ded_3000_80-0240HCCSLG1-1-16
800032HR_HMO_Blue_NE_Ded_3000_80-0240HCCSSG1-1-17
800031HR_HMO_Blue_NE_Ded_3000_80-0240SG1-1-17
800011HR_Blue_Care_Elect_Ded_3000_80-0132SG1-1-17
800075HR_Blue_Care_Elect_Ded_3000_80-0132MM1-1-17
800138HR_Blue_Care_Elect_Ded_3000_80-0132MMASCBF1-1-17
800096HR_HMO_Blue_NE_Ded_3000_80-0240MM1-1-17
800097HR_HMO_Blue_NE_Ded_3000_80-0240HCCSMM1-1-17
800155HR_Network_Blue_NE_Ded_3000_80-0240MMASCBF1-1-17
800184HR_Blue_Care_Elect_Ded_3000_80-0132LG1-1-17
800289HR_Blue_Care_Elect_Ded_3000_80-0132LGASC1-1-17
800246HR_HMO_Blue_NE_Ded_3000_80-0240LG1-1-17
800247HR_HMO_Blue_NE_Ded_3000_80-0240HCCSLG1-1-17

[55-0647_MCC_Meets_152993MB_2016(2).pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/381809/55-0647_MCC_Meets_152993MB_2016.2.pdf)

**Comment by cfieldsHR** [comment]
Hi Will, I'm filling in for Michelle this week - Could your team bulk edit the plan's MCC value from 'Does not meet' to 'Meets' to generate new docs with the disclosures?

**Comment by willdwyer** [comment]
Looks good, Chris.  This is now being closed.

Thanks,
