### ISSUE TITLE
HighRoads Certificate Renewal

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#363]
Hello,

The certificate that is used in Production to support SSO is expiring on June 27th.  Can you please open a request with your support team to deploy the updated certificate?

We would like to schedule this for either night of: Thursday, June 16th or Tuesday, June 21st (9 PM either day).  Please let us know which night works for you.

**Comment by michparrish** [comment]
Hi Will,
We're aware of the certification renew and are already working on it.
We will deploy during the regularly scheduled HighRoads maintenance time - date of update still to come.

**Comment by willdwyer** [comment]
Hi Michelle,

Do you have a date for this yet?

**Comment by willdwyer** [comment]
Hi Michelle,

Can you please let us know today if HR confirmed a date?  We are anticipating a date of either 6/16 or 6/21.  We need adequate lead time to make sure the right people will be available.

Thanks,

**Comment by michparrish** [comment]
Hi Will,
I reached out to IT yesterday re: your question. I just followed back up with them. It seems we may be waiting for something from your side but I'm trying to get the specifics so you can reach out to whomever is responsible.
Thanks for your patience.

**Comment by willdwyer** [comment]
Thanks, Michelle.  Please note that we are getting pressure from our IT department to get this scheduled, so dub this as Showstopper priority.

**Comment by michparrish** [comment]
Understood.
Here is the request from our IT Dept, if you can get this from yours?
HighRoads IT requires the certificate to apply.  Please can you provide details on the server/transfer appliance (i.e. sFTP) at BCBSMA that HighRoads’ IT Operations team can download it from.

**Comment by willdwyer** [comment]
Hi Michelle,

Please see below.

BlueWeb-TFIM-HighRoads.bcbsma.com 

https://certmanager.websecurity.symantec.com/mcelp/enroll/searchCertDetails?issuerSerial=bc2be132feb9153b6b9b530bde50e26d&jur_hash=b976ae55a42bf979f99cdea9ee12555a

**Comment by TimHeasley** [comment]
Meeting scheduled for 6/13 @ 1 pm.

**Comment by TimHeasley** [comment]
• Action Item:  HighRoads has received a link to the certificate and is reviewing the existing documentation in preparation for deployment.
• Action Item:  Deployment scheduled for 6/16 at 10pm.
• Action Item:  Matt Soleyn will send calendar invite for deployment on 6/16 at 10 pm.  Conference call line will be opened to communicate during deployment.
• Validated Assumption:  BCBSMA/HR SSO Certificates expire on 6/28
• Decision:  Existing SSO Certificates will be uploaded by both HighRoads and BCBSMA.  Back out plan will be to revert back to existing certificate, test/validate, and immediately assess any issue(s) and agree on next steps.  
• Decision:  Deployment of new certificate will be on 6/16 during the HighRoads Maintenance Window (10 pm – 11 pm) with the following schedule:  
![sso certificate](https://cloud.githubusercontent.com/assets/13483804/16117224/031f605e-339f-11e6-9f43-45b53c40c912.JPG)

**Comment by TimHeasley** [comment]
Update: Postponed until Tuesday, June 21st.

**Comment by willdwyer** [comment]
All set.  This item is being closed now.
