### ISSUE TITLE
Abortion not appearing as a Covered Service in 2017 plans

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#364]
Hello,

This defect was discovered through the following steps:
1. Search for and Edit plan design HMO_Blue_NE_Ded_1000_80-0114HCCSSG1-1-17
2. In Excluded Services section, change Abortion to Covered
3. Save
4. Check In plan design
5. Click checkbox next to plan design, select Edit, Go To Manage Plan
6. Hover over plan, click Plan Document Options
7. Proceed to generate SBC
8. On SBC, go to Excluded Services section, and note that Abortion is missing.

See screenshots.  
![screen shot 2016-06-13 at 4 07 30 pm](https://cloud.githubusercontent.com/assets/13453008/16021791/9473c488-3182-11e6-92a7-6c2cadda8a10.png)
![screen shot 2016-06-13 at 4 09 32 pm](https://cloud.githubusercontent.com/assets/13453008/16021792/9475ca3a-3182-11e6-9ca1-42ddbc26b2e9.png)

Note that there has been a regulation change for 2017 SBCs that we will now have to begin noting if Abortion is covered on Small Group 1-50 and Connector SBCs, so this is a High priority fix.

**Comment by TimHeasley** [comment]
We will research the issue and let you know when you can retest.

**Comment by willdwyer** [comment]
Hi Tim,

We just met internally to discuss this issue, and we can't produce any SG 2017 SBCs until this is resolved, so this will be elevated to Showstopper priority.

**Comment by TimHeasley** [comment]
We are working through the issue and hope to have it ready for you soon. Thanks

**Comment by TimHeasley** [comment]
Will,
This regulation change is an enhancement request and it’s going to take some testing.
We do have a question - is this supposed to show on all plans, or just the 2 the new regulation applies to?
Thanks, Tim

**Comment by willdwyer** [comment]
Tim,

Why would this be classified as an enhancement?  This should be part of the process; if a plan design is classified as Covered, then it should appear in the Excluded Services section.

And, we will only need this for Small Group 1-50 and Connector SBCs.

**Comment by willdwyer** [comment]
Hi Tim,

What's the status with this?  This is a critical item and must be fixed by HighRoads ASAP.  Please regard this as top priority, as we cannot generate any 2017 Small Group or Connector SBCs until this is complete.

**Comment by TimHeasley** [comment]
We are currently testing in PClient5 and will let you know today when you can test.

**Comment by willdwyer** [comment]
Thanks.  While you're doing that, please be sure that there are Small Group 1-50 and Connector plan designs in content library so that we can test appropriately.

**Comment by TimHeasley** [comment]
Will,
We have updated the 2 tier PPO workbook and it is ready for retest in PClient5.  Abortion now appears on the Excluded Services tab and you can select either Covered or Not Covered.  For Abortion to appear on the plan you must enter text in the Limitations box. The Limitation text that is entered will appear on the plan design. 
Please test at your convenience. After you approve we will update the other workbooks. 
Thanks, Tim

**Comment by willdwyer** [comment]
Tim,

There are currently no 2017 standard Preferred Blue PPO plan designs in PCLIENT5.  Which ones were updated?  This is specific to 2017 Small Group 1-50 and Connector plan designs (2016 plan designs should not be affected).  As specified earlier, please be sure there are small group 1-50 and connector plan designs in content library so we may be able to test appropriately.

Thanks,

**Comment by willdwyer** [comment]
Tim, I just went to generate one of the 2016 plan designs in PCLIENT5, and notice the update(s) has been made to 2016 plan designs.  As specified, this should only be for 2017 small group 1-50 and connector plans.

Also, why do we have to input text in the Limitations box for Abortion to appear?  This will not work for us.  For 2017 Small Group 1-50 and Connector plans, Abortion should be regarded and function as any other item in Excluded Services.  There will be several instances where Abortion will not have data in the Limitations box.  Please make this adjustment, and note that this item is critical, as we cannot generate any compliant 2017 small group1-50 or connector SBCs unless this is fixed.

**Comment by TimHeasley** [comment]
Will, 
For this update we need to change multiple workbooks in order for this field to show in the Configurator.  We added this field to all plan designs during last year’s annual copy, so we can’t just update only certain workbooks or zone in on certain plan types. Though this field has been available in each plan design since last year’s 2016 plan copy, it wasn’t visible in the workbook b/c you didn’t yet want to use it. The workbooks are based on Product Type and Tier, not Market Segment.  In order to cover all of the plan types in Small Group and Connector, we had to update the Indemnity, PPO 2-3-4 tier, & HMO 2-3-4 tier workbooks.  

In order for us to make this bullet point show on ONLY Small Group or Connector plans, by using the current process we have today and only use configuration (and not have to update code), is to update our backend ‘capture file’ with a User Defined Field that is used to do 2 things – 1) add the bullet point and 2) put the service in the correct box.   The reason that you have to add input text is so that Abortion (whether covered or not covered) only appears on those Small Group or Indemnity plan designs. When you add the value ‘Abortion’ into the Limitations field in the Configurator, this triggers the bullet to show. We could default this in the capture file, but then it would show for all plans, not just Small Group and Connector. 

Then, by selecting the ‘Covered’ or ‘Not covered’, this places the bullet in the proper box. This is the way that the capture file was set to work with the workbooks.

If you like we can refresh PClient5 with Prod data so you have 2017 plans to work with, but we will need to pull out the current items (#341 & #362) that your team is testing in PClient5.
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

We are not completely happy with the outcome, but definitely need a resolution for this, as we have to specify whether or not Abortion is covered for 2017 Small Group and Connector plan designs.

For the original proposed solution (having to manually type Abortion in the Limitations box for all plans), is this something that would be a 'one and done'?  In other words, if we were to generate a custom out of one of the 2017 Small Group plan designs, I assume the 'Abortion' text in the Limitations box would carry over from the standard, correct?  Also, if you have to update the plan designs, and insert Abortion as a field in Excluded Services for all plan designs, would you be able to just insert the text Abortion in the Limitations box for all Small Group and Connector plan designs?

And, as far as pulling out the coding for items #341 and #362, would this be able to be re-installed once PCLIENT5 data is updated with Prod data?  (we definitely don't want to outright abandon these 2 items)

**Comment by TimHeasley** [comment]
Will,
Understood, that is why we did so much research to see possible options.

Correct for the original proposed solution and inserting the input text. You can bulk edit those specific plan designs and it'll be there for you so you don't have to do it in the Configurator. You could also use Global Find/Replace which would be much quicker.

Yes, we could pull out the items being used for items #341 and #362, and they would be added after the refresh.

Thanks, Tim

**Comment by willdwyer** [comment]
OK, we will consult on this internally tomorrow and let you know if we want to proceed with the re-testing in PCLIENT5.

**Comment by willdwyer** [comment]
Please proceed with the testing in PCLIENT5 for this.

**Comment by TimHeasley** [comment]
Will,
Can you clarify your above comment? 
-Did you want us update the rest of the workbooks so you can test in PClient5
or
-Should we refresh PClient5
Just trying to understand next steps.
Thanks, Tim

**Comment by willdwyer** [comment]
Well, we need to test plans in PCLIENT5, so both tasks need to be done.

1st - refresh PCLIENT5
2nd - update rest of workbooks so we can test in PCLIENT5

**Comment by TimHeasley** [comment]
All of the workbooks are updated, they will be loaded to PClient5 after the refresh.  We will work on having the refresh on Monday 6/27.  Once we know timing we will share with you & your team.

**Comment by willdwyer** [comment]
Thanks.

Since HR will begin working on this 6/27, can they have this done by EOD 6/28?

**Comment by TimHeasley** [comment]
Will, 
Would it be ok to do the refresh today at noon?  Or do you have another time you prefer?
Also, as a part of IT's new process they need your consent / understanding that all of your data on PClient5 will be overwritten.
Thanks, Tim

**Comment by TimHeasley** [comment]
The refresh has been completed for PClient5 and you can log in.  I am in the process of reloading workbooks & disclosures that were being tested. As soon as they have been loaded and tested I will let you know when you can retest. Thanks

**Comment by TimHeasley** [comment]
Will,
All workbooks & mapping have been updated and tested in PClient5.
Ready for retest.
Thanks, Tim

**Comment by willdwyer** [comment]
Hi Tim,

Please add the following 2 disclosures to the SG 1-50 HMO Blue Select plans (these 5 below).  Please make the change in PCLIENT5, and we will proceed with testing.

900389HR_Access_Blue_Select_Saver_2000_80-0280SG1-1-17
900390HR_HMO_Blue_Select_Ded_1000_80-0281SG1-1-17
900391HR_HMO_Blue_Select_Ded_1000_Copay_80-0282SG1-1-17
900392HR_HMO_Blue_Select_Ded_2000_80-0283SG1-1-17
900393HR_HMO_Blue_Select_Ded_2000_Copay_80-0284SG1-1-17
900394HR_HMO_Blue_Select_Ded_3000_80-0285SG1-1-17

**Comment by TimHeasley** [comment]
Disclosure rules have been updated, tested in PClient5 (800390) and appears correctly.
Ready for retest.

**Comment by willdwyer** [comment]
Sorry, Tim.  I posted the above comment in the wrong item.  That pertains to #365

**Comment by TimHeasley** [comment]
No worries, I thought that might be the case.
I'll copy the comments above over to #365.

**Comment by willdwyer** [comment]
Thanks, Tim.  Looks good.  Please move to production.

**Comment by willdwyer** [comment]
Disregard last comment.  Not quite ready to move to production yet.

**Comment by willdwyer** [comment]
Thanks, Tim.

Looks good.  Please move to production.

**Comment by willdwyer** [comment]
Hi Tim,

Has the move to production been completed?

**Comment by TimHeasley** [comment]
Items have now been moved to Production and are ready to use.

**Comment by willdwyer** [comment]
This appears to be resolved.  Request closed.
