### ISSUE TITLE
Error generating 2017 PDF

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#366]
Hello,

This was an error reported by one of our BEs.  See screenshot; it seems we are unable to generate.  Is this is a disclosure issue?
![unknown](https://cloud.githubusercontent.com/assets/13453008/16583499/f20ddffe-4283-11e6-80a8-d3ec42f3a8b4.png)

**Comment by TimHeasley** [comment]
Will,
I believe this is tied in with issue #362 and the update.  The disclosure rules are looking for disclosure **55-0647_MCC_Meets 2015**.  I have looked for this disclosure and I am unable to find it.  Can you send it to me and I can make the update.
Thanks, Tim

**Comment by willdwyer** [comment]
Hi Tim,

Please see attached.

[55-0647_MCC_Meets_152993MB_2016.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/347776/55-0647_MCC_Meets_152993MB_2016.pdf)

**Comment by TimHeasley** [comment]
Thank you for sending, the disclosure rules have been updated and ready for retest in Production.

**Comment by willdwyer** [comment]
Looks good.  Closed.
