### ISSUE TITLE
Unable to log into PCLIENT5

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#367]
Hello,

Please see screenshot.  We are currently unable to log into PCLIENT5.  We are trying password BCBSM@4uat1!

<img width="1075" alt="screen shot 2016-07-05 at 9 18 46 am" src="https://cloud.githubusercontent.com/assets/13453008/16585973/82744f30-4291-11e6-9701-4da4f026566c.png">

**Comment by willdwyer** [comment]
Hi,

Any update on this?

**Comment by TimHeasley** [comment]
I know support was working on fixing the logins. I checked with them and will let you know as soon as you & your team can access PClient5.

**Comment by TimHeasley** [comment]
All PClient5 logins are fixed and ready for use.

**Comment by willdwyer** [comment]
All set, thanks.

This is now closed.
