### ISSUE TITLE
1-1-17 HMONE $1000 Copayment HCCS 51-99 - Disclosures Listed In The Wrong Order

### ISSUE THREAD

**Issue by mattrimer** [willdwyer/bcbsmaissuestracker#368]
When generating a PDF from this plan design [900089HR_HMO_Blue_NE_Ded_1000_Copay_80-0272HCCSMM1-1-17], I noticed that the disclosures are listed incorrectly. The HCCS disclosure is listed first, followed by the MCC Compliance disclosure.

The correct order should be:
- 55-0647 MCC Compliance
- 55-0532 HCCS

Let me know when this is fixed so I can retest.

Thanks!

**Comment by mattrimer** [comment]
UPDATE:

It looks like this issue is occurring on all templates generated today (this was not happening yesterday).

The correct order of the disclosures (where applicable) should be as follows:
- MCC or Non-MCC
- Pedi Dental
- HCCS or Options
- Select Limited Network
- Limited Regional Consumer Guide
- Chapter 61

Let me know if you have any questions.

**Comment by michparrish** [comment]
Hi Matt - is this in Prod? I just want to be sure. Thanks

**Comment by mattrimer** [comment]
Yes it is

**Comment by michparrish** [comment]
thanks - where do the Grandfathered ones fall?

**Comment by mattrimer** [comment]
Grandfathered should come somewhere after MCC/Non-MCC. You can keep it wherever it is currently as long as MCC/Non-MCC appears first.

The real problem that we've been encountering is that MCC was appearing last, after the other disclosures. The order of the others isn't as important as long as they are consistent throughout all plans.

Does that makes sense?

**Comment by michparrish** [comment]
ok - yeah, i'm not sure how the order got out of place, so I'm setting it up again now. The grandfathered ones look a little scattered so I want to put them all together in the right spot.

**Comment by michparrish** [comment]
Ok - I left the grandfathered ones where they were and updated everything else (I believe). Updated into Prod. Let me know if you see anything out of order.

**Comment by mattrimer** [comment]
The MCC Compliance is now in the correct place.

However, I noticed that with some small group plans, the Limited Regional Consumer Guide is not appearing (PB$1000 w/ HCCS; PB$2000 w/HCCS, for example). This disclosure appeared last week, and is now missing.

Let me know when this issue is fixed and I'll retest.

Thanks!

**Comment by michparrish** [comment]
Are those plans in question updated with the proper attributes? Here are the attributes needed to add the Limited Regional Consumer Guide:
market segment = Small Group 1-50
Product Identifier = HCCS, Tiered Network or Select Limited Network
Product Type = HMO or HMO-Type

Looking at the 2 plans you note above, they are listed as Product Type = PPO

Unless I'm looking at the wrong Disclosure doc. Do you have the # of the doc? I'm looking at 55-0249/Limited Regional Tiered Provider Consumer Guide.

**Comment by mattrimer** [comment]
The product type should have no bearing on the Limited Regional Consumer Guide disclosure.

Only the Market segment (Small Group 1-50) and the Product Identifier (HCCS, Tiered Network or Select Limited Network) should be considered.

All small group products with any of the three listed product identifiers should have this disclosure.

**Comment by mattrimer** [comment]
And yes, 55-0249 is correct.

**Comment by michparrish** [comment]
Ok - all references to Product Type for the doc 55-0249 have been removed and the mapping doc uploaded into Prod.
Please retest.

**Comment by mattrimer** [comment]
I retested this and it looks good. I think we can close this item.

Thanks Michelle!

**Comment by michparrish** [comment]
Excellent!! have a great weekend!

**Comment by michparrish** [comment]
...apparently I don't know how to close them so I'll let you guys.
