### ISSUE TITLE
Advantage Blue templates missing Prescription Drug website on Common Medical Events section

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#371]
Hello,

We noticed that for the Advantage Blue (EPO) template, the website is missing in the Common Medical Events section "If you need drugs to treat your illness or condition".  Please see screenshot.

The website input should be www.bluecrossma.com/medications.

Please fix globally ASAP.

<img width="910" alt="screen shot 2016-08-17 at 2 14 57 pm" src="https://cloud.githubusercontent.com/assets/13453008/17747941/13103404-6485-11e6-9b7a-f60392705e37.png">

**Comment by michparrish** [comment]
Hi Will,

Looks like this plan design doesn't have data filled into the Rx Contact Info field. This field is not available in the Configurator so someone will have to fill it in manually from Content Library.
This is the 2nd field below the 'Common Medical Event' header.

**Comment by willdwyer** [comment]
Hi Michelle,

I will try to update and let you know if I have any issues.

**Comment by willdwyer** [comment]
All set, Michelle.  Thanks,
