### ISSUE TITLE
Cannot access Manage Plan interface in PCLIENT5

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#372]
Hello, see screenshot below.  We encounter this when clicking Manage Plan in PCLIENT5.  Please fix ASAP.

![screen shot 2016-08-18 at 1 45 25 pm](https://cloud.githubusercontent.com/assets/13453008/17784426/8063ad4a-654a-11e6-882f-7e8ec0ba457f.png)

**Comment by michparrish** [comment]
known issue as of this morning - we are in the process of working on it. I'll let you know when we're back up and running.

**Comment by michparrish** [comment]
Issue is fixed - please try again. Thank you and so sorry for the wait.

**Comment by michparrish** [comment]
Will, do you think we can close this one too since you essentially were just able to test the calculator issue out in pclient5?

**Comment by willdwyer** [comment]
Yes, this one can be closed as well.
