### ISSUE TITLE
Diabetes calculator not calculating correctly for Options Ded III plans

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#373]
Hello,

Please see the 2 attached SBCs, and manual screenshots taken of the Diabetes calculators for these 2 plans.  As noted, the copays should add up to $1350, not $1490 (in the SBCs generated off HighRoads).  We have been unable to find a discrepancy, so this appears to be an issue with HighRoads.  Please research and fix globally.
![screen shot 2016-08-19 at 3 44 00 pm](https://cloud.githubusercontent.com/assets/13453008/17822225/d8d4dc40-6623-11e6-88ee-bbc39f404ec7.png)
![screen shot 2016-08-19 at 3 43 13 pm](https://cloud.githubusercontent.com/assets/13453008/17822228/dd23b87a-6623-11e6-9668-bf7fd4f93f10.png)
[Preferred_Blue_Options_Ded III_v.5_80-0279MM1-1-17.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/427765/Preferred_Blue_Options_Ded.III_v.5_80-0279MM1-1-17.pdf)
[HMO_Blue_NE_Options_Ded_III_v.5_80-0258SG1-1-17.pdf](https://github.com/willdwyer/bcbsmaissuestracker/files/427766/HMO_Blue_NE_Options_Ded_III_v.5_80-0258SG1-1-17.pdf)

**Comment by michparrish** [comment]
Hi Will,

The calculator has been fixed and uploaded into pclient5. Please retest and let us know if it's good to push to production.
Thanks!

**Comment by willdwyer** [comment]
Thanks, Michelle.  Before we start testing, do you know what the issue was?

**Comment by cfieldsHR** [comment]
Hi Will, The issue was related to Laboratory test, the 0 value was not being pulled into the calculator correctly when the value was "No Charge" + ($35 for hospitals).

**Comment by willdwyer** [comment]
Looks good.  Please move to production.

**Comment by cfieldsHR** [comment]
Coverage Calculator has been updated in Production

**Comment by willdwyer** [comment]
Looks good.  Closed.
