### ISSUE TITLE
Carve Out plans - Rx website in 'If you need drugs to treat your illness or condition' field... font color is black; should be blue

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#377]
Hello,

When generating a Carve Out plan, the www._____.com website in the field 'If you need drugs to treat your illness or condition' is black and should be blue.  See screenshots below.

1st screenshot is the color of what the website should be.
2nd screenshot is the color of what the website currently is.

Please resolve ASAP.

![unknown-4](https://cloud.githubusercontent.com/assets/13453008/18848000/6bf666c6-83fa-11e6-9c7c-f41d7e3ebf06.png)
![unknown-3](https://cloud.githubusercontent.com/assets/13453008/18848001/6c015734-83fa-11e6-9d4b-d1cddb034260.png)

**Comment by michparrish** [comment]
all set - updated and uploaded into pclient5 and prod, since it was a simple template update and you needed it ASAP. let me know if there are any issues.

**Comment by michparrish** [comment]
has this item been retested and confirmed? if so, please close - thanks!

**Comment by willdwyer** [comment]
Looks good.  Closed.
