### ISSUE TITLE
Green dot appearing in search screen

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#379]
Hello,

See screenshot.  There is a green dot appearing in the search results screen with the message "Renewal preparations are not required at this time"

This doesn't seem to be affecting anything, but we can't determine its purpose?

Please advise.
<img width="1194" alt="screen shot 2016-09-29 at 3 59 27 pm" src="https://cloud.githubusercontent.com/assets/13453008/18970186/49d54f88-865e-11e6-8578-4bc4e65e48b0.png">

**Comment by michparrish** [comment]
this is used in thresholds for Renewals, another module of CMS. You do not need to worry about this.

**Comment by michparrish** [comment]
Sorry - not Threshold, but someone set the Renewal Date in the attributes on this.
Sent email

**Comment by willdwyer** [comment]
Perfect.  Thanks, Michelle.  That was something we just never used, so were unfamiliar with it.  Either way, this request can now be closed.
