### ISSUE TITLE
Account number list does not filter for all account names

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#68]
```
What steps will reproduce the problem?
1. Once you are logged in the HR System, click Manage Plan in toolbar
2. In the ‘Plan Search’ screen, enter:
Effective Date – 2015
Financial Arrangement – Insured
Market Segment – Large Group 100+
Product Type – HMO
Click search
3. Hover over top plan, click Edit Plan
4. On Plan Details screen, enter Aquire for Account Name… then click on 
Account # field below
5. Note account #s
6. Then, click x on Account Name, and then enter A-1 Exterminators, Inc… then 
click on Account # field below
7. Note account #s

Actual Result:
Account #s do not filter

Expected Result:
Account #s should filter for all preferred account names.

Test Case #
MPI_PD_02


```

Original issue reported on code.google.com by `wcd82...@gmail.com` on 13 May 2015 at 5:15

Attachments:
- [Screen Shot 2015-05-13 at 12.11.24 PM.png](https://storage.googleapis.com/google-code-attachments/bcbsmaissuestracker/issue-68/comment-0/Screen Shot 2015-05-13 at 12.11.24 PM.png)
- [Screen Shot 2015-05-13 at 12.10.41 PM.png](https://storage.googleapis.com/google-code-attachments/bcbsmaissuestracker/issue-68/comment-0/Screen Shot 2015-05-13 at 12.10.41 PM.png)

**Comment by willdwyer** [comment]
Hello,

So we received an updated account name/account number list from sales.  There are some account names that are still blank, but this is acceptable, as they're non-official/prospective accounts.  They are at the bottom of the spreadsheet, and highlighted in yellow or orange.

Please see the spreadsheet per the link below, and make the updates to HighRoads.  Let me know once complete.

https://drive.google.com/open?id=0B0v09uxs7ITkcDNKNXo2ZnUxZGc

**Comment by michparrish** [comment]
Thank you! I'll forward to the team and we'll figure out resources to get this done.

**Comment by michparrish** [comment]
Steve H is coordinating the effort to get the list updated. This should be finished in a couple of weeks. We'll post when finished.

**Comment by willdwyer** [comment]
Hi Michelle,

Do you have an approximate date as to when this update will be completed by?  Please let me know.

**Comment by michparrish** [comment]
@willdwyer we are hoping to complete by 8/17. We are tight with resources right now but we'll do what we can to get this completed as soon as possible. Does that date work for you?

**Comment by willdwyer** [comment]
Hi Michelle, I'm sorry I didn't see this, but 8/17 works for us.

**Comment by michparrish** [comment]
Confirmation of completion sent to Will under separate cover with list of missing accounts or items left blank by Will. These changes will carry overnight with the refresh into pclient5 where BCBS can test.

**Comment by willdwyer** [comment]
Hi Michelle,

I tested some of the account numbers, and noticed that a lot of the ones we had input on the spreadsheet were missing (see screenshots).  I noticed on the spreadsheet we sent to you, the new ones were not highlighted; instead, just the ones that don't have matching account numbers for them.  If need be, I can highlight the ones on the spreadsheet we sent to you that were new, and missing from when we originally posted this item in the tracker.  Please let me know.

![screen shot 2015-08-18 at 5 08 42 pm](https://cloud.githubusercontent.com/assets/13453008/9343262/df5a3054-45ce-11e5-9323-937678ab788a.png)
![screen shot 2015-08-18 at 5 04 19 pm](https://cloud.githubusercontent.com/assets/13453008/9343263/df5e314a-45ce-11e5-8683-9fc67c44e9da.png)
![screen shot 2015-08-18 at 5 03 53 pm](https://cloud.githubusercontent.com/assets/13453008/9343264/df63eb12-45ce-11e5-941e-4dc323c88365.png)

**Comment by michparrish** [comment]
Will - my apologies, that was an oversight on my part. I had only updated the ones that I had found going through the list, and had missed a step when updating so they didn't take. I have included the ones that you had updated as well, but updated in Prod rather than pclient5. Steve had made all of his updates, so you should be able to use the latter half of the list for training.
Please check Prod and let me know if all looks good.
if you want to send an updated spreadsheet for the ones you know were missing from the first list, that would be great. Thank you.
here's just a pic of the updated Barbarian client:
![updated values](https://cloud.githubusercontent.com/assets/13471811/9345267/25fe9c80-45dd-11e5-9127-1e74db8332e3.JPG)

**Comment by markderg** [comment]
Looking to close out item upon your approval.  Let us know...Thx, Mark

**Comment by willdwyer** [comment]
Hi Michelle,

Not account names and number have been accounted for, yet.  (see screenshots).  Note that I tested in production.
![screen shot 2015-08-20 at 10 12 38 am](https://cloud.githubusercontent.com/assets/13453008/9385372/166cecd4-4724-11e5-96aa-e4a260978b98.png)
![screen shot 2015-08-20 at 10 08 52 am](https://cloud.githubusercontent.com/assets/13453008/9385373/166d9076-4724-11e5-8186-5c8d5be80d74.png)
![screen shot 2015-08-20 at 9 58 44 am](https://cloud.githubusercontent.com/assets/13453008/9385374/167041f4-4724-11e5-8ed9-09bcd1d37c02.png)
![screen shot 2015-08-20 at 9 58 18 am](https://cloud.githubusercontent.com/assets/13453008/9385371/166cf210-4724-11e5-8273-5382d8a42075.png)

I will send a spreadsheet in a separate email with all new account names and account numbers highlighted in yellow, and will exclude those that do not have matching account numbers for them.  Please re-assess, and let me know once complete.

**Comment by michparrish** [comment]
Hi Will - we did not set up those that were missing the account names b/c that means that they have not yet had SBCs created for them. When a user first creates plan designs and generates folders for them, they can add in the new Account Name into the Configurator and it will create itself with the folder structure. No need to include these on the list. For instance, Amigo was not on the original list, and Entergy and Fleetmatics did not have an account name set up yet in the system.
MSPCA is actually associated to a number, but not the number on the sheet. I'll fix this now.

**Comment by michparrish** [comment]
Hi Will,
From the list that you sent, we will not be setting up the following accounts b/c they do not yet exist, meaning they haven't had SBCs created for them yet. When a user creates their docs for the first time, they can add it as a new Account Name, along with the new Account Number, and then we can do that weekly/biweekly/monthly linking process.
Codman Square Health Center 
Comverse Technology, Inc. 
Entergy Corporation 
Fleetmatics 
Harvard University Group Health Plan (HUGHP) 
Harvard University Student Health Plan 
Liberty Mutual 

MSPCA was fixed.

Please confirm this is all set. Thank you!

**Comment by willdwyer** [comment]
Michelle,

Is it solely the account names you provided above that won't be included on the list?

Because I just went to look for an account number for Amego, Inc. and Arbella Insurance Group (on the spreadsheet I sent via email, and they have not been matched.

**Comment by michparrish** [comment]
Sorry, didn't scroll up to get them all. Also  not created:
Alere, Inc. 
Berkshire Children and Families 
Boston Beer Company Corporation 
Boston Trust and Investment Management Co. 

I had to fix Amego and Arbella. Now the entire list has been vetted.

**Comment by willdwyer** [comment]
Hi Michelle,

I just retested, and this looks good.  I will close this item now.

I'm going to make some updates to the Ops Manual for account name/account number management, as well as for LOVs.
